[workspace]
members = [
    "apps/daemon",
]
resolver = "2"

[profile.dev]
incremental = false
debug = 1

[profile.test]
incremental = false
debug = 1

[workspace.package]
edition = "2021"
license = "MIT"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
incremental = false
debug = 1
strip = "symbols"
panic = "abort"
codegen-units = 1
