use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};
use std::fmt;
use zeroize::Zeroizing;

const KEY_BYTES: usize = 32;
const SIGNATURE_BYTES: usize = 64;
const MAX_DEVICE_ID_BYTES: usize = 64;
const MAX_DISPLAY_NAME_BYTES: usize = 96;
const DOMAIN_CERTIFICATE: &[u8] = b"another-dimension/daemon/device-certificate/v1";
const DOMAIN_REVOCATION: &[u8] = b"another-dimension/daemon/device-revocation/v1";
const DOMAIN_MLS_CREDENTIAL: &[u8] = b"another-dimension/daemon/mls-credential/v1";

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum IdentityError {
    RandomnessUnavailable,
    InvalidSeed,
    InvalidDeviceId,
    InvalidDisplayName,
    InvalidRelayOrigin,
    InvalidCertificate,
    ExpiredCertificate,
    CertificateNotYetValid,
    DeviceAlreadyRevoked,
}

impl fmt::Display for IdentityError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::RandomnessUnavailable => "secure randomness is unavailable",
            Self::InvalidSeed => "identity seed is invalid",
            Self::InvalidDeviceId => "device id is invalid",
            Self::InvalidDisplayName => "display name is invalid",
            Self::InvalidRelayOrigin => "relay origin is invalid",
            Self::InvalidCertificate => "device certificate is invalid",
            Self::ExpiredCertificate => "device certificate is expired",
            Self::CertificateNotYetValid => "device certificate is not active yet",
            Self::DeviceAlreadyRevoked => "device is already revoked",
        })
    }
}

impl std::error::Error for IdentityError {}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AccountId(String);

impl AccountId {
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Clone)]
pub struct AccountRootKey {
    signing_key: SigningKey,
}

impl fmt::Debug for AccountRootKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("AccountRootKey")
            .field("account_id", &self.account_id().as_str())
            .field("private_key", &"[redacted]")
            .finish()
    }
}

impl AccountRootKey {
    pub fn generate() -> Result<Self, IdentityError> {
        let mut seed = [0_u8; KEY_BYTES];
        getrandom::fill(&mut seed).map_err(|_| IdentityError::RandomnessUnavailable)?;
        Ok(Self::from_seed(seed))
    }

    pub fn from_seed(seed: [u8; KEY_BYTES]) -> Self {
        Self {
            signing_key: SigningKey::from_bytes(&seed),
        }
    }

    pub fn public_key(&self) -> [u8; KEY_BYTES] {
        self.signing_key.verifying_key().to_bytes()
    }

    pub fn seed_bytes(&self) -> Zeroizing<[u8; KEY_BYTES]> {
        Zeroizing::new(self.signing_key.to_bytes())
    }

    pub fn account_id(&self) -> AccountId {
        account_id_from_public(&self.public_key())
    }

    pub fn account_id_from_public_key(public_key: [u8; KEY_BYTES]) -> AccountId {
        account_id_from_public(&public_key)
    }

    pub fn sign(&self, message: &[u8]) -> [u8; SIGNATURE_BYTES] {
        self.signing_key.sign(message).to_bytes()
    }

    pub fn issue_device(
        &self,
        device_id: impl Into<String>,
        protocol_package_hash: [u8; KEY_BYTES],
        issued_at: u64,
        expires_at: u64,
    ) -> Result<DeviceIdentity, IdentityError> {
        let device_id = validate_device_id(device_id.into())?;
        if expires_at <= issued_at {
            return Err(IdentityError::InvalidCertificate);
        }
        let device_key = generate_signing_key()?;
        let certificate = DeviceCertificate::signed(
            &self.signing_key,
            device_id,
            device_key.verifying_key().to_bytes(),
            protocol_package_hash,
            issued_at,
            expires_at,
        );
        Ok(DeviceIdentity {
            signing_key: device_key,
            certificate,
        })
    }

    /// Issue a certificate for a key generated by another device. The private
    /// key is supplied only as a public key and never enters this process.
    pub fn issue_device_for_public_key(
        &self,
        device_id: impl Into<String>,
        device_public_key: [u8; KEY_BYTES],
        protocol_package_hash: [u8; KEY_BYTES],
        issued_at: u64,
        expires_at: u64,
    ) -> Result<DeviceCertificate, IdentityError> {
        let device_id = validate_device_id(device_id.into())?;
        if expires_at <= issued_at {
            return Err(IdentityError::InvalidCertificate);
        }
        Ok(DeviceCertificate::signed(
            &self.signing_key,
            device_id,
            device_public_key,
            protocol_package_hash,
            issued_at,
            expires_at,
        ))
    }

    pub fn revoke_device(
        &self,
        certificate: &DeviceCertificate,
        revoked_at: u64,
    ) -> Result<DeviceRevocation, IdentityError> {
        if certificate.revoked || certificate.account_public_key != self.public_key() {
            return Err(IdentityError::DeviceAlreadyRevoked);
        }
        let message = revocation_message(
            &self.public_key(),
            &certificate.device_id,
            &certificate.device_public_key,
            revoked_at,
        );
        let signature = self.signing_key.sign(&message).to_bytes();
        Ok(DeviceRevocation {
            account_public_key: self.public_key(),
            device_id: certificate.device_id.clone(),
            device_public_key: certificate.device_public_key,
            revoked_at,
            signature,
        })
    }
}

pub struct DeviceIdentity {
    signing_key: SigningKey,
    certificate: DeviceCertificate,
}

impl fmt::Debug for DeviceIdentity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("DeviceIdentity")
            .field("device_id", &self.certificate.device_id)
            .field("private_key", &"[redacted]")
            .finish()
    }
}

impl DeviceIdentity {
    pub fn certificate(&self) -> &DeviceCertificate {
        &self.certificate
    }
    pub fn device_id(&self) -> &str {
        &self.certificate.device_id
    }
    pub fn public_key(&self) -> [u8; KEY_BYTES] {
        self.signing_key.verifying_key().to_bytes()
    }
    pub fn seed_bytes(&self) -> Zeroizing<[u8; KEY_BYTES]> {
        Zeroizing::new(self.signing_key.to_bytes())
    }

    /// Application-owned binding for the future MLS credential adapter.
    /// This is not an OpenMLS credential object.
    pub fn mls_credential_binding(&self) -> MlsCredentialBinding {
        let payload = credential_message(&self.certificate);
        MlsCredentialBinding {
            account_public_key: self.certificate.account_public_key,
            device_id: self.certificate.device_id.clone(),
            device_public_key: self.certificate.device_public_key,
            protocol_package_hash: self.certificate.protocol_package_hash,
            issued_at: self.certificate.issued_at,
            expires_at: self.certificate.expires_at,
            certificate_signature: self.certificate.signature,
            device_proof: self.signing_key.sign(&payload).to_bytes(),
        }
    }
}

#[derive(Clone, Eq, PartialEq)]
pub struct MlsCredentialBinding {
    account_public_key: [u8; KEY_BYTES],
    device_id: String,
    device_public_key: [u8; KEY_BYTES],
    protocol_package_hash: [u8; KEY_BYTES],
    issued_at: u64,
    expires_at: u64,
    certificate_signature: [u8; SIGNATURE_BYTES],
    device_proof: [u8; SIGNATURE_BYTES],
}

impl fmt::Debug for MlsCredentialBinding {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("MlsCredentialBinding")
            .field(
                "account_id",
                &account_id_from_public(&self.account_public_key).as_str(),
            )
            .field("device_id", &self.device_id)
            .field("proof", &"[redacted]")
            .finish()
    }
}

impl MlsCredentialBinding {
    pub fn account_id(&self) -> AccountId {
        account_id_from_public(&self.account_public_key)
    }
    pub fn account_public_key(&self) -> [u8; KEY_BYTES] {
        self.account_public_key
    }
    pub fn device_id(&self) -> &str {
        &self.device_id
    }
    pub fn protocol_package_hash(&self) -> [u8; KEY_BYTES] {
        self.protocol_package_hash
    }

    pub fn verify(&self, now: u64) -> Result<(), IdentityError> {
        let certificate = DeviceCertificate {
            account_public_key: self.account_public_key,
            device_id: self.device_id.clone(),
            device_public_key: self.device_public_key,
            protocol_package_hash: self.protocol_package_hash,
            issued_at: self.issued_at,
            expires_at: self.expires_at,
            signature: self.certificate_signature,
            revoked: false,
        };
        certificate.verify(now)?;
        let device = VerifyingKey::from_bytes(&self.device_public_key)
            .map_err(|_| IdentityError::InvalidCertificate)?;
        device
            .verify_strict(
                &credential_message(&certificate),
                &Signature::from_bytes(&self.device_proof),
            )
            .map_err(|_| IdentityError::InvalidCertificate)
    }
}

#[derive(Clone, Eq, PartialEq)]
pub struct DeviceCertificate {
    account_public_key: [u8; KEY_BYTES],
    device_id: String,
    device_public_key: [u8; KEY_BYTES],
    protocol_package_hash: [u8; KEY_BYTES],
    issued_at: u64,
    expires_at: u64,
    signature: [u8; SIGNATURE_BYTES],
    revoked: bool,
}

impl fmt::Debug for DeviceCertificate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("DeviceCertificate")
            .field(
                "account_id",
                &account_id_from_public(&self.account_public_key).as_str(),
            )
            .field("device_id", &self.device_id)
            .field("issued_at", &self.issued_at)
            .field("expires_at", &self.expires_at)
            .field("revoked", &self.revoked)
            .field("signature", &"[redacted]")
            .finish()
    }
}

impl DeviceCertificate {
    fn signed(
        root: &SigningKey,
        device_id: String,
        device_public_key: [u8; KEY_BYTES],
        protocol_package_hash: [u8; KEY_BYTES],
        issued_at: u64,
        expires_at: u64,
    ) -> Self {
        let account_public_key = root.verifying_key().to_bytes();
        let message = certificate_message(
            &account_public_key,
            &device_id,
            &device_public_key,
            &protocol_package_hash,
            issued_at,
            expires_at,
        );
        Self {
            account_public_key,
            device_id,
            device_public_key,
            protocol_package_hash,
            issued_at,
            expires_at,
            signature: root.sign(&message).to_bytes(),
            revoked: false,
        }
    }

    pub fn account_id(&self) -> AccountId {
        account_id_from_public(&self.account_public_key)
    }
    pub fn account_public_key(&self) -> [u8; KEY_BYTES] {
        self.account_public_key
    }
    pub fn device_id(&self) -> &str {
        &self.device_id
    }
    pub fn device_public_key(&self) -> [u8; KEY_BYTES] {
        self.device_public_key
    }
    pub fn protocol_package_hash(&self) -> [u8; KEY_BYTES] {
        self.protocol_package_hash
    }
    pub fn issued_at(&self) -> u64 {
        self.issued_at
    }
    pub fn expires_at(&self) -> u64 {
        self.expires_at
    }
    pub fn is_revoked(&self) -> bool {
        self.revoked
    }

    pub fn signature(&self) -> [u8; SIGNATURE_BYTES] {
        self.signature
    }

    pub fn from_parts(
        account_public_key: [u8; KEY_BYTES],
        device_id: String,
        device_public_key: [u8; KEY_BYTES],
        protocol_package_hash: [u8; KEY_BYTES],
        issued_at: u64,
        expires_at: u64,
        signature: [u8; SIGNATURE_BYTES],
        revoked: bool,
    ) -> Result<Self, IdentityError> {
        let certificate = Self {
            account_public_key,
            device_id,
            device_public_key,
            protocol_package_hash,
            issued_at,
            expires_at,
            signature,
            revoked,
        };
        certificate.verify_signature()?;
        Ok(certificate)
    }

    pub fn apply_revocation(&mut self, revocation: &DeviceRevocation) -> Result<(), IdentityError> {
        // A valid certificate may be revoked after its natural expiry. Verify
        // the root signature, not the current validity window.
        self.verify_signature()?;
        revocation.verify(self)?;
        self.revoked = true;
        Ok(())
    }

    pub fn verify(&self, now: u64) -> Result<(), IdentityError> {
        if self.revoked {
            return Err(IdentityError::InvalidCertificate);
        }
        if now < self.issued_at {
            return Err(IdentityError::CertificateNotYetValid);
        }
        if now >= self.expires_at {
            return Err(IdentityError::ExpiredCertificate);
        }
        if self.expires_at <= self.issued_at || validate_device_id(self.device_id.clone()).is_err()
        {
            return Err(IdentityError::InvalidCertificate);
        }
        self.verify_signature()
    }

    fn verify_signature(&self) -> Result<(), IdentityError> {
        if self.expires_at <= self.issued_at || validate_device_id(self.device_id.clone()).is_err()
        {
            return Err(IdentityError::InvalidCertificate);
        }
        let key = VerifyingKey::from_bytes(&self.account_public_key)
            .map_err(|_| IdentityError::InvalidCertificate)?;
        let signature = Signature::from_bytes(&self.signature);
        let message = certificate_message(
            &self.account_public_key,
            &self.device_id,
            &self.device_public_key,
            &self.protocol_package_hash,
            self.issued_at,
            self.expires_at,
        );
        key.verify_strict(&message, &signature)
            .map_err(|_| IdentityError::InvalidCertificate)
    }

    fn matches_revocation(&self, revocation: &DeviceRevocation) -> bool {
        self.account_public_key == revocation.account_public_key
            && self.device_id == revocation.device_id
            && self.device_public_key == revocation.device_public_key
    }
}

#[derive(Clone, Eq, PartialEq)]
pub struct DeviceRevocation {
    account_public_key: [u8; KEY_BYTES],
    device_id: String,
    device_public_key: [u8; KEY_BYTES],
    revoked_at: u64,
    signature: [u8; SIGNATURE_BYTES],
}

impl fmt::Debug for DeviceRevocation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("DeviceRevocation")
            .field("device_id", &self.device_id)
            .field("revoked_at", &self.revoked_at)
            .field("signature", &"[redacted]")
            .finish()
    }
}

impl DeviceRevocation {
    pub fn verify(&self, certificate: &DeviceCertificate) -> Result<(), IdentityError> {
        if !certificate.matches_revocation(self)
            || validate_device_id(self.device_id.clone()).is_err()
        {
            return Err(IdentityError::InvalidCertificate);
        }
        let key = VerifyingKey::from_bytes(&self.account_public_key)
            .map_err(|_| IdentityError::InvalidCertificate)?;
        let signature = Signature::from_bytes(&self.signature);
        let message = revocation_message(
            &self.account_public_key,
            &self.device_id,
            &self.device_public_key,
            self.revoked_at,
        );
        key.verify_strict(&message, &signature)
            .map_err(|_| IdentityError::InvalidCertificate)
    }

    pub fn revoked_at(&self) -> u64 {
        self.revoked_at
    }
    pub fn device_id(&self) -> &str {
        &self.device_id
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProfileIdentity {
    account_id: AccountId,
    display_name: String,
    relay_origin: Option<String>,
}

impl ProfileIdentity {
    pub fn from_account(
        root: &AccountRootKey,
        display_name: impl Into<String>,
        relay_origin: Option<String>,
    ) -> Result<Self, IdentityError> {
        let display_name = display_name.into();
        if display_name.is_empty()
            || display_name.len() > MAX_DISPLAY_NAME_BYTES
            || display_name.chars().any(|ch| ch.is_control())
        {
            return Err(IdentityError::InvalidDisplayName);
        }
        if let Some(origin) = &relay_origin {
            if !valid_relay_origin(origin) {
                return Err(IdentityError::InvalidRelayOrigin);
            }
        }
        Ok(Self {
            account_id: root.account_id(),
            display_name,
            relay_origin,
        })
    }

    pub fn account_id(&self) -> &AccountId {
        &self.account_id
    }
    pub fn display_name(&self) -> &str {
        &self.display_name
    }
    pub fn relay_origin(&self) -> Option<&str> {
        self.relay_origin.as_deref()
    }
}

fn generate_signing_key() -> Result<SigningKey, IdentityError> {
    let mut seed = [0_u8; KEY_BYTES];
    getrandom::fill(&mut seed).map_err(|_| IdentityError::RandomnessUnavailable)?;
    Ok(SigningKey::from_bytes(&seed))
}

fn validate_device_id(value: String) -> Result<String, IdentityError> {
    if value.is_empty()
        || value.len() > MAX_DEVICE_ID_BYTES
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
    {
        return Err(IdentityError::InvalidDeviceId);
    }
    Ok(value)
}

fn account_id_from_public(public_key: &[u8; KEY_BYTES]) -> AccountId {
    AccountId(format!("ad1pk{}", encode_hex(public_key)))
}

fn certificate_message(
    account: &[u8; KEY_BYTES],
    device_id: &str,
    device: &[u8; KEY_BYTES],
    package: &[u8; KEY_BYTES],
    issued: u64,
    expires: u64,
) -> Vec<u8> {
    let mut message = Vec::with_capacity(256);
    message.extend_from_slice(DOMAIN_CERTIFICATE);
    append_bytes(&mut message, account);
    append_bytes(&mut message, device_id.as_bytes());
    append_bytes(&mut message, device);
    append_bytes(&mut message, package);
    message.extend_from_slice(&issued.to_be_bytes());
    message.extend_from_slice(&expires.to_be_bytes());
    message
}

fn revocation_message(
    account: &[u8; KEY_BYTES],
    device_id: &str,
    device: &[u8; KEY_BYTES],
    revoked_at: u64,
) -> Vec<u8> {
    let mut message = Vec::with_capacity(160);
    message.extend_from_slice(DOMAIN_REVOCATION);
    append_bytes(&mut message, account);
    append_bytes(&mut message, device_id.as_bytes());
    append_bytes(&mut message, device);
    message.extend_from_slice(&revoked_at.to_be_bytes());
    message
}

fn credential_message(certificate: &DeviceCertificate) -> Vec<u8> {
    let mut message = Vec::with_capacity(256);
    message.extend_from_slice(DOMAIN_MLS_CREDENTIAL);
    append_bytes(&mut message, &certificate.account_public_key);
    append_bytes(&mut message, certificate.device_id.as_bytes());
    append_bytes(&mut message, &certificate.device_public_key);
    append_bytes(&mut message, &certificate.protocol_package_hash);
    message.extend_from_slice(&certificate.issued_at.to_be_bytes());
    message.extend_from_slice(&certificate.expires_at.to_be_bytes());
    append_bytes(&mut message, &certificate.signature);
    message
}

fn append_bytes(output: &mut Vec<u8>, value: &[u8]) {
    output.extend_from_slice(&(value.len() as u32).to_be_bytes());
    output.extend_from_slice(value);
}

fn valid_relay_origin(value: &str) -> bool {
    let Some((scheme, rest)) = value.split_once("://") else {
        return false;
    };
    if scheme != "http" && scheme != "https"
        || rest.is_empty()
        || rest.contains('/')
        || rest.contains('@')
        || rest.contains('?')
        || rest.contains('#')
        || rest.chars().any(|ch| ch.is_whitespace())
    {
        return false;
    }
    true
}

fn encode_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut result = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        result.push(HEX[(byte >> 4) as usize] as char);
        result.push(HEX[(byte & 0x0f) as usize] as char);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::{AccountRootKey, IdentityError, ProfileIdentity};

    #[test]
    fn root_identity_is_stable_and_display_name_is_not_identity() {
        let root = AccountRootKey::from_seed([7; 32]);
        let first = root.account_id();
        let profile_a =
            ProfileIdentity::from_account(&root, "Reporter", Some("https://relay.example".into()))
                .unwrap();
        let profile_b = ProfileIdentity::from_account(
            &root,
            "Different name",
            Some("https://other.example".into()),
        )
        .unwrap();
        assert_eq!(first, root.account_id());
        assert_eq!(profile_a.account_id(), &first);
        assert_ne!(profile_a, profile_b);
        assert_eq!(first.as_str().len(), 69);
    }

    #[test]
    fn device_certificate_requires_root_signature_and_expiry() {
        let root = AccountRootKey::from_seed([9; 32]);
        let device = root.issue_device("macbook-air", [3; 32], 100, 200).unwrap();
        assert_eq!(device.certificate().verify(150), Ok(()));
        assert_eq!(
            device.certificate().verify(200),
            Err(IdentityError::ExpiredCertificate)
        );
        let mut altered = device.certificate().clone();
        altered.protocol_package_hash = [4; 32];
        assert_eq!(altered.verify(150), Err(IdentityError::InvalidCertificate));
    }

    #[test]
    fn root_can_revoke_only_the_certified_device() {
        let root = AccountRootKey::from_seed([11; 32]);
        let device = root.issue_device("phone", [5; 32], 100, 200).unwrap();
        let revocation = root.revoke_device(device.certificate(), 150).unwrap();
        assert_eq!(revocation.verify(device.certificate()), Ok(()));
        let other = root.issue_device("tablet", [6; 32], 100, 200).unwrap();
        assert_eq!(
            revocation.verify(other.certificate()),
            Err(IdentityError::InvalidCertificate)
        );
        let mut certificate = device.certificate().clone();
        certificate.apply_revocation(&revocation).unwrap();
        assert!(certificate.is_revoked());
        assert_eq!(
            certificate.verify(160),
            Err(IdentityError::InvalidCertificate)
        );
    }

    #[test]
    fn profile_metadata_has_strict_non_identity_validation() {
        let root = AccountRootKey::from_seed([13; 32]);
        assert!(ProfileIdentity::from_account(&root, "", None).is_err());
        assert!(
            ProfileIdentity::from_account(&root, "ok", Some("ftp://relay.example".into())).is_err()
        );
        assert!(ProfileIdentity::from_account(
            &root,
            "ok",
            Some("https://relay.example/path".into())
        )
        .is_err());
        assert!(
            ProfileIdentity::from_account(&root, "ok", Some("https://relay.example".into()))
                .is_ok()
        );
    }

    #[test]
    fn mls_credential_binding_requires_root_certificate_and_device_proof() {
        let root = AccountRootKey::from_seed([17; 32]);
        let device = root.issue_device("laptop", [21; 32], 1, 100).unwrap();
        let binding = device.mls_credential_binding();
        assert_eq!(binding.verify(50), Ok(()));
        let mut altered = binding.clone();
        altered.protocol_package_hash = [22; 32];
        assert_eq!(altered.verify(50), Err(IdentityError::InvalidCertificate));
        let mut wrong_device = binding.clone();
        wrong_device.device_proof[0] ^= 1;
        assert_eq!(
            wrong_device.verify(50),
            Err(IdentityError::InvalidCertificate)
        );
    }
}
