[package]
name = "another-dimension-web-crypto-wasm"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
another-dimension-crypto = { path = "../crypto" }
argon2 = { version = "0.5.3", default-features = false, features = ["alloc", "zeroize"] }
getrandom = { version = "0.3.4", features = ["wasm_js"] }
serde_json = "1.0"
vodozemac = { version = "0.10.0", default-features = false, features = ["experimental-session-config", "js", "low-level-api"] }
wasm-bindgen = "0.2.121"

[lints]
workspace = true
