#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_EVIDENCE_PACKAGE_CHECKSUM_GUARD_AUDIT.md"
GUARD="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_EVIDENCE_PACKAGE_CHECKSUM_NON_CLAIM_GUARD.md"

test -f "$DOC"

grep -q 'Audit status: checksum guard coverage audit only, not release evidence' "$DOC"
grep -q 'RELEASE_SIGNING_CANDIDATE_EVIDENCE_PACKAGE_CHECKSUM_NON_CLAIM_GUARD.md' "$DOC"
grep -q 'fixture checksum coverage is not release evidence' "$DOC"
grep -q 'no real release artifact checksum verification exists' "$DOC"
grep -q 'no signed artifact verification evidence exists' "$DOC"
grep -q 'not release-ready or v0.1-security-ready' "$DOC"
grep -q 'real release artifact checksums have been verified' "$DOC"
grep -q 'real release artifact hashes have been compared against `SHA256SUMS`' "$DOC"
grep -q 'detached signatures have been verified for a release candidate' "$DOC"
grep -q 'artifact authenticity has been proven' "$DOC"
grep -q 'candidate evidence has been collected' "$DOC"
grep -q 'release signing has been approved' "$DOC"
grep -q 'a release candidate has been approved' "$DOC"
grep -q 'release hardening gates have passed' "$DOC"
grep -q 'does not checksum real release artifacts' "$DOC"
grep -q 'does not compare real release artifact hashes against `SHA256SUMS`' "$DOC"
grep -q 'does not verify detached signatures' "$DOC"
grep -q 'does not prove artifact authenticity' "$DOC"
grep -q 'does not collect candidate-specific release evidence' "$DOC"
grep -q 'Checksum guard coverage is not release evidence' "$DOC"
grep -q 'Checksum guard coverage is not signed artifact verification' "$DOC"
grep -q 'Checksum guard coverage is not release approval' "$DOC"

grep -q 'Guard status: checksum non-claim guard only, not release evidence' "$GUARD"
grep -q 'Checksum and digest coverage remains fixture-only' "$GUARD"
grep -q 'fixture checksum coverage is not release evidence' "$GUARD"
grep -q 'no real release artifact checksum verification exists' "$GUARD"
grep -q 'no signed artifact verification evidence exists' "$GUARD"
grep -q 'not release-ready or v0.1-security-ready' "$GUARD"
grep -q 'real release artifact checksums have been verified' "$GUARD"
grep -q 'real release artifact hashes have been compared against `SHA256SUMS`' "$GUARD"
grep -q 'detached signatures have been verified for a release candidate' "$GUARD"
grep -q 'artifact authenticity has been proven' "$GUARD"
grep -q 'candidate evidence has been collected' "$GUARD"
grep -q 'release signing has been approved' "$GUARD"
grep -q 'a release candidate has been approved' "$GUARD"
grep -q 'release hardening gates have passed' "$GUARD"
grep -q 'does not checksum real release artifacts' "$GUARD"
grep -q 'does not verify detached signatures' "$GUARD"
grep -q 'does not prove artifact authenticity' "$GUARD"

printf 'release signing candidate evidence package checksum guard coverage audit remains audit-only\n'
