#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_EVIDENCE_INDEX_CHECKSUM_REQUIREMENTS.md"

test -f "$DOC"

grep -q 'Requirement status: index checksum binding requirements only, not candidate evidence' "$DOC"
grep -q 'candidate_commit' "$DOC"
grep -q 'release_tag' "$DOC"
grep -q 'artifact_manifest' "$DOC"
grep -q 'artifact_manifest_sha256' "$DOC"
grep -q 'classification' "$DOC"
grep -q 'blocker_status' "$DOC"
grep -q 'key ceremony' "$DOC"
grep -q 'signed artifact evidence' "$DOC"
grep -q 'verification UX evidence' "$DOC"
grep -q 'binary verification evidence' "$DOC"
grep -q 'dependency review evidence' "$DOC"
grep -q 'release-candidate signoff evidence' "$DOC"
grep -q 'external review readiness evidence' "$DOC"
grep -q 'update and installer integrity evidence' "$DOC"
grep -q 'missing candidate index' "$DOC"
grep -q 'missing `artifact_manifest`' "$DOC"
grep -q 'missing `artifact_manifest_sha256`' "$DOC"
grep -q 'empty artifact manifest file' "$DOC"
grep -q 'stale `artifact_manifest_sha256`' "$DOC"
grep -q 'mismatched record `candidate_commit`' "$DOC"
grep -q 'mismatched record `release_tag`' "$DOC"
grep -q 'mismatched record `artifact_manifest`' "$DOC"
grep -q 'mismatched record `artifact_manifest_sha256`' "$DOC"
grep -q 'template-only evidence' "$DOC"
grep -q 'placeholder evidence' "$DOC"
grep -q 'empty blocker status' "$DOC"
grep -q 'do not checksum real release artifacts' "$DOC"
grep -q 'do not compare real release artifact hashes against `SHA256SUMS`' "$DOC"
grep -q 'do not verify detached signatures' "$DOC"
grep -q 'do not prove artifact authenticity' "$DOC"
grep -q 'do not collect candidate-specific release evidence' "$DOC"
grep -q 'do not approve release signing' "$DOC"
grep -q 'do not make Another Dimension Chat release-ready or v0.1-security-ready' "$DOC"

printf 'release signing candidate evidence index checksum requirements remain requirements-only\n'
