#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_GUARD_AUDIT.md"
GUARD="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_NON_CLAIM_GUARD.md"

test -f "$DOC"

grep -q 'Audit status: signed-artifact verification guard coverage audit only, not signed artifact verification evidence' "$DOC"
grep -q 'RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_NON_CLAIM_GUARD.md' "$DOC"
grep -q 'fixture signed-artifact verification coverage is not signed artifact verification evidence' "$DOC"
grep -q 'no detached signature verification evidence exists' "$DOC"
grep -q 'no artifact authenticity proof exists' "$DOC"
grep -q 'not release-ready or v0.1-security-ready' "$DOC"
grep -q 'real release artifact hashes have been compared against `SHA256SUMS`' "$DOC"
grep -q 'detached signatures have been verified for a release candidate' "$DOC"
grep -q 'signed artifact verification has passed' "$DOC"
grep -q 'artifact authenticity has been proven' "$DOC"
grep -q 'candidate evidence has been collected' "$DOC"
grep -q 'release signing has been approved' "$DOC"
grep -q 'a release candidate has been approved' "$DOC"
grep -q 'release hardening gates have passed' "$DOC"
grep -q 'does not sign release artifacts' "$DOC"
grep -q 'does not checksum real release artifacts' "$DOC"
grep -q 'does not compare real release artifact hashes against `SHA256SUMS`' "$DOC"
grep -q 'does not verify detached signatures' "$DOC"
grep -q 'does not prove artifact authenticity' "$DOC"
grep -q 'does not collect candidate-specific release evidence' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not signed artifact verification evidence' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not detached signature verification evidence' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not artifact authenticity proof' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not release signing approval' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not release approval' "$DOC"

grep -q 'Guard status: signed-artifact verification non-claim guard only, not signed artifact verification evidence' "$GUARD"
grep -q 'Signed-artifact verification coverage remains fixture-only' "$GUARD"
grep -q 'fixture signed-artifact verification coverage is not signed artifact verification evidence' "$GUARD"
grep -q 'no detached signature verification evidence exists' "$GUARD"
grep -q 'no artifact authenticity proof exists' "$GUARD"
grep -q 'not release-ready or v0.1-security-ready' "$GUARD"
grep -q 'real release artifact hashes have been compared against `SHA256SUMS`' "$GUARD"
grep -q 'detached signatures have been verified for a release candidate' "$GUARD"
grep -q 'signed artifact verification has passed' "$GUARD"
grep -q 'artifact authenticity has been proven' "$GUARD"
grep -q 'candidate evidence has been collected' "$GUARD"
grep -q 'release signing has been approved' "$GUARD"
grep -q 'a release candidate has been approved' "$GUARD"
grep -q 'release hardening gates have passed' "$GUARD"
grep -q 'does not sign release artifacts' "$GUARD"
grep -q 'does not verify detached signatures' "$GUARD"
grep -q 'does not prove artifact authenticity' "$GUARD"

printf 'release signing candidate signed-artifact verification guard coverage audit remains audit-only\n'
