#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MOBILE_DIR="$ROOT_DIR/apps/mobile"

require_file() {
  local path="$1"
  if [[ ! -f "$ROOT_DIR/$path" ]]; then
    echo "missing required mobile skeleton file: $path" >&2
    exit 1
  fi
}

require_text() {
  local path="$1"
  local text="$2"
  if ! grep -F -q "$text" "$ROOT_DIR/$path"; then
    echo "missing required mobile skeleton text in $path: $text" >&2
    exit 1
  fi
}

reject_find() {
  local description="$1"
  shift
  if find "$MOBILE_DIR" "$@" -print -quit | grep -q .; then
    echo "mobile skeleton must not contain $description" >&2
    exit 1
  fi
}

require_file "apps/mobile/README.md"
require_file "apps/mobile/android/README.md"
require_file "apps/mobile/ios/README.md"
require_file "apps/mobile/ffi/README.md"

require_text "apps/mobile/README.md" "documentation-only boundary"
require_text "apps/mobile/README.md" "Mobile clients are not part of the current"
require_text "apps/mobile/README.md" "unsigned experimental public beta"
require_text "apps/mobile/README.md" "sensitive"
require_text "apps/mobile/README.md" "not audited"
require_text "apps/mobile/README.md" "not production-ready"
require_text "apps/mobile/README.md" "external onion delivery not"
require_text "apps/mobile/README.md" "Status Screen Copy Boundary"
require_text "apps/mobile/README.md" "documentation-only candidates"
require_text "apps/mobile/README.md" "Status screens may show status only"
require_text "apps/mobile/README.md" "redacted status only"
require_text "apps/mobile/README.md" "not connected"
require_text "apps/mobile/README.md" "manual action required"
require_text "apps/mobile/README.md" "Status screen labels may project only"
require_text "apps/mobile/README.md" "profile lock state"
require_text "apps/mobile/README.md" "runtime command surface"
require_text "apps/mobile/README.md" "mobile command surface"
require_text "apps/mobile/README.md" "public non-claims"
require_text "apps/mobile/README.md" "must not show send now"
require_text "apps/mobile/README.md" "receive in background"
require_text "apps/mobile/README.md" "push delivery enabled"
require_text "apps/mobile/README.md" "connected to peer"
require_text "apps/mobile/README.md" "onion delivery verified"
require_text "apps/mobile/README.md" "security-ready claims"
require_text "apps/mobile/README.md" "Install/Update Screen Copy Boundary"
require_text "apps/mobile/README.md" "manual update verification required"
require_text "apps/mobile/README.md" "same GitHub Release artifact"
require_text "apps/mobile/README.md" "same release checksum"
require_text "apps/mobile/README.md" "public provenance"
require_text "apps/mobile/README.md" "release manifest"
require_text "apps/mobile/README.md" "release notes"
require_text "apps/mobile/README.md" "dependency evidence"
require_text "apps/mobile/README.md" "store trust not claimed"
require_text "apps/mobile/README.md" "auto-update available"
require_text "apps/mobile/README.md" "automatic update"
require_text "apps/mobile/README.md" "update installed automatically"
require_text "apps/mobile/README.md" "Play Store verified"
require_text "apps/mobile/README.md" "App Store verified"
require_text "apps/mobile/README.md" "TestFlight verified"
require_text "apps/mobile/README.md" "store approved security"
require_text "apps/mobile/README.md" "mobile review security"
require_text "apps/mobile/README.md" "platform signing security"
require_text "apps/mobile/README.md" "notarization security"
require_text "apps/mobile/README.md" "branch checksum accepted"
require_text "apps/mobile/README.md" "source archive checksum accepted"
require_text "apps/mobile/README.md" "copied checksum accepted"
require_text "apps/mobile/README.md" "Backup-Exclusion Screen Copy Boundary"
require_text "apps/mobile/README.md" "backup exclusion status only"
require_text "apps/mobile/README.md" "app-private storage required"
require_text "apps/mobile/README.md" "app-container storage required"
require_text "apps/mobile/README.md" "backup exclusion marker written by wrapper"
require_text "apps/mobile/README.md" "backup exclusion marker verified by wrapper"
require_text "apps/mobile/README.md" "platform verification token present"
require_text "apps/mobile/README.md" "cloud backup not claimed"
require_text "apps/mobile/README.md" "backup recovery not claimed"
require_text "apps/mobile/README.md" "rollback prevention not claimed"
require_text "apps/mobile/README.md" "secure deletion not claimed"
require_text "apps/mobile/README.md" "cloud backup enabled"
require_text "apps/mobile/README.md" "cloud sync enabled"
require_text "apps/mobile/README.md" "backup recovery available"
require_text "apps/mobile/README.md" "rollback prevention guaranteed"
require_text "apps/mobile/README.md" "secure deletion guaranteed"
require_text "apps/mobile/README.md" "shared external storage allowed"
require_text "apps/mobile/README.md" "shared app group storage allowed"
require_text "apps/mobile/README.md" "iCloud backup available"
require_text "apps/mobile/README.md" "Google backup available"
require_text "apps/mobile/README.md" "backup complete"
require_text "apps/mobile/README.md" "data safe after device restore"
require_text "apps/mobile/README.md" "Local Data Lifecycle Screen Copy Boundary"
require_text "apps/mobile/README.md" "local data lifecycle status only"
require_text "apps/mobile/README.md" "conversation delete available"
require_text "apps/mobile/README.md" "conversation delete preserves session"
require_text "apps/mobile/README.md" "session delete available"
require_text "apps/mobile/README.md" "session delete preserves messages"
require_text "apps/mobile/README.md" "profile delete available"
require_text "apps/mobile/README.md" "full local wipe available"
require_text "apps/mobile/README.md" "passphrase-first unlock required"
require_text "apps/mobile/README.md" "encrypted store required"
require_text "apps/mobile/README.md" "backup exclusion best-effort only"
require_text "apps/mobile/README.md" "rollback detection marker only"
require_text "apps/mobile/README.md" "secure deletion not claimed"
require_text "apps/mobile/README.md" "store path shown"
require_text "apps/mobile/README.md" "passphrase retained"
require_text "apps/mobile/README.md" "plaintext exposed"
require_text "apps/mobile/README.md" "key material exposed"
require_text "apps/mobile/README.md" "remote wipe available"
require_text "apps/mobile/README.md" "First-Run Platform Readiness Checklist Boundary"
require_text "apps/mobile/README.md" "first-run checklist status only"
require_text "apps/mobile/README.md" "mobile wrapper is documentation-only"
require_text "apps/mobile/README.md" "platform is Android shell candidate or iOS shell candidate"
require_text "apps/mobile/README.md" "push delivery not claimed"
require_text "apps/mobile/README.md" "mobile app readiness not claimed"
require_text "apps/mobile/README.md" "security-ready not claimed"
require_text "apps/mobile/README.md" "mobile app ready"
require_text "apps/mobile/README.md" "Android app ready"
require_text "apps/mobile/README.md" "iOS app ready"
require_text "apps/mobile/README.md" "store approved"
require_text "apps/mobile/README.md" "background delivery enabled"
require_text "apps/mobile/README.md" "external onion delivery verified"
require_text "apps/mobile/README.md" "safe for sensitive communication"
require_text "apps/mobile/README.md" "Manual Pairing Checklist Screen Copy Boundary"
require_text "apps/mobile/README.md" "manual pairing checklist status only"
require_text "apps/mobile/README.md" "invite code create or join is explicit user action"
require_text "apps/mobile/README.md" "pairing payload export/import is manual"
require_text "apps/mobile/README.md" "safety transcript confirm required"
require_text "apps/mobile/README.md" "pairwise identity only"
require_text "apps/mobile/README.md" "verified pairwise session required before messaging"
require_text "apps/mobile/README.md" "redacted pairing status only"
require_text "apps/mobile/README.md" "no central contact discovery"
require_text "apps/mobile/README.md" "no searchable username"
require_text "apps/mobile/README.md" "no phone number account"
require_text "apps/mobile/README.md" "no email account"
require_text "apps/mobile/README.md" "automatic contact discovery"
require_text "apps/mobile/README.md" "searchable username lookup"
require_text "apps/mobile/README.md" "phone number lookup"
require_text "apps/mobile/README.md" "email lookup"
require_text "apps/mobile/README.md" "global account"
require_text "apps/mobile/README.md" "central account"
require_text "apps/mobile/README.md" "central message server"
require_text "apps/mobile/README.md" "QR scan proves identity"
require_text "apps/mobile/README.md" "pairing automatically verified"
require_text "apps/mobile/README.md" "message delivery verified"
require_text "apps/mobile/README.md" "Invite Verification Checklist Boundary"
require_text "apps/mobile/README.md" "invite verification checklist status only"
require_text "apps/mobile/README.md" "invite code entered by explicit user action"
require_text "apps/mobile/README.md" "invite code create or join is manual"
require_text "apps/mobile/README.md" "pairing payload decodable before verification"
require_text "apps/mobile/README.md" "safety transcript displayed before confirmation"
require_text "apps/mobile/README.md" "pairwise session draft only after safety confirmation"
require_text "apps/mobile/README.md" "message session still requires handshake"
require_text "apps/mobile/README.md" "redacted invite verification status only"
require_text "apps/mobile/README.md" "central contact discovery not claimed"
require_text "apps/mobile/README.md" "account lookup not claimed"
require_text "apps/mobile/README.md" "invite code proves identity"
require_text "apps/mobile/README.md" "invite code discovers contacts"
require_text "apps/mobile/README.md" "invite code searches username"
require_text "apps/mobile/README.md" "invite code looks up phone number"
require_text "apps/mobile/README.md" "invite code looks up email"
require_text "apps/mobile/README.md" "invite accepted automatically"
require_text "apps/mobile/README.md" "safety transcript automatically confirmed"
require_text "apps/mobile/README.md" "session ready after invite"
require_text "apps/mobile/README.md" "Manual Envelope Exchange Checklist Boundary"
require_text "apps/mobile/README.md" "manual envelope exchange checklist status only"
require_text "apps/mobile/README.md" "verified pairwise session required before envelope exchange"
require_text "apps/mobile/README.md" "session runtime material required"
require_text "apps/mobile/README.md" "message number reserved locally"
require_text "apps/mobile/README.md" "encrypted envelope export is explicit user action"
require_text "apps/mobile/README.md" "encrypted envelope import is explicit user action"
require_text "apps/mobile/README.md" "local transcript write after import"
require_text "apps/mobile/README.md" "network I/O not attempted"
require_text "apps/mobile/README.md" "delivery acknowledgement not claimed"
require_text "apps/mobile/README.md" "production messaging not claimed"
require_text "apps/mobile/README.md" "automatic network send"
require_text "apps/mobile/README.md" "automatic network receive"
require_text "apps/mobile/README.md" "message delivered"
require_text "apps/mobile/README.md" "delivery acknowledgement received"
require_text "apps/mobile/README.md" "production messaging ready"
require_text "apps/mobile/README.md" "production E2EE ready"
require_text "apps/mobile/README.md" "plaintext message shown"
require_text "apps/mobile/README.md" "key material exposed"
require_text "apps/mobile/README.md" "Receive/Import Checklist Boundary"
require_text "apps/mobile/README.md" "receive/import checklist status only"
require_text "apps/mobile/README.md" "inbound envelope decoded locally"
require_text "apps/mobile/README.md" "verified pairwise session required before import"
require_text "apps/mobile/README.md" "session transport required before import"
require_text "apps/mobile/README.md" "replay window check required"
require_text "apps/mobile/README.md" "tamper failure does not advance state"
require_text "apps/mobile/README.md" "received transcript write is local"
require_text "apps/mobile/README.md" "plaintext shown only after local decrypt"
require_text "apps/mobile/README.md" "network receive not claimed"
require_text "apps/mobile/README.md" "background receive not claimed"
require_text "apps/mobile/README.md" "push receive enabled"
require_text "apps/mobile/README.md" "message received from network"
require_text "apps/mobile/README.md" "replay prevention guaranteed"
require_text "apps/mobile/README.md" "tamper recovery guaranteed"
require_text "apps/mobile/README.md" "plaintext stored unencrypted"
require_text "apps/mobile/README.md" "Retry/Cancel Checklist Boundary"
require_text "apps/mobile/README.md" "retry/cancel checklist status only"
require_text "apps/mobile/README.md" "retryable failure is local outbound state"
require_text "apps/mobile/README.md" "retry requires explicit user action"
require_text "apps/mobile/README.md" "cancel requires explicit user action"
require_text "apps/mobile/README.md" "retry reuses encrypted envelope export flow"
require_text "apps/mobile/README.md" "cancel terminal is local outbound state"
require_text "apps/mobile/README.md" "cancel does not send network notification"
require_text "apps/mobile/README.md" "pending outbound can be retried or canceled"
require_text "apps/mobile/README.md" "received import state is unchanged by cancel"
require_text "apps/mobile/README.md" "remote acknowledgement not required"
require_text "apps/mobile/README.md" "delivery acknowledgement not claimed"
require_text "apps/mobile/README.md" "network retry not claimed"
require_text "apps/mobile/README.md" "background retry not claimed"
require_text "apps/mobile/README.md" "retry sent automatically"
require_text "apps/mobile/README.md" "cancel notified peer"
require_text "apps/mobile/README.md" "remote cancellation delivered"
require_text "apps/mobile/README.md" "delivery acknowledgement required"
require_text "apps/mobile/README.md" "retry delivery verified"
require_text "apps/mobile/README.md" "background retry enabled"
require_text "apps/mobile/README.md" "push retry enabled"
require_text "apps/mobile/README.md" "message delivered after retry"
require_text "apps/mobile/README.md" "remote ack protocol ready"
require_text "apps/mobile/README.md" "cancel deletes peer copy"
require_text "apps/mobile/README.md" "cancel guarantees remote deletion"
require_text "apps/mobile/README.md" "Transcript Status Checklist Boundary"
require_text "apps/mobile/README.md" "transcript status checklist status only"
require_text "apps/mobile/README.md" "sent direction is local outbound record"
require_text "apps/mobile/README.md" "received direction is local inbound record"
require_text "apps/mobile/README.md" "outbound pending is local state"
require_text "apps/mobile/README.md" "outbound failed is retryable local state"
require_text "apps/mobile/README.md" "outbound sent is local export status only"
require_text "apps/mobile/README.md" "outbound canceled is terminal local state"
require_text "apps/mobile/README.md" "expired message status is local lifecycle state"
require_text "apps/mobile/README.md" "conversation deleted status is local lifecycle state"
require_text "apps/mobile/README.md" "plaintext shown only from local decrypt"
require_text "apps/mobile/README.md" "transcript export is explicit user action"
require_text "apps/mobile/README.md" "network sync not claimed"
require_text "apps/mobile/README.md" "sent means delivered"
require_text "apps/mobile/README.md" "message delivered to peer"
require_text "apps/mobile/README.md" "message read by peer"
require_text "apps/mobile/README.md" "remote transcript synchronized"
require_text "apps/mobile/README.md" "cloud transcript backup"
require_text "apps/mobile/README.md" "transcript proves delivery"
require_text "apps/mobile/README.md" "transcript proves receipt"
require_text "apps/mobile/README.md" "remote deletion verified"
require_text "apps/mobile/README.md" "conversation deleted remotely"
require_text "apps/mobile/README.md" "plaintext synced"
require_text "apps/mobile/README.md" "Conversation Deletion Checklist Boundary"
require_text "apps/mobile/README.md" "conversation deletion checklist status only"
require_text "apps/mobile/README.md" "conversation delete is explicit user action"
require_text "apps/mobile/README.md" "local sent message records removed"
require_text "apps/mobile/README.md" "local received message records removed"
require_text "apps/mobile/README.md" "local message envelopes removed"
require_text "apps/mobile/README.md" "local message indexes removed"
require_text "apps/mobile/README.md" "local message counter removed"
require_text "apps/mobile/README.md" "pairwise session record preserved"
require_text "apps/mobile/README.md" "transcript empty after local delete"
require_text "apps/mobile/README.md" "local lifecycle state only"
require_text "apps/mobile/README.md" "remote deletion not claimed"
require_text "apps/mobile/README.md" "cloud backup recovery not claimed"
require_text "apps/mobile/README.md" "forensic deletion guaranteed"
require_text "apps/mobile/README.md" "peer copy deleted"
require_text "apps/mobile/README.md" "cloud backup deleted"
require_text "apps/mobile/README.md" "Session/Profile/Wipe Checklist Boundary"
require_text "apps/mobile/README.md" "session profile wipe checklist status only"
require_text "apps/mobile/README.md" "session delete is explicit user action"
require_text "apps/mobile/README.md" "session delete removes resume records"
require_text "apps/mobile/README.md" "session delete preserves message records"
require_text "apps/mobile/README.md" "profile delete is explicit user action"
require_text "apps/mobile/README.md" "profile delete removes profile store locks"
require_text "apps/mobile/README.md" "profile delete clears unlock state"
require_text "apps/mobile/README.md" "full local wipe is explicit user action"
require_text "apps/mobile/README.md" "full local wipe removes owned app data"
require_text "apps/mobile/README.md" "backup exclusion remains best-effort only"
require_text "apps/mobile/README.md" "rollback detection remains marker only"
require_text "apps/mobile/README.md" "remote wipe not claimed"
require_text "apps/mobile/README.md" "session delete removes peer messages"
require_text "apps/mobile/README.md" "profile delete removes cloud account"
require_text "apps/mobile/README.md" "full wipe deletes peer copy"
require_text "apps/mobile/README.md" "cloud sync disabled remotely"
require_text "apps/mobile/README.md" "Destructive Action Confirmation Checklist Boundary"
require_text "apps/mobile/README.md" "destructive action confirmation checklist status only"
require_text "apps/mobile/README.md" "confirmation required before conversation delete"
require_text "apps/mobile/README.md" "confirmation required before session delete"
require_text "apps/mobile/README.md" "confirmation required before profile delete"
require_text "apps/mobile/README.md" "confirmation required before full local wipe"
require_text "apps/mobile/README.md" "action scope shown before confirmation"
require_text "apps/mobile/README.md" "local-only impact shown before confirmation"
require_text "apps/mobile/README.md" "pairwise session preservation shown when applicable"
require_text "apps/mobile/README.md" "message preservation shown when applicable"
require_text "apps/mobile/README.md" "owned app data scope shown before full wipe"
require_text "apps/mobile/README.md" "backup exclusion best-effort shown before confirmation"
require_text "apps/mobile/README.md" "cloud recovery not claimed"
require_text "apps/mobile/README.md" "one tap destructive action"
require_text "apps/mobile/README.md" "silent destructive action"
require_text "apps/mobile/README.md" "cloud recovery available"
require_text "apps/mobile/README.md" "Lifecycle Checklist Index Boundary"
require_text "apps/mobile/README.md" "mobile lifecycle checklist index status only"
require_text "apps/mobile/README.md" "checklist coverage index only"
require_text "apps/mobile/README.md" "non-claim index only"
require_text "apps/mobile/README.md" "first-run checklist coverage included"
require_text "apps/mobile/README.md" "local data lifecycle coverage included"
require_text "apps/mobile/README.md" "transcript status coverage included"
require_text "apps/mobile/README.md" "conversation deletion coverage included"
require_text "apps/mobile/README.md" "session profile wipe coverage included"
require_text "apps/mobile/README.md" "destructive confirmation coverage included"
require_text "apps/mobile/README.md" "documentation-only mobile wrapper boundary"
require_text "apps/mobile/README.md" "production messaging not claimed"
require_text "apps/mobile/README.md" "mobile lifecycle ready"
require_text "apps/mobile/README.md" "all lifecycle checks passed"
require_text "apps/mobile/README.md" "no remaining mobile work"
require_text "apps/mobile/README.md" "release ready"
require_text "apps/mobile/README.md" "Pre-Release Non-Claim Audit Boundary"
require_text "apps/mobile/README.md" "mobile pre-release non-claim audit status only"
require_text "apps/mobile/README.md" "public wording audit only"
require_text "apps/mobile/README.md" "documentation-only wrapper state reviewed"
require_text "apps/mobile/README.md" "no buildable mobile app recorded"
require_text "apps/mobile/README.md" "no store distribution recorded"
require_text "apps/mobile/README.md" "no runtime messaging recorded"
require_text "apps/mobile/README.md" "non-claim wording coverage included"
require_text "apps/mobile/README.md" "lifecycle checklist index coverage included"
require_text "apps/mobile/README.md" "unsigned experimental public beta retained"
require_text "apps/mobile/README.md" "sensitive communication prohibited retained"
require_text "apps/mobile/README.md" "not audited retained"
require_text "apps/mobile/README.md" "not production-ready retained"
require_text "apps/mobile/README.md" "central account or contact discovery not claimed"
require_text "apps/mobile/README.md" "pre-release approved"
require_text "apps/mobile/README.md" "release candidate approved"
require_text "apps/mobile/README.md" "security audit passed"
require_text "apps/mobile/README.md" "store review ready"
require_text "apps/mobile/README.md" "all blockers cleared"
require_text "apps/mobile/README.md" "Release-Blocker Inventory Boundary"
require_text "apps/mobile/README.md" "mobile release-blocker inventory status only"
require_text "apps/mobile/README.md" "remaining blocker inventory only"
require_text "apps/mobile/README.md" "documentation-only wrapper blocker recorded"
require_text "apps/mobile/README.md" "buildable mobile app blocker recorded"
require_text "apps/mobile/README.md" "store distribution blocker recorded"
require_text "apps/mobile/README.md" "runtime messaging blocker recorded"
require_text "apps/mobile/README.md" "external onion delivery evidence blocker recorded"
require_text "apps/mobile/README.md" "push notification blocker recorded"
require_text "apps/mobile/README.md" "cloud backup blocker recorded"
require_text "apps/mobile/README.md" "central account and contact discovery blocker recorded"
require_text "apps/mobile/README.md" "independent audit blocker recorded"
require_text "apps/mobile/README.md" "release approval blocker recorded"
require_text "apps/mobile/README.md" "blockers are not cleared"
require_text "apps/mobile/README.md" "release readiness not claimed"
require_text "apps/mobile/README.md" "security readiness not claimed"
require_text "apps/mobile/README.md" "no remaining mobile blockers"
require_text "apps/mobile/README.md" "release blockers resolved"
require_text "apps/mobile/README.md" "mobile release ready"
require_text "apps/mobile/README.md" "store distribution ready"
require_text "apps/mobile/README.md" "runtime messaging ready"
require_text "apps/mobile/README.md" "push notification ready"
require_text "apps/mobile/README.md" "contact discovery ready"
require_text "apps/mobile/README.md" "independent audit complete"
require_text "apps/mobile/README.md" "Blocker-To-Implementation Roadmap Boundary"
require_text "apps/mobile/README.md" "mobile blocker-to-implementation roadmap status only"
require_text "apps/mobile/README.md" "implementation phase mapping only"
require_text "apps/mobile/README.md" "documentation-only wrapper phase recorded"
require_text "apps/mobile/README.md" "buildable mobile app implementation phase recorded"
require_text "apps/mobile/README.md" "store distribution decision phase recorded"
require_text "apps/mobile/README.md" "runtime messaging implementation phase recorded"
require_text "apps/mobile/README.md" "external onion delivery evidence phase recorded"
require_text "apps/mobile/README.md" "push notification exclusion phase recorded"
require_text "apps/mobile/README.md" "cloud backup exclusion phase recorded"
require_text "apps/mobile/README.md" "central account and contact discovery exclusion phase recorded"
require_text "apps/mobile/README.md" "independent audit evidence phase recorded"
require_text "apps/mobile/README.md" "release approval evidence phase recorded"
require_text "apps/mobile/README.md" "roadmap does not clear blockers"
require_text "apps/mobile/README.md" "roadmap does not implement mobile app"
require_text "apps/mobile/README.md" "roadmap does not claim release readiness"
require_text "apps/mobile/README.md" "roadmap does not claim security readiness"
require_text "apps/mobile/README.md" "roadmap blockers resolved"
require_text "apps/mobile/README.md" "implementation complete"
require_text "apps/mobile/README.md" "mobile app implemented"
require_text "apps/mobile/README.md" "store distribution decided"
require_text "apps/mobile/README.md" "runtime messaging implemented"
require_text "apps/mobile/README.md" "external onion delivery evidence recorded"
require_text "apps/mobile/README.md" "release approval recorded"
require_text "apps/mobile/README.md" "all roadmap items complete"
require_text "apps/mobile/README.md" "Mobile Wrapper Implementation Entry Criteria Boundary"
require_text "apps/mobile/README.md" "mobile wrapper implementation entry criteria status only"
require_text "apps/mobile/README.md" "entry criteria list only"
require_text "apps/mobile/README.md" "target platform decision criteria recorded"
require_text "apps/mobile/README.md" "shared core FFI boundary criteria recorded"
require_text "apps/mobile/README.md" "status DTO and redaction criteria recorded"
require_text "apps/mobile/README.md" "local data lifecycle criteria recorded"
require_text "apps/mobile/README.md" "explicit user action criteria recorded"
require_text "apps/mobile/README.md" "no central account criteria recorded"
require_text "apps/mobile/README.md" "no push notification dependency criteria recorded"
require_text "apps/mobile/README.md" "no cloud backup criteria recorded"
require_text "apps/mobile/README.md" "platform build scaffold criteria recorded"
require_text "apps/mobile/README.md" "wrapper test plan criteria recorded"
require_text "apps/mobile/README.md" "public non-claim copy criteria recorded"
require_text "apps/mobile/README.md" "criteria are not satisfied"
require_text "apps/mobile/README.md" "implementation has not started"
require_text "apps/mobile/README.md" "entry criteria satisfied"
require_text "apps/mobile/README.md" "implementation can start"
require_text "apps/mobile/README.md" "mobile implementation started"
require_text "apps/mobile/README.md" "Android implementation ready"
require_text "apps/mobile/README.md" "iOS implementation ready"
require_text "apps/mobile/README.md" "FFI boundary stable"
require_text "apps/mobile/README.md" "runtime messaging available"
require_text "apps/mobile/README.md" "all entry criteria met"
require_text "apps/mobile/README.md" "Mobile Wrapper Implementation Authorization Boundary"
require_text "apps/mobile/README.md" "mobile wrapper implementation authorization status only"
require_text "apps/mobile/README.md" "authorization record only"
require_text "apps/mobile/README.md" "authorization checklist only"
require_text "apps/mobile/README.md" "entry criteria reviewed but not satisfied"
require_text "apps/mobile/README.md" "explicit owner authorization required"
require_text "apps/mobile/README.md" "implementation authorization not granted"
require_text "apps/mobile/README.md" "mobile implementation has not started"
require_text "apps/mobile/README.md" "security review authorization not granted"
require_text "apps/mobile/README.md" "release review authorization not granted"
require_text "apps/mobile/README.md" "store distribution authorization not granted"
require_text "apps/mobile/README.md" "runtime messaging authorization not granted"
require_text "apps/mobile/README.md" "external delivery evidence authorization not granted"
require_text "apps/mobile/README.md" "push notification dependency remains excluded"
require_text "apps/mobile/README.md" "cloud backup remains excluded"
require_text "apps/mobile/README.md" "central account remains excluded"
require_text "apps/mobile/README.md" "mobile readiness not claimed"
require_text "apps/mobile/README.md" "authorization does not claim release readiness"
require_text "apps/mobile/README.md" "authorization does not claim security readiness"
require_text "apps/mobile/README.md" "runtime messaging availability not claimed"
require_text "apps/mobile/README.md" "store readiness not claimed"
require_text "apps/mobile/README.md" "external delivery evidence not claimed"
require_text "apps/mobile/README.md" "implementation authorized"
require_text "apps/mobile/README.md" "implementation authorization granted"
require_text "apps/mobile/README.md" "owner approved implementation"
require_text "apps/mobile/README.md" "security review approved"
require_text "apps/mobile/README.md" "release review approved"
require_text "apps/mobile/README.md" "runtime messaging authorized"
require_text "apps/mobile/README.md" "external delivery evidence accepted"
require_text "apps/mobile/README.md" "push notification authorized"
require_text "apps/mobile/README.md" "cloud backup authorized"
require_text "apps/mobile/README.md" "central account authorized"
require_text "apps/mobile/README.md" "Mobile Wrapper Implementation Kickoff Blocker Boundary"
require_text "apps/mobile/README.md" "mobile wrapper implementation kickoff blocker status only"
require_text "apps/mobile/README.md" "kickoff blocker record only"
require_text "apps/mobile/README.md" "authorization not granted blocker recorded"
require_text "apps/mobile/README.md" "entry criteria not satisfied blocker recorded"
require_text "apps/mobile/README.md" "implementation kickoff blocked"
require_text "apps/mobile/README.md" "no implementation task opened"
require_text "apps/mobile/README.md" "no mobile source scaffold created"
require_text "apps/mobile/README.md" "no Android build scaffold created"
require_text "apps/mobile/README.md" "no iOS build scaffold created"
require_text "apps/mobile/README.md" "no runtime messaging scaffold created"
require_text "apps/mobile/README.md" "no store distribution task opened"
require_text "apps/mobile/README.md" "no external delivery evidence task opened"
require_text "apps/mobile/README.md" "kickoff blocker does not claim mobile readiness"
require_text "apps/mobile/README.md" "kickoff blocker does not claim release readiness"
require_text "apps/mobile/README.md" "kickoff blocker does not claim security readiness"
require_text "apps/mobile/README.md" "implementation kickoff allowed"
require_text "apps/mobile/README.md" "implementation kickoff unblocked"
require_text "apps/mobile/README.md" "implementation task opened"
require_text "apps/mobile/README.md" "mobile source scaffold created"
require_text "apps/mobile/README.md" "Android build scaffold created"
require_text "apps/mobile/README.md" "iOS build scaffold created"
require_text "apps/mobile/README.md" "runtime messaging scaffold created"
require_text "apps/mobile/README.md" "store distribution task opened"
require_text "apps/mobile/README.md" "external delivery evidence task opened"

require_text "apps/mobile/android/README.md" "documentation-only boundary"
require_text "apps/mobile/android/README.md" "not a mobile wrapper source scaffold"
require_text "apps/mobile/android/README.md" "not a Gradle project"
require_text "apps/mobile/android/README.md" "not an APK or AAB artifact"
require_text "apps/mobile/android/README.md" "not Android app readiness"
require_text "apps/mobile/android/README.md" "thin Kotlin shell over UniFFI or another"
require_text "apps/mobile/android/README.md" "must not define independent protocol, storage, transport"

require_text "apps/mobile/ios/README.md" "documentation-only boundary"
require_text "apps/mobile/ios/README.md" "not a mobile wrapper source scaffold"
require_text "apps/mobile/ios/README.md" "not an Xcode project"
require_text "apps/mobile/ios/README.md" "not an IPA artifact"
require_text "apps/mobile/ios/README.md" "not TestFlight distribution"
require_text "apps/mobile/ios/README.md" "not iOS app readiness"
require_text "apps/mobile/ios/README.md" "thin Swift shell over UniFFI or another"
require_text "apps/mobile/ios/README.md" "must not define independent protocol, storage, transport"

require_text "apps/mobile/ffi/README.md" "documentation-only naming and API inventory"
require_text "apps/mobile/ffi/README.md" "not a UniFFI definition"
require_text "apps/mobile/ffi/README.md" "not generated bindings"
require_text "apps/mobile/ffi/README.md" "not Kotlin or Swift"
require_text "apps/mobile/ffi/README.md" "runtime source"
require_text "apps/mobile/ffi/README.md" "Allowed API groups mirror the shared core wrapper boundary"
require_text "apps/mobile/ffi/README.md" "shared_core_status_surface"
require_text "apps/mobile/ffi/README.md" "redacted_support_diagnostics"
require_text "apps/mobile/ffi/README.md" "must not export raw storage open calls"
require_text "apps/mobile/ffi/README.md" "security-ready claims"
require_text "apps/mobile/ffi/README.md" "Signature Placeholder Boundary"
require_text "apps/mobile/ffi/README.md" "documentation-only until a"
require_text "apps/mobile/ffi/README.md" "narrow handle-and-bytes shape"
require_text "apps/mobile/ffi/README.md" "opaque"
require_text "apps/mobile/ffi/README.md" "ProfileHandle"
require_text "apps/mobile/ffi/README.md" "canonical byte buffers"
require_text "apps/mobile/ffi/README.md" "redacted structured result objects"
require_text "apps/mobile/ffi/README.md" "explicit error codes"
require_text "apps/mobile/ffi/README.md" "caller-owned input buffers"
require_text "apps/mobile/ffi/README.md" "core-owned returned buffers"
require_text "apps/mobile/ffi/README.md" "explicit release"
require_text "apps/mobile/ffi/README.md" "explicit user action tokens"
require_text "apps/mobile/ffi/README.md" "does not define a"
require_text "apps/mobile/ffi/README.md" "callable mobile FFI"
require_text "apps/mobile/ffi/README.md" "stable ABI"
require_text "apps/mobile/ffi/README.md" "memory ownership contract"
require_text "apps/mobile/ffi/README.md" "serialization"
require_text "apps/mobile/ffi/README.md" "binding generation"
require_text "apps/mobile/ffi/README.md" "mobile app readiness"
require_text "apps/mobile/ffi/README.md" "Status Command DTO Boundary"
require_text "apps/mobile/ffi/README.md" "documentation-only redacted"
require_text "apps/mobile/ffi/README.md" "not a callable command surface"
require_text "apps/mobile/ffi/README.md" "schema version"
require_text "apps/mobile/ffi/README.md" "profile lock"
require_text "apps/mobile/ffi/README.md" "runtime command surface"
require_text "apps/mobile/ffi/README.md" "mobile command surface"
require_text "apps/mobile/ffi/README.md" "public non-claims"
require_text "apps/mobile/ffi/README.md" "profile paths"
require_text "apps/mobile/ffi/README.md" "database paths"
require_text "apps/mobile/ffi/README.md" "network endpoints"
require_text "apps/mobile/ffi/README.md" "delivery runtime handles"
require_text "apps/mobile/ffi/README.md" "push tokens"
require_text "apps/mobile/ffi/README.md" "central account identifiers"
require_text "apps/mobile/ffi/README.md" "security-ready toggles"
require_text "apps/mobile/ffi/README.md" "DTO Serialization Placeholder Boundary"
require_text "apps/mobile/ffi/README.md" "documentation-only until a"
require_text "apps/mobile/ffi/README.md" "deterministic UTF-8 JSON object"
require_text "apps/mobile/ffi/README.md" "explicit schema version"
require_text "apps/mobile/ffi/README.md" "sorted keys"
require_text "apps/mobile/ffi/README.md" "string enums"
require_text "apps/mobile/ffi/README.md" "bounded arrays of status labels"
require_text "apps/mobile/ffi/README.md" "reject-unknown-fields"
require_text "apps/mobile/ffi/README.md" "does not define a serializer"
require_text "apps/mobile/ffi/README.md" "stable wire format"
require_text "apps/mobile/ffi/README.md" "cross-version migration"
require_text "apps/mobile/ffi/README.md" "raw logs"
require_text "apps/mobile/ffi/README.md" "support bundles"
require_text "apps/mobile/ffi/README.md" "crash dumps"
require_text "apps/mobile/ffi/README.md" "Redacted Diagnostics Payload Placeholder Boundary"
require_text "apps/mobile/ffi/README.md" "local-copy-only"
require_text "apps/mobile/ffi/README.md" "Allowed diagnostics payload fields"
require_text "apps/mobile/ffi/README.md" "failure class"
require_text "apps/mobile/ffi/README.md" "manual network permission"
require_text "apps/mobile/ffi/README.md" "app launch network boundary"
require_text "apps/mobile/ffi/README.md" "redacted runtime flags"
require_text "apps/mobile/ffi/README.md" "diagnostics redaction state"
require_text "apps/mobile/ffi/README.md" "Allowed diagnostics channels"
require_text "apps/mobile/ffi/README.md" "in-app redacted text view"
require_text "apps/mobile/ffi/README.md" "explicit user-initiated copy"
require_text "apps/mobile/ffi/README.md" "minimal private security contact request"
require_text "apps/mobile/ffi/README.md" "bridge lines"
require_text "apps/mobile/ffi/README.md" "pairing payloads"
require_text "apps/mobile/ffi/README.md" "envelope payloads"
require_text "apps/mobile/ffi/README.md" "Android logcat"
require_text "apps/mobile/ffi/README.md" "iOS"
require_text "apps/mobile/ffi/README.md" "sysdiagnose"
require_text "apps/mobile/ffi/README.md" "share-sheet private data prefill"

reject_find "Android build project files" \
  \( -name build.gradle -o -name settings.gradle -o -name AndroidManifest.xml \)
reject_find "iOS build project files" \
  \( -name Package.swift -o -name Info.plist -o -name '*.xcodeproj' -o -name '*.xcworkspace' \)
reject_find "mobile runtime or generated binding source" \
  \( -name '*.kt' -o -name '*.swift' -o -name '*.udl' \)
reject_find "mobile app artifacts" \
  \( -name '*.apk' -o -name '*.aab' -o -name '*.ipa' \)
reject_find "mobile build output directories" \
  \( -type d -name build -o -type d -name DerivedData \)

printf 'status=mobile-shared-core-boundary-verified\n'
printf 'mobile_source_scaffold_created=false\n'
printf 'android_build_scaffold_created=false\n'
printf 'ios_build_scaffold_created=false\n'
printf 'runtime_app_implementation_created=false\n'
printf 'mobile_readiness_claim=false\n'
