#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_MANIFEST_CONSISTENCY_AUDIT.md"
FIXTURE="$ROOT_DIR/scripts/verify_release_signing_candidate_manifest_consistency_fixture.sh"

grep -q 'Audit status: manifest consistency coverage audit only, not candidate evidence' "$DOC"
grep -q 'ARTIFACT_MANIFEST' "$DOC"
grep -q 'CANDIDATE_EVIDENCE_INDEX' "$DOC"
grep -q 'candidate_commit' "$DOC"
grep -q 'release_tag' "$DOC"
grep -q 'artifact_manifest_sha256' "$DOC"
grep -q 'fixture-filled-not-release-evidence' "$DOC"
grep -q 'missing artifact manifest' "$DOC"
grep -q 'empty artifact manifest' "$DOC"
grep -q 'stale index manifest digest' "$DOC"
grep -q 'mismatched record candidate commit' "$DOC"
grep -q 'mismatched record release tag' "$DOC"
grep -q 'mismatched record manifest digest' "$DOC"
grep -q 'template-only evidence' "$DOC"
grep -q 'placeholder evidence' "$DOC"
grep -q 'does not inspect real release artifacts' "$DOC"
grep -q 'does not verify real signed artifacts' "$DOC"
grep -q 'does not create or approve candidate evidence' "$DOC"
grep -q 'does not verify artifact authenticity' "$DOC"
grep -q 'does not approve release signing' "$DOC"
grep -q 'does not approve a release candidate or release' "$DOC"
grep -q 'Fixture manifest consistency coverage is not candidate evidence' "$DOC"
grep -q 'Fixture manifest consistency coverage is not signed artifact verification' "$DOC"
grep -q 'Fixture manifest consistency coverage is not release approval' "$DOC"

grep -q 'ARTIFACT_MANIFEST' "$FIXTURE"
grep -q 'CANDIDATE_EVIDENCE_INDEX' "$FIXTURE"
grep -q 'candidate_commit' "$FIXTURE"
grep -q 'release_tag' "$FIXTURE"
grep -q 'artifact_manifest_sha256' "$FIXTURE"
grep -q 'fixture-filled-not-release-evidence' "$FIXTURE"
grep -q 'expect_rejects "missing artifact manifest"' "$FIXTURE"
grep -q 'expect_rejects "empty artifact manifest"' "$FIXTURE"
grep -q 'expect_rejects "stale index manifest digest"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record candidate commit"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record release tag"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record manifest digest"' "$FIXTURE"
grep -q 'expect_rejects "template-only evidence"' "$FIXTURE"
grep -q 'expect_rejects "placeholder evidence"' "$FIXTURE"

printf 'release signing candidate manifest consistency audit confirms fixture coverage and limits\n'
