#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_EVIDENCE_INDEX_CHECKSUM_FIXTURE_AUDIT.md"
FIXTURE="$ROOT_DIR/scripts/verify_release_signing_candidate_evidence_index_checksum_fixture.sh"

grep -q 'Audit status: index checksum fixture coverage audit only, not candidate evidence' "$DOC"
grep -q 'CANDIDATE_EVIDENCE_INDEX' "$DOC"
grep -q 'ARTIFACT_MANIFEST' "$DOC"
grep -q 'candidate_commit' "$DOC"
grep -q 'release_tag' "$DOC"
grep -q 'artifact_manifest' "$DOC"
grep -q 'artifact_manifest_sha256' "$DOC"
grep -q 'classification' "$DOC"
grep -q 'blocker_status' "$DOC"
grep -q 'artifact_manifest_sha256` matches the disposable `ARTIFACT_MANIFEST' "$DOC"
grep -q 'Every required record path is listed exactly once' "$DOC"
grep -q 'fixture-filled-not-release-evidence' "$DOC"
grep -q 'missing candidate index' "$DOC"
grep -q 'missing artifact manifest' "$DOC"
grep -q 'missing artifact manifest digest' "$DOC"
grep -q 'empty artifact manifest' "$DOC"
grep -q 'stale artifact manifest digest' "$DOC"
grep -q 'mismatched record candidate commit' "$DOC"
grep -q 'mismatched record release tag' "$DOC"
grep -q 'mismatched record artifact manifest' "$DOC"
grep -q 'mismatched record artifact manifest digest' "$DOC"
grep -q 'template-only evidence' "$DOC"
grep -q 'placeholder evidence' "$DOC"
grep -q 'empty blocker status' "$DOC"
grep -q 'does not checksum real release artifacts' "$DOC"
grep -q 'does not compare real release artifact hashes against `SHA256SUMS`' "$DOC"
grep -q 'does not verify detached signatures' "$DOC"
grep -q 'does not prove artifact authenticity' "$DOC"
grep -q 'does not collect candidate-specific release evidence' "$DOC"
grep -q 'does not approve release signing' "$DOC"
grep -q 'does not approve a release candidate or release' "$DOC"
grep -q 'does not make Another Dimension Chat release-ready or v0.1-security-ready' "$DOC"
grep -q 'Index checksum fixture coverage is not candidate evidence' "$DOC"
grep -q 'Index checksum fixture coverage is not signed artifact verification' "$DOC"
grep -q 'Index checksum fixture coverage is not release approval' "$DOC"

grep -q 'CANDIDATE_EVIDENCE_INDEX' "$FIXTURE"
grep -q 'ARTIFACT_MANIFEST' "$FIXTURE"
grep -q 'candidate_commit' "$FIXTURE"
grep -q 'release_tag' "$FIXTURE"
grep -q 'artifact_manifest' "$FIXTURE"
grep -q 'artifact_manifest_sha256' "$FIXTURE"
grep -q 'classification' "$FIXTURE"
grep -q 'blocker_status' "$FIXTURE"
grep -q 'verify_record_list' "$FIXTURE"
grep -q 'fixture-filled-not-release-evidence' "$FIXTURE"
grep -q 'expect_rejects "missing candidate index"' "$FIXTURE"
grep -q 'expect_rejects "missing artifact manifest"' "$FIXTURE"
grep -q 'expect_rejects "missing artifact manifest digest"' "$FIXTURE"
grep -q 'expect_rejects "empty artifact manifest"' "$FIXTURE"
grep -q 'expect_rejects "stale artifact manifest digest"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record candidate commit"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record release tag"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record artifact manifest"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record artifact manifest digest"' "$FIXTURE"
grep -q 'expect_rejects "template-only evidence"' "$FIXTURE"
grep -q 'expect_rejects "placeholder evidence"' "$FIXTURE"
grep -q 'expect_rejects "empty blocker status"' "$FIXTURE"

printf 'release signing candidate evidence index checksum fixture audit confirms fixture coverage and limits\n'
