#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$ROOT_DIR/apps/desktop-tauri"
TAURI_DIR="$APP_DIR/src-tauri"

require_contains() {
  local file="$1"
  local pattern="$2"

  if ! grep -q -- "$pattern" "$file"; then
    echo "missing expected Tauri scaffold pattern in $file: $pattern" >&2
    exit 1
  fi
}

require_not_contains() {
  local file="$1"
  local pattern="$2"

  if grep -q -- "$pattern" "$file"; then
    echo "unexpected Tauri scaffold pattern in $file: $pattern" >&2
    exit 1
  fi
}

require_status_field() {
  local field="$1"
  local value="$2"

  require_contains "$TAURI_DIR/src/status.rs" "$field: \"$value\""
  require_contains "$APP_DIR/src/main.js" "status.$field"
}

require_status_copy() {
  local value="$1"

  require_contains "$APP_DIR/index.html" "$value"
}

required_files=(
  "$APP_DIR/README.md"
  "$APP_DIR/.npmrc"
  "$APP_DIR/package.json"
  "$APP_DIR/package-lock.json"
  "$TAURI_DIR/Cargo.lock"
  "$APP_DIR/index.html"
  "$APP_DIR/src/action-state.js"
  "$APP_DIR/src/action-state.test.js"
  "$APP_DIR/src/i18n.js"
  "$APP_DIR/src/i18n.test.js"
  "$APP_DIR/src/main.js"
  "$APP_DIR/src/ui-smoke.test.js"
  "$APP_DIR/scripts/noop-dev-server.mjs"
  "$APP_DIR/scripts/run-local-peer.mjs"
  "$APP_DIR/scripts/verify-local-peer-flow.mjs"
  "$APP_DIR/scripts/verify-ui-loop-scripts.mjs"
  "$APP_DIR/src/transcript-export.js"
  "$APP_DIR/src/transcript-retention.js"
  "$APP_DIR/src/styles.css"
  "$APP_DIR/vite.config.js"
  "$ROOT_DIR/scripts/repo_size_guard_once.sh"
  "$ROOT_DIR/scripts/smoke_tauri_two_profile.sh"
  "$TAURI_DIR/Cargo.toml"
  "$TAURI_DIR/build.rs"
  "$TAURI_DIR/src/lib.rs"
  "$TAURI_DIR/src/main.rs"
  "$TAURI_DIR/src/status.rs"
  "$TAURI_DIR/icons/icon.png"
  "$TAURI_DIR/tauri.conf.json"
)

for file in "${required_files[@]}"; do
  test -f "$file"
done

require_contains "$TAURI_DIR/tauri.conf.json" '"frontendDist": "../dist"'
require_contains "$TAURI_DIR/tauri.conf.json" '"devUrl": "http://localhost:1420"'
require_contains "$TAURI_DIR/tauri.conf.json" '"active": true'
require_contains "$TAURI_DIR/tauri.conf.json" '"resources": \[\]'
require_contains "$APP_DIR/package.json" '"tauri:build"'
require_contains "$APP_DIR/package.json" '"tauri:build:full"'
require_contains "$APP_DIR/package.json" '"legacy:tauri:build:embedded-runtime"'
require_contains "$APP_DIR/package.json" '"tauri:dev"'
require_contains "$TAURI_DIR/Cargo.toml" 'default = \["public-shell"\]'
require_contains "$TAURI_DIR/Cargo.toml" 'legacy-embedded-runtime = \['
require_contains "$APP_DIR/package.json" '"tauri:build:windows-nsis:shell": "npm run engine:prepare-sidecar:release:manual && node scripts/with-cargo-target.mjs tauri build --config src-tauri/tauri.sidecar.conf.json --features public-shell --bundles nsis -- --no-default-features"'
require_contains "$APP_DIR/package.json" '"tauri:dev:beta-onion"'
require_contains "$APP_DIR/package.json" '"tauri:build:beta-onion"'
require_contains "$APP_DIR/package.json" '"tauri:dev:peer-a"'
require_contains "$APP_DIR/package.json" '"tauri:dev:peer-b"'
require_contains "$APP_DIR/package.json" '"test:ui-fast"'
require_contains "$APP_DIR/package.json" '"test:native-shell"'
require_contains "$APP_DIR/package.json" '"verify:ui-loop-scripts"'
require_contains "$APP_DIR/package.json" '"test:local-peers"'
require_contains "$APP_DIR/scripts/verify-ui-loop-scripts.mjs" 'uiOnlyScripts'
require_contains "$APP_DIR/scripts/verify-ui-loop-scripts.mjs" 'ui-only-script-calls-native'
require_contains "$APP_DIR/package.json" 'engine:prepare-sidecar:release:manual'
require_contains "$APP_DIR/package.json" 'legacy:tauri:dev:manual-onion'
require_contains "$APP_DIR/scripts/run-local-peer.mjs" 'another-dimension-dev-${peer}'
require_contains "$APP_DIR/scripts/run-local-peer.mjs" 'ANOTHER_DIMENSION_APP_DATA_DIR'
require_contains "$APP_DIR/scripts/run-local-peer.mjs" 'ANOTHER_DIMENSION_APP_CACHE_DIR'
require_contains "$APP_DIR/scripts/verify-local-peer-flow.mjs" 'production_isolated_invite_roots_exchange_payloads_without_peer_private_profile'
require_contains "$APP_DIR/scripts/verify-local-peer-flow.mjs" 'production_two_profile_room_setup_accepts_invite_derived_profiles'
require_contains "$APP_DIR/scripts/noop-dev-server.mjs" 'process.exit(0)'
require_contains "$APP_DIR/README.md" 'Build a local-only lightweight desktop public shell'
require_contains "$APP_DIR/README.md" 'npm run tauri:dev:beta-onion'
require_contains "$APP_DIR/README.md" 'npm run tauri:dev'
require_contains "$APP_DIR/README.md" 'sidecar-first public-shell builds'
require_contains "$APP_DIR/README.md" 'legacy:tauri:*'
require_contains "$APP_DIR/README.md" 'app.path().app_data_dir()'
require_contains "$APP_DIR/README.md" '<app-data>/profiles/<profile>/'
require_contains "$APP_DIR/README.md" 'no destructive migration step'
require_contains "$APP_DIR/README.md" 'No Tor bootstrap, onion hosting, descriptor publication, stream I/O, or envelope I/O starts on app launch'
require_contains "$APP_DIR/index.html" 'Local details'
require_contains "$APP_DIR/index.html" 'Transfer details'
require_contains "$TAURI_DIR/src/lib.rs" 'prototype_status'
require_contains "$TAURI_DIR/src/lib.rs" 'dev_local_demo'
require_contains "$TAURI_DIR/src/lib.rs" 'dev_local_message_loop'
require_contains "$TAURI_DIR/src/lib.rs" 'DevLocalMessageLoopResult'
require_contains "$TAURI_DIR/src/lib.rs" 'parse_loop_messages'
require_contains "$TAURI_DIR/src/lib.rs" 'sanitize_loop_messages'
require_contains "$TAURI_DIR/src/lib.rs" 'steps: Vec<DevLocalDemoStep>'
require_contains "$TAURI_DIR/src/lib.rs" 'simulation: DevLocalSimulation'
require_contains "$TAURI_DIR/src/lib.rs" 'build_demo_simulation'
require_contains "$TAURI_DIR/src/lib.rs" 'DevLocalPeer'
require_contains "$TAURI_DIR/src/lib.rs" 'safety_number'
require_contains "$TAURI_DIR/src/lib.rs" 'message_body'
require_contains "$TAURI_DIR/src/lib.rs" 'first_run_hint'
require_contains "$TAURI_DIR/src/lib.rs" 'parse_demo_steps'
require_contains "$TAURI_DIR/src/lib.rs" 'status: "completed"'
require_contains "$TAURI_DIR/src/lib.rs" 'mod status;'
require_contains "$TAURI_DIR/src/lib.rs" 'pub use status::PrototypeStatus;'
require_contains "$TAURI_DIR/src/lib.rs" 'redacted_prototype_status()'
require_contains "$TAURI_DIR/src/lib.rs" 'dev_local_message_loop'
require_contains "$TAURI_DIR/src/lib.rs" 'production_message_retention_policy'
require_contains "$TAURI_DIR/src/lib.rs" 'production_profile_unlock'
require_contains "$TAURI_DIR/src/lib.rs" 'production_profile_list'
require_contains "$TAURI_DIR/src/lib.rs" 'production_message_retention_preference_get'
require_contains "$TAURI_DIR/src/lib.rs" 'production_message_retention_preference_set'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_profile_unlock'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_profile_list'
require_contains "$TAURI_DIR/src/lib.rs" 'app_data_dir()'
require_contains "$TAURI_DIR/src/lib.rs" 'production_pairing_payload_export'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_pairing_payload_export'
require_contains "$TAURI_DIR/src/lib.rs" 'production_pairing_safety_preview'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_pairing_safety_preview'
require_contains "$TAURI_DIR/src/lib.rs" 'production_pairing_session_draft_save'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_pairing_session_draft_save'
require_contains "$TAURI_DIR/src/lib.rs" 'production_session_state_check'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_session_state_check'
require_contains "$TAURI_DIR/src/lib.rs" 'production_handshake_init_export'
require_contains "$TAURI_DIR/src/lib.rs" 'production_handshake_reply_export'
require_contains "$TAURI_DIR/src/lib.rs" 'production_handshake_finish_export'
require_contains "$TAURI_DIR/src/lib.rs" 'production_handshake_finish_import'
require_contains "$TAURI_DIR/src/lib.rs" 'production_message_envelope_export'
require_contains "$TAURI_DIR/src/lib.rs" 'production_message_envelope_import'
require_contains "$TAURI_DIR/src/lib.rs" 'production_message_outbound_mark_send_failed'
require_contains "$TAURI_DIR/src/lib.rs" 'production_onion_inbound_envelope_receive_attempt'
require_contains "$TAURI_DIR/src/lib.rs" 'received_message_record_decodable'
require_contains "$TAURI_DIR/src/lib.rs" 'received_message_matches_session'
require_contains "$TAURI_DIR/src/lib.rs" 'production_onion_descriptor_publication_attempt'
require_contains "$TAURI_DIR/src/lib.rs" 'production_onion_outbound_envelope_send_attempt'
require_contains "$TAURI_DIR/src/lib.rs" 'production_onion_outbound_envelope_send_stored_endpoint_attempt'
require_contains "$TAURI_DIR/src/lib.rs" 'production_onion_outbound_envelope_send_prepare'
require_contains "$TAURI_DIR/src/lib.rs" 'production_onion_service_launch_attempt'
require_contains "$TAURI_DIR/src/lib.rs" 'production_message_received_export'
require_contains "$TAURI_DIR/src/lib.rs" 'production_message_transcript_export'
require_contains "$TAURI_DIR/src/lib.rs" 'ProductionMessageTranscriptEntryResult'
require_contains "$TAURI_DIR/src/lib.rs" 'transcript_tsv'
require_contains "$TAURI_DIR/src/lib.rs" 'created_at_ms'
require_contains "$TAURI_DIR/src/lib.rs" 'ttl_seconds'
require_contains "$TAURI_DIR/src/lib.rs" 'expires_at_ms'
require_contains "$TAURI_DIR/src/lib.rs" 'expired'
require_contains "$TAURI_DIR/src/lib.rs" 'expired_messages_purged'
require_contains "$TAURI_DIR/src/lib.rs" 'production_local_roundtrip'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_local_roundtrip'
require_contains "$TAURI_DIR/src/lib.rs" 'cargo'
require_contains "$TAURI_DIR/src/lib.rs" 'demo'
require_contains "$TAURI_DIR/src/lib.rs" 'local'
require_contains "$TAURI_DIR/src/lib.rs" 'local-loop'
require_contains "$TAURI_DIR/src/status.rs" 'pub fn redacted_prototype_status() -> PrototypeStatus'
require_contains "$TAURI_DIR/src/status.rs" 'secure_release: false'
require_contains "$TAURI_DIR/src/status.rs" 'usable_messaging: false'
require_status_field 'core_status' 'core boundary only'
require_status_field 'profile_status' 'profile boundary only'
require_status_field 'pairing_status' 'pairing boundary only'
require_status_field 'production_session_status' 'snow Noise XX synchronous evaluation boundary only'
require_status_field 'production_self_test_status' 'CLI production boundary self-test only'
require_contains "$TAURI_DIR/src/status.rs" 'production_session_non_readiness:'
require_contains "$TAURI_DIR/src/status.rs" 'no audited production E2EE claim network transport automatic messaging or secure release'
require_contains "$APP_DIR/src/main.js" 'status.production_session_non_readiness'
require_contains "$TAURI_DIR/src/status.rs" 'production_skeleton_preflight_summary'
require_contains "$TAURI_DIR/src/status.rs" 'production_skeleton_next_connector_selection'
require_contains "$TAURI_DIR/src/status.rs" 'production_preflight_status: format!'
require_contains "$TAURI_DIR/src/status.rs" 'production_preflight_blockers:'
require_contains "$TAURI_DIR/src/status.rs" 'preflight.session_e2ee_ready()'
require_contains "$TAURI_DIR/src/status.rs" 'preflight.transport_send_receive_available()'
require_contains "$TAURI_DIR/src/status.rs" 'preflight.storage_rollback_protection()'
require_contains "$APP_DIR/src/main.js" 'status.production_preflight_blockers'
require_contains "$TAURI_DIR/src/status.rs" 'session_durable_state_status:'
require_contains "$TAURI_DIR/src/status.rs" 'local encrypted session lifecycle controls available; no audited readiness claim'
require_contains "$APP_DIR/src/main.js" 'status.session_durable_state_status'
require_status_field 'session_unlock_policy_status' 'passphrase-first high-risk policy OS-keystore-only rejected'
require_contains "$TAURI_DIR/src/status.rs" 'session_unlock_non_readiness:'
require_contains "$TAURI_DIR/src/status.rs" 'rollback prevention secure deletion from media runtime messaging disabled'
require_contains "$APP_DIR/src/main.js" 'status.session_unlock_non_readiness'
require_contains "$TAURI_DIR/src/status.rs" 'session_unlock_cli_rejection_status:'
require_contains "$TAURI_DIR/src/status.rs" 'CLI production unlock disabled; desktop product unlock available'
require_contains "$APP_DIR/src/main.js" 'status.session_unlock_cli_rejection_status'
require_contains "$TAURI_DIR/src/status.rs" 'session_unlock_cli_rejection_flags:'
require_contains "$TAURI_DIR/src/status.rs" 'desktop_product_unlock=true storage_opened_on_user_action=true session_lifecycle_controls=true key_material_exposed=false runtime_messaging=false'
require_contains "$APP_DIR/src/main.js" 'status.session_unlock_cli_rejection_flags'
require_contains "$TAURI_DIR/src/status.rs" 'transport_status: format!'
require_contains "$APP_DIR/src/main.js" 'status.transport_status'
require_contains "$TAURI_DIR/src/status.rs" 'network_execution_status: format!'
require_contains "$TAURI_DIR/src/status.rs" 'next_connector.opens_runtime_execution()'
require_contains "$APP_DIR/src/main.js" 'status.network_execution_status'
require_contains "$TAURI_DIR/src/status.rs" 'experimental_transport_status:'
require_contains "$TAURI_DIR/src/status.rs" 'manual bootstrap gate summary only; bridge config local-sensitive and configuration-specific; no audited censorship-circumvention claim'
require_contains "$APP_DIR/src/main.js" 'status.experimental_transport_status'
require_contains "$TAURI_DIR/src/status.rs" 'bootstrap_status_classification:'
require_contains "$TAURI_DIR/src/status.rs" 'network-disabled; censorship-or-bridge-required; timeout-or-transient-network-failure'
require_contains "$APP_DIR/src/main.js" 'status.bootstrap_status_classification'
require_contains "$APP_DIR/src/main.js" 'status.production_session_status'
require_contains "$APP_DIR/src/main.js" 'status.production_self_test_status'
require_contains "$TAURI_DIR/src/status.rs" 'transport_io_status: format!'
require_contains "$TAURI_DIR/src/status.rs" 'next_connector.required_gate()'
require_contains "$APP_DIR/src/main.js" 'status.transport_io_status'
require_contains "$TAURI_DIR/src/status.rs" 'storage_status:'
require_contains "$TAURI_DIR/src/status.rs" 'ADREC1 storage spike plus forward-only schema and local data lifecycle boundary'
require_contains "$APP_DIR/src/main.js" 'status.storage_status'
require_status_field 'verification_status' 'lightweight checks only'
require_contains "$APP_DIR/src/main.js" 'invoke("prototype_status")'
require_contains "$APP_DIR/src/main.js" 'invoke("production_message_retention_policy")'
require_contains "$APP_DIR/src/main.js" 'invoke("production_profile_unlock"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_profile_list"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_pairing_payload_export"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_pairing_safety_preview"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_pairing_session_draft_save"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_session_state_check"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_handshake_init_export"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_handshake_reply_export"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_handshake_finish_export"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_handshake_finish_import"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_message_envelope_export"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_message_envelope_import"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_message_outbound_mark_send_failed"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_onion_inbound_envelope_receive_attempt"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_onion_descriptor_publication_attempt"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_onion_outbound_envelope_send_attempt"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_onion_outbound_envelope_send_stored_endpoint_attempt"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_onion_outbound_envelope_send_prepare"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_onion_service_launch_attempt"'
require_contains "$APP_DIR/src/main.js" 'fields.startProductionTwoProfileOnionReceive.addEventListener'
require_contains "$APP_DIR/src/main.js" 'fields.startProductionTwoProfileOnionBootstrap.addEventListener'
require_contains "$APP_DIR/src/main.js" 'fields.launchProductionTwoProfileOnionEndpoint.addEventListener'
require_contains "$APP_DIR/src/main.js" 'fields.sendProductionTwoProfileLatestOnionEnvelope.addEventListener'
require_contains "$APP_DIR/src/main.js" 'invoke("production_message_received_export"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_message_transcript_export"'
require_contains "$APP_DIR/src/main.js" 'createdAtMs'
require_contains "$APP_DIR/src/main.js" 'ttlSeconds'
require_contains "$APP_DIR/src/main.js" 'expiresAtMs'
require_contains "$APP_DIR/src/main.js" 'expired'
require_contains "$APP_DIR/src/main.js" 'twoProfileRetentionLabel'
require_contains "$APP_DIR/src/main.js" 'transcriptRetentionWarning'
require_contains "$APP_DIR/src/main.js" 'transcriptBoundarySummary'
require_contains "$APP_DIR/src/main.js" 'from "./transcript-export.js"'
require_contains "$APP_DIR/src/main.js" 'from "./transcript-retention.js"'
require_contains "$APP_DIR/src/transcript-export.js" 'combinedTwoProfileTranscriptTsv'
require_contains "$APP_DIR/src/transcript-retention.js" 'transcriptRetentionView'
require_contains "$APP_DIR/src/main.js" 'appendExpiredMessagesPurged'
require_contains "$APP_DIR/src/main.js" 'expired_messages_purged'
require_contains "$APP_DIR/src/styles.css" 'transcript-retention'
require_contains "$APP_DIR/src/main.js" 'loadProductionTwoProfileTranscript'
require_contains "$APP_DIR/src/main.js" 'refreshTwoProfileConversationAfterManualImport'
require_contains "$APP_DIR/src/main.js" 'syncTwoProfileConversationAfterManualExport'
require_contains "$APP_DIR/src/main.js" 'replyToLatestTwoProfileMessage'
require_contains "$APP_DIR/src/main.js" 'selectTwoProfileConversationEntryForReview'
require_contains "$APP_DIR/src/main.js" 'selectReplyAfterDeliveredReview'
require_contains "$APP_DIR/src/main.js" 'twoProfileConversationActionView'
require_contains "$APP_DIR/src/main.js" 'setProductionMessageManualCurrent'
require_contains "$APP_DIR/src/main.js" 'setOpenManualProductionToolsLabel'
require_contains "$APP_DIR/src/main.js" 'setReviewPendingTwoProfileLabel'
require_contains "$APP_DIR/src/main.js" 'setReplyLatestTwoProfileLabel'
require_contains "$APP_DIR/src/main.js" 'selectedTwoProfilePendingConversationEntry'
require_contains "$APP_DIR/src/main.js" 'selectedTwoProfileNextActionMessage'
require_contains "$APP_DIR/src/main.js" 'selectedTwoProfileManualFocusTarget'
require_contains "$APP_DIR/src/main.js" 'reviewPendingTwoProfileMessage'
require_contains "$APP_DIR/src/main.js" 'autoSelectPendingTwoProfileConversation'
require_contains "$APP_DIR/src/main.js" 'applyPendingConversationToManualMessageReview'
require_contains "$APP_DIR/src/main.js" 'invoke("production_local_roundtrip"'
require_contains "$APP_DIR/src/main.js" 'invoke("production_invite_room_setup"'
require_contains "$APP_DIR/src/main.js" 'renderProductionTwoProfileRoomSetupResult'
require_contains "$APP_DIR/src/main.js" 'hasTwoProfileSetupInput'
require_contains "$APP_DIR/src/main.js" 'invoke("dev_local_demo")'
require_contains "$APP_DIR/src/main.js" 'invoke("dev_local_message_loop"'
require_contains "$TAURI_DIR/src/lib.rs" 'production_two_profile_room_setup'
require_contains "$TAURI_DIR/src/lib.rs" 'production_invite_room_setup'
require_contains "$TAURI_DIR/src/lib.rs" 'production_invite_room_session_status'
require_contains "$TAURI_DIR/src/lib.rs" 'production_invite_room_message_send'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_two_profile_room_setup'
require_contains "$TAURI_DIR/src/lib.rs" 'production_two_profile_roundtrip'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_two_profile_roundtrip'
require_contains "$TAURI_DIR/src/lib.rs" 'production_two_profile_message_roundtrip'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_two_profile_message_roundtrip'
require_contains "$TAURI_DIR/src/lib.rs" 'production_two_profile_real_onion_roundtrip'
require_contains "$TAURI_DIR/src/lib.rs" 'run_production_two_profile_real_onion_roundtrip'
require_contains "$TAURI_DIR/src/lib.rs" 'production_two_profile_real_onion_roundtrip_smoke_delivers_or_fails_closed'
require_contains "$ROOT_DIR/scripts/smoke_tauri_two_profile.sh" 'Tauri two-profile production resume smoke passed'
require_contains "$ROOT_DIR/scripts/smoke_tauri_two_profile.sh" 'production pairing payload create'
require_contains "$ROOT_DIR/scripts/smoke_tauri_two_profile.sh" 'production pairing session save-draft'
require_contains "$ROOT_DIR/scripts/smoke_tauri_two_profile.sh" 'production pairing session handshake-finish-import'
require_contains "$ROOT_DIR/scripts/smoke_tauri_two_profile.sh" 'production message local-roundtrip'
require_contains "$ROOT_DIR/scripts/smoke_tauri_two_profile.sh" 'production message transcript-export'
require_contains "$ROOT_DIR/scripts/smoke_tauri_two_profile.sh" 'network_send_attempted=false'
require_contains "$ROOT_DIR/scripts/smoke_tauri_two_profile.sh" 'runtime_messaging=false'
require_contains "$APP_DIR/src/main.js" 'unlockProductionProfile'
require_contains "$APP_DIR/src/main.js" 'autoResume: true'
require_contains "$APP_DIR/src/main.js" 'Conversation resumed after profile unlock'
require_contains "$APP_DIR/src/main.js" 'loadProductionProfileList'
require_contains "$APP_DIR/src/main.js" 'renderProductionProfileSelector'
require_contains "$APP_DIR/src/main.js" 'applyProductionActionState'
require_contains "$APP_DIR/src/action-state.js" 'productionManualNextActions'
require_contains "$APP_DIR/src/action-state.js" 'productionManualRelayCurrentActions'
require_contains "$APP_DIR/src/action-state.js" 'productionManualRelaySuccessWarning'
require_contains "$APP_DIR/src/action-state.js" 'click Relay to peer'
require_contains "$APP_DIR/src/action-state.js" 'click Fill remote'
require_contains "$APP_DIR/src/action-state.js" 'productionActionAvailability'
require_contains "$APP_DIR/src/action-state.js" 'productionProfilePreset'
require_contains "$APP_DIR/src/action-state.js" 'productionCounterpartProfile'
require_contains "$APP_DIR/src/action-state.js" 'productionProfileUnlockView'
require_contains "$APP_DIR/src/action-state.js" 'productionPairingPayloadView'
require_contains "$APP_DIR/src/action-state.js" 'productionSessionDraftView'
require_contains "$APP_DIR/src/action-state.js" 'productionSessionStateView'
require_contains "$APP_DIR/src/action-state.js" 'productionHandshakePayloadView'
require_contains "$APP_DIR/src/action-state.js" 'productionHandshakeFinishImportView'
require_contains "$APP_DIR/src/action-state.js" 'productionMessageEnvelopeExportView'
require_contains "$APP_DIR/src/action-state.js" 'productionMessageEnvelopeImportView'
require_contains "$APP_DIR/src/action-state.js" 'productionReceivedMessageExportView'
require_contains "$APP_DIR/index.html" 'production-message-ttl'
require_contains "$APP_DIR/index.html" 'production-two-profile-message-ttl'
require_contains "$APP_DIR/src/main.js" 'messageTtlSeconds'
require_contains "$APP_DIR/src/main.js" 'selectedMessageTtlSeconds'
require_contains "$APP_DIR/src/main.js" 'loadProductionMessageRetentionPreference'
require_contains "$APP_DIR/src/main.js" 'saveProductionMessageRetentionPreference'
require_contains "$APP_DIR/src/main.js" 'production_message_retention_preference_get'
require_contains "$APP_DIR/src/main.js" 'production_message_retention_preference_set'
require_contains "$TAURI_DIR/src/lib.rs" 'sanitize_production_message_ttl_seconds'
require_contains "$TAURI_DIR/src/lib.rs" 'message_ttl_seconds'
require_contains "$APP_DIR/src/action-state.test.js" 'node:test'
require_contains "$APP_DIR/src/ui-smoke.test.js" 'node:test'
require_contains "$APP_DIR/package.json" 'test:state'
require_contains "$APP_DIR/package.json" 'src/ui-smoke.test.js'
require_contains "$APP_DIR/src/main.js" 'productionSessionReadyForMessages'
require_contains "$APP_DIR/src/main.js" 'applyProductionProfilePreset'
require_contains "$APP_DIR/src/main.js" 'moveLocalPayload'
require_contains "$APP_DIR/src/main.js" 'storeProductionPayloadSlot'
require_contains "$APP_DIR/src/main.js" 'loadProductionPayloadSlot'
require_contains "$APP_DIR/src/main.js" 'moveLocalMessageEnvelope'
require_contains "$APP_DIR/src/main.js" 'storeProductionMessageEnvelope'
require_contains "$APP_DIR/src/main.js" 'loadProductionMessageEnvelope'
require_contains "$APP_DIR/src/main.js" 'clearImportedMessageEnvelopeSlot'
require_contains "$APP_DIR/src/main.js" 'exportProductionPairingPayload'
require_contains "$APP_DIR/src/main.js" 'saveProductionSessionDraft'
require_contains "$APP_DIR/src/main.js" 'checkProductionSessionState'
require_contains "$APP_DIR/src/main.js" 'exportProductionHandshakeInit'
require_contains "$APP_DIR/src/main.js" 'exportProductionHandshakeReply'
require_contains "$APP_DIR/src/main.js" 'exportProductionHandshakeFinish'
require_contains "$APP_DIR/src/main.js" 'importProductionHandshakeFinish'
require_contains "$APP_DIR/src/main.js" 'exportProductionMessageEnvelope'
require_contains "$APP_DIR/src/main.js" 'importProductionMessageEnvelope'
require_contains "$APP_DIR/src/main.js" 'exportProductionReceivedMessage'
require_contains "$APP_DIR/src/main.js" 'runProductionTwoProfileRoundtrip'
require_contains "$APP_DIR/src/main.js" 'runProductionRoundtrip'
require_contains "$APP_DIR/src/main.js" 'runLocalLoop'
require_contains "$APP_DIR/index.html" 'data-theme="dark"'
require_contains "$APP_DIR/index.html" '<button id="theme-toggle" type="button" aria-pressed="true">Dark mode</button>'
require_contains "$APP_DIR/src/main.js" 'themeStorageKey'
require_contains "$APP_DIR/src/main.js" 'toggleTheme'
require_contains "$APP_DIR/src/main.js" 'renderAppStateSummary'
require_contains "$APP_DIR/src/i18n.js" 'mainBlockerSummary'
require_contains "$APP_DIR/src/action-state.js" 'productionTwoProfileReadiness'
require_contains "$APP_DIR/src/action-state.js" 'productionTwoProfileConversationActionView'
require_contains "$APP_DIR/src/main.js" 'renderProductionTwoProfileResult'
require_contains "$APP_DIR/src/action-state.js" 'productionTwoProfileResultView'
require_contains "$APP_DIR/src/main.js" 'setProductionFollowupActions'
require_contains "$APP_DIR/src/main.js" 'selectTwoProfileConversationEntry'
require_contains "$APP_DIR/src/main.js" 'setSelectedTwoProfileConversationEntry'
require_contains "$APP_DIR/src/main.js" 'selectTwoProfileConversationMessage'
require_contains "$APP_DIR/src/main.js" 'Reply target selected'
require_contains "$APP_DIR/src/main.js" 'Send reply to selected message'
require_contains "$APP_DIR/src/main.js" 'swapTwoProfileDirection'
require_contains "$APP_DIR/src/main.js" 'openManualProductionTools'
require_contains "$APP_DIR/src/main.js" 'renderManualStatus'
require_contains "$APP_DIR/src/main.js" 'renderManualMessageStatus'
require_contains "$APP_DIR/src/main.js" 'setActionButtonState'
require_contains "$APP_DIR/src/main.js" 'checkProductionTwoProfileSessionStatus'
require_contains "$APP_DIR/src/main.js" 'latestTwoProfileSessionStatusForCurrentInput'
require_contains "$APP_DIR/src/main.js" 'knownTwoProfileSessionStatus'
require_contains "$APP_DIR/src/main.js" 'twoProfileSessionsIncomplete'
require_contains "$APP_DIR/src/main.js" 'openInviteRoomFromToken'
require_contains "$APP_DIR/src/main.js" 'startInviteRoomFromCode'
require_contains "$APP_DIR/src/main.js" 'finishInviteRoomReadyFromStatus'
require_contains "$APP_DIR/src/main.js" 'confirmTwoProfileSafetyForInput'
require_contains "$APP_DIR/src/main.js" 'prepareInviteRoomPrivateRouteExchange'
require_contains "$APP_DIR/src/main.js" 'applyPeerPrivateRouteCode'
require_contains "$APP_DIR/index.html" 'room-invite-token-display'
require_contains "$APP_DIR/index.html" 'received-invite-code'
require_contains "$APP_DIR/index.html" 'private-route-exchange'
require_contains "$APP_DIR/src/main.js" 'Check recovered sessions before writing'
require_contains "$APP_DIR/src/main.js" 'twoProfileSessionRebuildMessage'
require_contains "$APP_DIR/src/main.js" 'autoSelectPendingTwoProfileConversation'
require_contains "$APP_DIR/src/main.js" 'retry-send'
require_contains "$APP_DIR/src/main.js" 'pending-review'
require_contains "$APP_DIR/src/main.js" 'Resume needs session check'
require_contains "$APP_DIR/src/main.js" 'Resume needs review'
require_contains "$APP_DIR/src/main.js" 'syncProductionProfilePassphraseFromTwoProfile'
require_contains "$APP_DIR/src/main.js" 'preserveTwoProfileStatus'
require_contains "$APP_DIR/src/action-state.js" 'productionManualStatusView'
require_contains "$APP_DIR/src/action-state.js" 'productionManualMessageStatusView'
require_contains "$APP_DIR/src/action-state.js" 'productionManualRelayAvailability'
require_contains "$APP_DIR/src/action-state.js" 'productionTwoProfileSessionStatusView'
require_contains "$APP_DIR/src/action-state.js" 'productionProfileMessageReadiness'
require_contains "$APP_DIR/src/action-state.js" 'Next: reply direction is selected'
require_contains "$APP_DIR/src/action-state.js" 'Invite code needed'
require_contains "$APP_DIR/src/action-state.js" 'Ready: room can be created'
require_contains "$APP_DIR/src/action-state.js" 'no plaintext, key material, store path, network I/O, transport I/O, or runtime messaging exposure'
require_contains "$APP_DIR/src/styles.css" '[data-theme="light"]'
require_contains "$APP_DIR/src/styles.css" '.status-summary'
require_contains "$APP_DIR/src/styles.css" '.boundary-details'
require_contains "$APP_DIR/src/styles.css" '.action-readiness'
require_contains "$APP_DIR/src/styles.css" '.followup-actions'
require_contains "$APP_DIR/index.html" 'class="production-workflow"'
require_contains "$APP_DIR/index.html" '<details class="advanced-panel">'
require_contains "$APP_DIR/index.html" '<summary data-i18n="manualProductionTools">Transfer details</summary>'
require_contains "$APP_DIR/src/i18n.js" 'Transfer details'
require_contains "$APP_DIR/src/i18n.js" 'hasTranslation'
require_contains "$APP_DIR/src/i18n.test.js" 'visible app translation keys exist in both languages'
require_contains "$APP_DIR/src/styles.css" '.advanced-panel:not(.is-revealed)'
require_contains "$APP_DIR/src/styles.css" '.dev-diagnostic-panel:not(.is-revealed)'
require_contains "$APP_DIR/src/styles.css" '.chat-diagnostics:not(.is-revealed)'
require_contains "$APP_DIR/src/styles.css" '.followup-actions:not(.is-revealed)'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active .followup-actions'
require_contains "$APP_DIR/src/styles.css" 'body.is-developer-mode .advanced-panel.is-revealed'
require_contains "$APP_DIR/src/styles.css" 'body.is-developer-mode .followup-actions.is-revealed'
require_contains "$APP_DIR/src/styles.css" '\.system-settings-panel\[open\] > \.status-summary'
require_contains "$APP_DIR/src/styles.css" 'body\.is-developer-mode \.system-settings-panel\[open\] > \.status-summary'
require_contains "$APP_DIR/src/styles.css" '\.system-settings-panel\[open\] > \.boundary-details'
require_contains "$APP_DIR/src/i18n.js" '전송 상세'
require_contains "$APP_DIR/src/i18n.js" 'Start a private room'
require_contains "$APP_DIR/src/i18n.js" '비공개 채팅방 시작'
require_contains "$APP_DIR/index.html" 'connection-choice-grid'
require_contains "$APP_DIR/index.html" 'connectionChoiceCreate'
require_contains "$APP_DIR/index.html" 'connectionChoiceCreateText'
require_contains "$APP_DIR/index.html" 'connectionChoiceEnterText'
require_contains "$APP_DIR/src/i18n.js" '한 명은 초대 코드를 만들고'
require_contains "$APP_DIR/index.html" 'room-network-permission'
require_contains "$APP_DIR/index.html" 'class="room-secondary-options"'
require_contains "$APP_DIR/src/styles.css" '.room-secondary-options > summary'
require_contains "$APP_DIR/src/main.js" 'roomNetworkPermission'
require_contains "$APP_DIR/src/main.js" 'manualNetworkPermissionEnabled()'
require_contains "$APP_DIR/src/main.js" 'focusTarget?.closest?.("details")'
require_contains "$APP_DIR/src/styles.css" 'body.is-developer-mode .onion-advanced-controls'
require_contains "$APP_DIR/src/main.js" 'connectionCodeRoleFor'
require_contains "$APP_DIR/src/action-state.js" 'productionInviteCodeProfiles'
require_contains "$APP_DIR/src/action-state.js" 'productionInviteCodeProfileName'
require_contains "$APP_DIR/src/action-state.test.js" 'invite code creates opposite local and peer roles'
require_contains "$APP_DIR/src/action-state.test.js" 'chat action moves from setup to compose to stored send'
require_contains "$APP_DIR/src/main.js" 'dataset.peerProfile'
require_contains "$APP_DIR/src/main.js" 'twoProfileInviteCodeModeActive'
require_contains "$APP_DIR/src/main.js" 'keepTwoProfileInviteCodeDirection("swap")'
require_contains "$APP_DIR/src/main.js" 'inviteCodeProfileSelectionIgnored'
require_contains "$APP_DIR/src/main.js" 'twoProfileConversationUserActionMessage'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active .message-transcript .transcript-review'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active .chat-transcript-toolbar #review-pending-two-profile-message'
require_contains "$APP_DIR/src/main.js" 'cancel.textContent = t("cancelSend")'
require_contains "$APP_DIR/src/i18n.js" 'cancelSend: "전송 취소"'
require_contains "$APP_DIR/src/i18n.js" 'Allow network delivery only when I press send or listen'
require_contains "$APP_DIR/src/i18n.js" 'Allow private delivery before sending or listening'
require_contains "$APP_DIR/src/styles.css" '.network-permission-toggle'
require_contains "$APP_DIR/src/main.js" 'localizedSendAttemptMessage'
require_contains "$APP_DIR/src/main.js" 'setChatDeliveryNoticeForSendAttempt'
require_contains "$APP_DIR/src/main.js" 'stored remote endpoint refresh required'
require_contains "$APP_DIR/src/i18n.js" 'Message saved. Turn on private delivery to send it.'
require_contains "$APP_DIR/index.html" 'copy-room-invite-token'
require_contains "$APP_DIR/index.html" 'reject-two-profile-safety'
require_contains "$APP_DIR/index.html" 'close-app-settings'
require_contains "$APP_DIR/src/main.js" 'closeChatSettings'
require_contains "$APP_DIR/src/main.js" 'closeAppSettings'
require_contains "$APP_DIR/src/main.js" 'is-chat-settings-open'
require_contains "$APP_DIR/src/main.js" 'is-app-settings-open'
require_contains "$APP_DIR/src/i18n.js" '설정 닫기'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-settings-open::before'
require_contains "$APP_DIR/src/styles.css" 'body.is-app-settings-open::before'
require_contains "$APP_DIR/src/i18n.js" '내 코드 만들기'
require_contains "$APP_DIR/src/i18n.js" '문구가 다르면 이 채팅방을 사용하지 마세요'
require_contains "$APP_DIR/src/i18n.js" 'roomStatusShortReady: "Local ready"'
require_contains "$APP_DIR/src/i18n.js" 'roomStatusShortReady: "로컬 준비"'
require_contains "$APP_DIR/src/i18n.js" 'roomStatusShortReceiving: "수신 중"'
require_contains "$APP_DIR/src/i18n.js" 'roomStatusShortWaiting'
require_contains "$APP_DIR/src/main.js" 'latestTwoProfileRetryableOutboundEntry(input)'
require_contains "$APP_DIR/src/main.js" 'roomStatusShortWaiting'
require_contains "$APP_DIR/src/styles.css" '.room-status-summary.is-waiting'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active .room-identity-bar'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active:not(.has-confirmed-safety) .room-identity-bar'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active .chat-transcript-toolbar'
require_contains "$APP_DIR/src/styles.css" 'room-status-summary.is-ready:not(.is-receiving)'
require_contains "$APP_DIR/src/styles.css" 'chat-transcript-toolbar:not(.has-reply-action)'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active #production-two-profile-flow'
require_contains "$APP_DIR/src/styles.css" 'content: "..."'
require_contains "$APP_DIR/src/main.js" 'onionDeliveryStarting'
require_contains "$APP_DIR/src/main.js" 'transcript-delivery-note'
require_contains "$APP_DIR/index.html" 'chat-delivery-notice'
require_contains "$APP_DIR/src/main.js" 'updateChatDeliveryNoticeFromText'
require_contains "$APP_DIR/src/main.js" 'realOnionNotice'
require_contains "$APP_DIR/src/i18n.js" 'chatNoticeRefreshAddress'
require_contains "$APP_DIR/src/action-state.test.js" 'failed outbound messages stay retryable or cancelable from the active device'
require_contains "$APP_DIR/src/main.js" 'retryableTwoProfileOutboundWarning'
require_contains "$APP_DIR/src/main.js" 'twoProfileResumeWarningForTarget'
require_contains "$APP_DIR/src/i18n.js" 'chatNoticeEndpointUpdated'
require_contains "$APP_DIR/src/i18n.js" '새 메시지를 기다리는 중입니다'
require_contains "$APP_DIR/src/i18n.js" '메시지를 받기 전에 확인 문구를 비교하세요'
require_contains "$APP_DIR/src/main.js" 'profile: profileA'
require_contains "$APP_DIR/src/main.js" 'receiveNeedsReadyRoom'
require_contains "$APP_DIR/src/main.js" 'receiveNeedsVerification'
require_contains "$APP_DIR/src/i18n.js" 'receiveStillListening'
require_contains "$APP_DIR/src/main.js" 'productionTwoProfileOnionReceiveUserNotice'
require_contains "$APP_DIR/src/main.js" 'productionTwoProfileOnionReceiveImportSummary(refreshPlan)'
require_contains "$APP_DIR/src/main.js" 'chatNoticeForProductionState("Message listening will retry")'
require_contains "$APP_DIR/src/main.js" 'refreshSessionStatus: refreshPlan.endpointUpdated === true'
require_contains "$APP_DIR/src/i18n.js" 'receiveStopPending'
require_contains "$APP_DIR/src/main.js" 'productionTwoProfileOnionReceiveImportSummary'
require_contains "$APP_DIR/src/action-state.js" 'productionTwoProfileRealOnionResultView'
require_contains "$APP_DIR/src/action-state.js" 'touchedTranscript'
require_contains "$APP_DIR/src/main.js" 'view.touchedTranscript'
require_contains "$APP_DIR/index.html" '<section class="room-receive-controls"'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active .room-receive-controls'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active.has-message-draft:not(.is-receiving-messages) .room-receive-controls'
require_contains "$APP_DIR/src/styles.css" 'body.is-chat-active.has-private-delivery-permission.has-message-draft:not(.is-receiving-messages)'
require_contains "$APP_DIR/src/styles.css" 'border-radius: 999px'
require_contains "$APP_DIR/src/main.js" 'document.body.classList.toggle("has-message-draft", hasDraft)'
require_contains "$APP_DIR/src/main.js" 'return currentLanguage === "ko" ? "메시지 작성" : "Write a message";'
require_contains "$APP_DIR/src/main.js" 'hasConversation || latestTwoProfileSuccessForInput(input) || sessionsReady'
require_not_contains "$APP_DIR/src/main.js" 'applyDevActiveChatMockFromUrl'
require_not_contains "$APP_DIR/src/main.js" 'Dev layout mock'
require_not_contains "$APP_DIR/src/main.js" 'mock=active-chat'
require_contains "$APP_DIR/src/styles.css" 'body.needs-safety-confirmation #production-two-profile-transcript'
require_contains "$APP_DIR/index.html" 'production-manual-route'
require_contains "$APP_DIR/index.html" 'production-manual-direction'
require_contains "$APP_DIR/index.html" 'production-manual-slots'
require_contains "$APP_DIR/src/action-state.js" 'active_slot(${profile})'
require_contains "$APP_DIR/src/action-state.js" 'counterpart_slot(${remoteProfile})'
require_contains "$APP_DIR/index.html" 'production-manual-policy'
require_contains "$APP_DIR/src/action-state.js" 'button_confirmed_profile_switch=true background_profile_switch=false network_io=false'
require_contains "$APP_DIR/index.html" 'production-message-active-status'
require_contains "$APP_DIR/index.html" 'production-message-manual-check'
require_contains "$APP_DIR/index.html" 'check-production-two-profile-session-status'
require_contains "$APP_DIR/src/action-state.js" 'pasted envelope is not from the stored remote slot'
require_contains "$APP_DIR/src/action-state.js" 'load the remote envelope manually before import'
require_contains "$APP_DIR/src/styles.css" '.manual-relay-summary'
require_contains "$APP_DIR/src/styles.css" '.is-current-action'
require_contains "$APP_DIR/index.html" 'use-alice-production-profile'
require_contains "$APP_DIR/index.html" 'use-bob-production-profile'
require_contains "$APP_DIR/index.html" 'store-production-pairing-payload'
require_contains "$APP_DIR/index.html" 'load-production-pairing-payload'
require_contains "$APP_DIR/index.html" 'store-production-handshake-init'
require_contains "$APP_DIR/index.html" 'load-production-handshake-init'
require_contains "$APP_DIR/index.html" 'store-production-handshake-reply'
require_contains "$APP_DIR/index.html" 'load-production-handshake-reply'
require_contains "$APP_DIR/index.html" 'store-production-handshake-finish'
require_contains "$APP_DIR/index.html" 'load-production-handshake-finish'
require_contains "$APP_DIR/index.html" 'store-production-message-envelope'
require_contains "$APP_DIR/index.html" 'load-production-message-envelope'
require_contains "$APP_DIR/src-tauri/src/lib.rs" 'production_two_profile_session_status'
require_contains "$APP_DIR/src/styles.css" '.production-workflow'
require_contains "$APP_DIR/src/styles.css" '.advanced-panel'
require_contains "$APP_DIR/src/main.js" 'localLoopMessages'
require_contains "$APP_DIR/src/main.js" 'renderLoopResults'
require_contains "$APP_DIR/src/main.js" 'Loop completed'
require_contains "$APP_DIR/src/main.js" 'result.replay_summary'
require_contains "$APP_DIR/src/main.js" 'result.storage_guard'
require_contains "$APP_DIR/src/main.js" 'Demo running'
require_contains "$APP_DIR/src/main.js" 'Demo completed'
require_contains "$APP_DIR/src/main.js" 'Demo failed'
require_contains "$APP_DIR/src/main.js" 'renderDemoSteps'
require_contains "$APP_DIR/src/main.js" 'renderFlowControls'
require_contains "$APP_DIR/src/main.js" 'applySimulationStage'
require_contains "$APP_DIR/src/main.js" 'Reset local view'
require_contains "$APP_DIR/src/main.js" 'result.simulation'
require_contains "$APP_DIR/src/main.js" 'result.first_run_hint'
require_contains "$APP_DIR/src/main.js" 'result.steps'
require_contains "$APP_DIR/src/main.js" 'First run may take longer while Cargo builds the dev-insecure local demo.'
require_contains "$APP_DIR/src/main.js" 'result.warning.trim()'
require_contains "$APP_DIR/src/main.js" 'result.transcript.trim()'
require_contains "$APP_DIR/src/main.js" 'Unexpected release claim'
require_contains "$APP_DIR/src/main.js" 'Unexpected messaging status'
require_contains "$APP_DIR/README.md" 'not a secure-release claim'
require_contains "$APP_DIR/README.md" 'dev_local_demo'
require_contains "$APP_DIR/README.md" 'not production messaging'
require_contains "$APP_DIR/README.md" 'Build a local-only lightweight desktop public shell'
require_contains "$APP_DIR/README.md" 'public-shell first run avoids compiling the full Rust core/runtime stack'
require_contains "$APP_DIR/README.md" 'structured local flow steps'
require_contains "$APP_DIR/README.md" 'Alice/Bob peer panels'
require_contains "$APP_DIR/README.md" 'Reset local view'
require_contains "$APP_DIR/README.md" 'repeatable local loop'
require_contains "$APP_DIR/README.md" 'demo local-loop'
require_contains "$APP_DIR/README.md" 'dev store plaintext guard'
require_contains "$APP_DIR/README.md" 'core, profile'
require_contains "$APP_DIR/README.md" 'security-sensitive protocol, storage, and transport work stays in Rust commands'
require_contains "$APP_DIR/README.md" 'conservative pre-network copy'
require_contains "$APP_DIR/README.md" 'production-session status'
require_contains "$APP_DIR/README.md" 'static evaluation copy for the `snow` Noise XX synchronous boundary'
require_contains "$APP_DIR/README.md" 'onion transport commands are separate explicit user-triggered actions'
require_contains "$APP_DIR/README.md" 'production-self-test status'
require_contains "$APP_DIR/README.md" 'does not execute from the Tauri shell or mark messaging usable'
require_contains "$APP_DIR/README.md" 'production-session limits copy'
require_contains "$APP_DIR/README.md" 'production-preflight'
require_contains "$APP_DIR/README.md" 'mirrors the CLI `production preflight` blockers as static read-only copy'
require_contains "$APP_DIR/README.md" 'does not execute the CLI command, bootstrap transport, or mark messaging usable'
require_contains "$APP_DIR/README.md" 'session lifecycle controls can check and delete local encrypted session draft'
require_contains "$APP_DIR/README.md" 'no audited readiness claim'
require_contains "$APP_DIR/README.md" 'session unlock-policy status'
require_contains "$APP_DIR/README.md" 'Product unlock/lock commands open the local encrypted profile store only after explicit user passphrase input'
require_contains "$APP_DIR/README.md" 'session unlock-limits'
require_contains "$APP_DIR/README.md" 'rollback prevention secure deletion from media runtime messaging disabled'
require_contains "$APP_DIR/README.md" 'session unlock-rejection status'
require_contains "$APP_DIR/README.md" 'CLI `production unlock` command remains fail-closed'
require_contains "$APP_DIR/README.md" 'does not expose profile paths, passphrases, raw storage errors, key material, write session records, or enable runtime messaging'
require_contains "$APP_DIR/README.md" 'network-execution'
require_contains "$APP_DIR/README.md" 'disabled-by-default copy'
require_contains "$APP_DIR/README.md" 'experimental-transport'
require_contains "$APP_DIR/README.md" 'manual-gate summary'
require_contains "$APP_DIR/README.md" 'bootstrap-status classification'
require_contains "$APP_DIR/README.md" 'network-disabled'
require_contains "$APP_DIR/README.md" 'timeout-or-transient-network-failure'
require_contains "$APP_DIR/README.md" 'does not expose raw Arti errors, paths, endpoints, bridge lines, descriptors, profile names, contact ids, or key material'
require_contains "$APP_DIR/README.md" 'transport-I/O'
require_contains "$APP_DIR/README.md" 'explicit onion commands report redacted attempt results'
require_contains "$APP_DIR/README.md" 'static `ADREC1` spike copy'
require_contains "$APP_DIR/README.md" 'does not claim complete production key management'
require_contains "$APP_DIR/README.md" 'verification boundaries'
require_contains "$APP_DIR/index.html" 'Private 1:1 chat'
require_contains "$APP_DIR/index.html" 'Another Dimension Chat'
require_contains "$APP_DIR/index.html" 'Current app state'
require_contains "$APP_DIR/index.html" 'app-release-summary'
require_contains "$APP_DIR/index.html" 'local-capability-summary'
require_contains "$APP_DIR/index.html" 'main-blocker-summary'
require_contains "$APP_DIR/index.html" 'production-two-profile-direction'
require_contains "$APP_DIR/index.html" 'production-two-profile-flow'
require_contains "$APP_DIR/index.html" 'production-two-profile-readiness'
require_contains "$APP_DIR/index.html" 'check-production-two-profile-session-status-inline'
require_contains "$APP_DIR/index.html" 'Developer follow-up'
require_contains "$APP_DIR/index.html" 'open-manual-production-tools'
require_contains "$APP_DIR/index.html" 'Review details'
require_contains "$APP_DIR/index.html" 'Private detail check'
require_contains "$APP_DIR/index.html" 'Developer details'
require_contains "$APP_DIR/index.html" 'Session durable state'
require_contains "$APP_DIR/index.html" 'Session unlock policy'
require_contains "$APP_DIR/index.html" 'Session unlock limits'
require_contains "$APP_DIR/index.html" 'Session unlock rejection'
require_contains "$APP_DIR/index.html" 'Unlock rejection flags'
require_contains "$APP_DIR/index.html" 'Only visible on this device'
require_contains "$APP_DIR/index.html" 'Alice/Bob dev-insecure flow'
require_contains "$APP_DIR/index.html" 'Run local demo'
require_contains "$APP_DIR/index.html" 'Demo idle'
require_contains "$APP_DIR/index.html" 'First run may take longer while Cargo builds the dev-insecure local demo.'
require_contains "$APP_DIR/index.html" 'Warning has not run yet.'
require_contains "$APP_DIR/index.html" 'Local demo flow steps'
require_contains "$APP_DIR/index.html" 'Steps have not run yet.'
require_contains "$APP_DIR/index.html" 'Local peer simulation'
require_contains "$APP_DIR/index.html" 'Alice and Bob state'
require_contains "$APP_DIR/index.html" 'Local flow controls'
require_contains "$APP_DIR/index.html" 'Local peer panels'
require_contains "$APP_DIR/index.html" 'Safety number'
require_contains "$APP_DIR/index.html" 'Replay check'
require_contains "$APP_DIR/index.html" 'Saved room check'
require_contains "$APP_DIR/index.html" 'Snow Noise XX synchronous evaluation boundary only'
require_contains "$APP_DIR/index.html" 'Production self-test'
require_contains "$APP_DIR/index.html" 'CLI production boundary self-test only'
require_contains "$APP_DIR/index.html" 'Room session limits'
require_contains "$APP_DIR/index.html" 'No audited production E2EE claim network transport automatic messaging or secure release'
require_contains "$APP_DIR/index.html" 'Production preflight'
require_contains "$APP_DIR/index.html" 'Read-only production skeleton blockers copy'
require_contains "$APP_DIR/index.html" 'Preflight blockers'
require_contains "$APP_DIR/index.html" 'session E2EE false transport send receive false storage rollback not-provided messaging false'
require_contains "$APP_DIR/index.html" 'Production profile'
require_contains "$APP_DIR/index.html" 'Persistent local store'
require_contains "$APP_DIR/index.html" 'production-profile-selector'
require_contains "$APP_DIR/index.html" 'Unlock profile'
require_contains "$APP_DIR/index.html" 'Production pairing'
require_contains "$APP_DIR/index.html" 'Public payload export'
require_contains "$APP_DIR/index.html" 'Export pairing'
require_contains "$APP_DIR/index.html" 'Fill local'
require_contains "$APP_DIR/index.html" 'Fill remote'
require_contains "$APP_DIR/src/action-state.js" 'Fill local copies the active output field'
require_contains "$APP_DIR/src/action-state.js" 'manually select the counterpart profile'
require_contains "$APP_DIR/src/action-state.js" 'manually select Alice or Bob'
require_contains "$APP_DIR/src/main.js" 'expected_counterpart='
require_contains "$APP_DIR/src/main.js" 'loaded_from='
require_contains "$APP_DIR/src/main.js" 'Filled remote field from active='
require_contains "$APP_DIR/src/main.js" 'manualMissingCounterpartWarning'
require_contains "$APP_DIR/src/main.js" 'manualLoadedCounterpartWarning'
require_contains "$APP_DIR/index.html" 'Remote payload'
require_contains "$APP_DIR/index.html" 'Save draft'
require_contains "$APP_DIR/index.html" 'Handshake init'
require_contains "$APP_DIR/index.html" 'Remote handshake init'
require_contains "$APP_DIR/index.html" 'Handshake reply'
require_contains "$APP_DIR/index.html" 'Remote handshake reply'
require_contains "$APP_DIR/index.html" 'Handshake finish'
require_contains "$APP_DIR/index.html" 'Remote handshake finish'
require_contains "$APP_DIR/index.html" 'Export init'
require_contains "$APP_DIR/index.html" 'Import finish'
require_contains "$APP_DIR/index.html" 'Check session'
require_contains "$APP_DIR/index.html" 'Production message'
require_contains "$APP_DIR/index.html" 'Encrypted envelope path'
require_contains "$APP_DIR/index.html" 'Export envelope'
require_contains "$APP_DIR/index.html" 'Remote envelope'
require_contains "$APP_DIR/index.html" 'Import envelope'
require_contains "$APP_DIR/index.html" 'Attempt onion launch'
require_contains "$APP_DIR/index.html" 'Attempt descriptor publish'
require_contains "$APP_DIR/index.html" 'Prepare envelope send'
require_contains "$APP_DIR/index.html" 'Show plaintext'
require_contains "$APP_DIR/index.html" 'Received message'
require_contains "$APP_DIR/index.html" 'Production core local roundtrip'
require_contains "$APP_DIR/index.html" 'Run core roundtrip'
require_contains "$APP_DIR/index.html" 'Repeatable local loop'
require_contains "$APP_DIR/index.html" 'Local message loop'
require_contains "$APP_DIR/index.html" 'Run local loop'
require_contains "$APP_DIR/index.html" 'Reset loop view'
require_contains "$APP_DIR/index.html" 'Local loop message results'
require_contains "$APP_DIR/index.html" 'Storage guard'
require_contains "$APP_DIR/index.html" 'Release claim'
require_status_copy 'No secure-release claim'
require_status_copy 'No runtime messaging path'
require_status_copy 'Core boundary only'
require_status_copy 'Profile boundary only'
require_status_copy 'Pairing boundary only'
require_status_copy 'Snow Noise XX synchronous evaluation boundary only'
require_status_copy 'CLI production boundary self-test only'
require_status_copy 'No audited production E2EE claim network transport automatic messaging or secure release'
require_status_copy 'Read-only production skeleton blockers copy'
require_status_copy 'session E2EE false transport send receive false storage rollback not-provided messaging false'
require_status_copy 'Pre-network fail-closed only'
require_status_copy 'Network execution disabled'
require_status_copy 'Manual bootstrap gate summary only'
require_status_copy 'network-disabled; censorship-or-bridge-required;'
require_status_copy 'timeout-or-transient-network-failure'
require_status_copy 'Hosting stream envelope messaging disabled'
require_status_copy 'ADREC1 storage spike plus forward-only schema and local data lifecycle boundary'
require_status_copy 'Lightweight checks only'
require_contains "$APP_DIR/.npmrc" '^workspaces=false$'
require_contains "$APP_DIR/package-lock.json" '"lockfileVersion": 3'
require_contains "$APP_DIR/package-lock.json" '"vite": "^6.0.0"'
require_contains "$TAURI_DIR/Cargo.lock" 'name = "tauri"'

status_false_count="$(grep -E '^\s*[a-z_]+: false,' "$TAURI_DIR/src/status.rs" | wc -l | tr -d ' ')"
test "$status_false_count" = "2"

if grep -n -E '^\s*[a-z_]+: true,' "$TAURI_DIR/src/status.rs" >/dev/null; then
  echo "status adapter must not expose true readiness flags" >&2
  exit 1
fi

if grep -n -E 'secure_release:|usable_messaging:|core_status:|profile_status:|pairing_status:|production_session_status:|production_self_test_status:|production_session_non_readiness:|production_preflight_status:|production_preflight_blockers:|transport_status:|network_execution_status:|storage_status:|verification_status:' "$TAURI_DIR/src/lib.rs" >/dev/null; then
  echo "Tauri command wrapper must delegate status construction to status.rs" >&2
  exit 1
fi

if grep -n -E '"[^"]*(secure release ready|usable messaging ready|connected|bootstrapped)[^"]*"' "$TAURI_DIR/src/status.rs" >/dev/null; then
  echo "status adapter must not imply readiness or secure-release state" >&2
  exit 1
fi

startup_block="$(awk 'found { print } /initializeLanguage\\(\\);/ { found = 1; print }' "$APP_DIR/src/main.js")"
if printf '%s\n' "$startup_block" | grep -n -E 'invoke\("production_onion_|production_onion_receive_loop_start|production_onion_service_launch_attempt|production_onion_outbound_envelope_send_attempt|production_onion_inbound_envelope_receive_attempt' >/dev/null; then
  echo "Tauri startup block must not invoke onion network commands" >&2
  exit 1
fi

cargo metadata --manifest-path "$TAURI_DIR/Cargo.toml" --no-deps --format-version 1 >/dev/null

npm --prefix "$APP_DIR" run verify:ui-loop-scripts
npm --prefix "$APP_DIR" run test:ui-fast
bash "$ROOT_DIR/scripts/repo_size_guard_once.sh"

printf 'tauri scaffold static and UI verification passed\n'
