#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

grep -q 'license = "UNLICENSED"' "$ROOT_DIR/Cargo.toml"
grep -q 'publish = false' "$ROOT_DIR/Cargo.toml"
grep -q '"private": true' "$ROOT_DIR/apps/desktop-tauri/package.json"
grep -q 'Default build boundary checks that keep `dev-insecure` out of default feature sets' "$ROOT_DIR/README.md"
grep -q 'Default CLI hardening rejects production skeleton commands for profile, pairing, messaging, storage unlock, transport bootstrap, and transport send/receive' "$ROOT_DIR/README.md"
grep -q 'Production skeleton preflight summary aggregates current crypto/session, transport, storage, and command-surface blockers' "$ROOT_DIR/README.md"
grep -q 'Production skeleton next connector selection keeps the next slice on session protocol and durable-state gates without opening runtime execution' "$ROOT_DIR/README.md"
grep -q 'Session durable-state connector gate draft records private-key and replay storage requirements while keeping Noise transport state in memory and runtime execution closed' "$ROOT_DIR/README.md"
grep -q 'Session durable-state connector harness applies the storage policy to those records and rejects session transport persistence before any connector implementation' "$ROOT_DIR/README.md"
grep -q 'Session durable-state persistence adapter skeleton maps the allowed record policies without implementing storage unlock, transport I/O, or runtime messaging' "$ROOT_DIR/README.md"
grep -q 'Session durable-state encrypted-record adapter spike prepares allowed sealed records without writing them to a store or enabling durable Noise transport state' "$ROOT_DIR/README.md"
grep -q 'Session durable-state adapter non-readiness guard keeps rollback protection, durable session persistence, production E2EE readiness, store writes, and runtime messaging false' "$ROOT_DIR/README.md"
grep -q 'Session durable-state store-write spike is test-only and round-trips a prepared sealed record through SQLCipher without adding a production unlock or messaging path' "$ROOT_DIR/README.md"
grep -q 'Session durable-state store-write status mirror marks that coverage as test-only while keeping production store write, unlock, durable persistence, rollback protection, and runtime messaging disabled' "$ROOT_DIR/README.md"
grep -q 'Session durable-state product unlock blocker summary keeps product unlock closed until key wrapping, backup exclusion, rollback, and durable session lifecycle decisions are complete' "$ROOT_DIR/README.md"
grep -q 'Session durable-state unlock policy handoff confirms high-risk passphrase-first unlock policy and OS-keystore-only rejection while keeping product unlock and runtime messaging disabled' "$ROOT_DIR/README.md"
grep -q 'Session unlock/lock command design gate requires explicit lock, idle auto-lock, redacted unlock errors, and passphrase-first high-risk policy while keeping product unlock and lock commands disabled' "$ROOT_DIR/README.md"
grep -q 'Session unlock command fail-closed skeleton accepts request shape coverage but always returns a redacted disabled result without opening storage, writing session records, exposing key material, or enabling runtime messaging' "$ROOT_DIR/README.md"
grep -q 'Session lock lifecycle status mirror records default/high-risk idle auto-lock requirements while keeping storage unlocked state, product lock command, key erasure claim, and runtime messaging disabled' "$ROOT_DIR/README.md"
grep -q 'Session unlock redacted error taxonomy classifies disabled, passphrase-required, and OS-keystore-only rejected states without exposing raw storage errors, OS keychain errors, paths, identifiers, key material, or passphrase detail' "$ROOT_DIR/README.md"
grep -q 'Default CLI `production unlock` is a fail-closed boundary command that returns the redacted disabled taxonomy without opening storage, writing session records, exposing key material, or enabling runtime messaging' "$ROOT_DIR/README.md"
grep -q 'Tauri prototype status mirrors the CLI production unlock redacted disabled taxonomy as static read-only copy without adding an unlock command or executing the CLI' "$ROOT_DIR/README.md"
grep -q 'Tauri prototype status mirrors session durable-state and unlock-policy blockers as static read-only copy without adding unlock, store-write, or runtime messaging commands' "$ROOT_DIR/README.md"
grep -q 'A public-safe release hardening gap inventory that tracks missing signing, reproducible/equivalent verification, dependency review, release-copy alignment, external review readiness, and update integrity before any security-ready claim' "$ROOT_DIR/README.md"
grep -q 'A release artifact gate verifier skeleton that keeps signing and reproducible/equivalent verification documented as incomplete until real implementation exists' "$ROOT_DIR/README.md"
grep -q 'A dependency review gate verifier skeleton that keeps dependency/supply-chain review documented as incomplete until review evidence exists' "$ROOT_DIR/README.md"
grep -q 'An external review gate verifier skeleton that keeps external/independent review readiness documented as incomplete until review readiness evidence exists' "$ROOT_DIR/README.md"
grep -q 'A release completion audit that records current v0.1-security-ready evidence as not complete while release gates remain incomplete' "$ROOT_DIR/README.md"
grep -q 'An update integrity gate verifier skeleton that keeps update/installer integrity documented as incomplete until release artifact and package verification evidence exists' "$ROOT_DIR/README.md"
grep -q 'An update/installer integrity template that records required artifact, signature/hash, downgrade, platform package, recovery, and classification fields while remaining classified as not update integrity evidence' "$ROOT_DIR/README.md"
grep -q 'A release signoff gate verifier skeleton that keeps release-candidate threat-model/release-copy signoff documented as incomplete until signoff evidence exists' "$ROOT_DIR/README.md"
grep -q 'A release-candidate signoff template that records required threat-model, public-copy alignment, release-gate evidence, blocker, and classification fields while remaining classified as not signoff evidence' "$ROOT_DIR/README.md"
grep -q 'A release gate evidence audit that records why template coverage is still not v0.1-security-ready 100% without real candidate-specific gate evidence' "$ROOT_DIR/README.md"
grep -q 'A release signing implementation plan that targets offline detached signatures while keeping release signing documented as unimplemented' "$ROOT_DIR/README.md"
grep -q 'A release signing dry-run verifier that uses disposable fixtures to reject missing signatures, stale checksums, stale detached signature markers, and unsigned artifacts without signing release artifacts' "$ROOT_DIR/README.md"
grep -q 'A release detached-signature fixture verifier that uses disposable OpenSSL RSA keys to validate checksum signature behavior without creating release keys or signing release artifacts' "$ROOT_DIR/README.md"
grep -q 'A release signing tooling decision gate that records the OpenSSL-compatible detached-signature path while keeping release signing documented as incomplete' "$ROOT_DIR/README.md"
grep -q 'A release signing ceremony dry-run record that defines key ceremony and command sequence placeholders without creating release keys or signing release artifacts' "$ROOT_DIR/README.md"
grep -q 'A release signing ceremony harness that executes the selected OpenSSL-compatible command sequence with disposable keys only' "$ROOT_DIR/README.md"
grep -q 'Release key ceremony evidence requirements that define the required real ceremony evidence package without creating release keys' "$ROOT_DIR/README.md"
grep -q 'Release artifact signing evidence requirements that define the required signed artifact evidence package without signing release artifacts' "$ROOT_DIR/README.md"
grep -q 'Release verification UX evidence requirements that define required user/reviewer verification evidence without verifying release artifacts' "$ROOT_DIR/README.md"
grep -q 'A release signing candidate evidence index that ties release-candidate signing evidence records together without recording release evidence' "$ROOT_DIR/README.md"
grep -q 'A release signing candidate evidence collection runbook that defines collection order and fail-closed rules without collecting release evidence' "$ROOT_DIR/README.md"
grep -q 'A reproducible/equivalent binary verification plan that records required evidence while keeping binary verification documented as incomplete' "$ROOT_DIR/README.md"
grep -q 'A binary manifest fixture verifier that rejects missing artifacts, extra artifacts, checksum mismatches, and build-input drift without verifying release artifacts' "$ROOT_DIR/README.md"
grep -q 'A binary verification input template that records required release-candidate fields while remaining classified as not verification evidence' "$ROOT_DIR/README.md"
grep -q 'A dependency review template that records required release-candidate lockfile, direct dependency, native dependency, deny/allow decision, and classification fields while remaining classified as not review evidence' "$ROOT_DIR/README.md"
grep -q 'An external review readiness template that records required release-candidate scope, review material, reviewer expectation, finding triage, blocker, and classification fields while remaining classified as not review readiness evidence' "$ROOT_DIR/README.md"
grep -q 'RELEASE_HARDENING.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_COMPLETION_AUDIT.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_SIGNING_PLAN.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_SIGNING_TOOLING_DECISION.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_SIGNING_CEREMONY_DRY_RUN.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_KEY_CEREMONY_REQUIREMENTS.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_ARTIFACT_SIGNING_REQUIREMENTS.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_VERIFICATION_UX_REQUIREMENTS.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_SIGNING_CANDIDATE_EVIDENCE_INDEX.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_SIGNING_CANDIDATE_EVIDENCE_RUNBOOK.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_BINARY_VERIFICATION_PLAN.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_BINARY_INPUT_TEMPLATE.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_DEPENDENCY_REVIEW_TEMPLATE.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_EXTERNAL_REVIEW_TEMPLATE.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_SIGNOFF_TEMPLATE.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_UPDATE_INTEGRITY_TEMPLATE.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_GATE_EVIDENCE_AUDIT.md' "$ROOT_DIR/README.md"
grep -q 'run_step "release artifact gate skeleton" scripts/verify_release_artifact_gates.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "dependency review gate skeleton" scripts/verify_dependency_review_gate.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "dependency review template" scripts/verify_dependency_review_template.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "external review gate skeleton" scripts/verify_external_review_gate.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "external review template" scripts/verify_external_review_template.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release completion audit" scripts/verify_release_completion_audit.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release gate evidence audit" scripts/verify_release_gate_evidence_audit.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "update integrity gate skeleton" scripts/verify_update_integrity_gate.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "update integrity template" scripts/verify_update_integrity_template.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signoff gate skeleton" scripts/verify_release_signoff_gate.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signoff template" scripts/verify_release_signoff_template.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signing plan" scripts/verify_release_signing_plan.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signing dry-run" scripts/verify_release_signing_dry_run.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release detached-signature fixture" scripts/verify_release_detached_signature_fixture.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signing tooling gate" scripts/verify_release_signing_tooling_gate.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signing ceremony dry-run" scripts/verify_release_signing_ceremony_dry_run.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signing ceremony harness" scripts/verify_release_signing_ceremony_harness.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release key ceremony requirements" scripts/verify_release_key_ceremony_requirements.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release artifact signing requirements" scripts/verify_release_artifact_signing_requirements.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release verification UX requirements" scripts/verify_release_verification_ux_requirements.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signing candidate evidence index" scripts/verify_release_signing_candidate_evidence_index.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signing candidate evidence runbook" scripts/verify_release_signing_candidate_evidence_runbook.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "binary verification plan" scripts/verify_binary_verification_plan.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "binary manifest fixture" scripts/verify_binary_manifest_fixture.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "binary input template" scripts/verify_binary_input_template.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'cargo run -q -- production preflight' "$ROOT_DIR/README.md"
grep -q 'read-only production skeleton preflight' "$ROOT_DIR/README.md"
grep -q 'without creating profiles, unlocking storage, bootstrapping transport, sending envelopes, receiving envelopes, or marking messaging ready' "$ROOT_DIR/README.md"
grep -q 'run_step "default build boundary checks" scripts/verify_default_boundary.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'cargo test -p another-dimension --test cli_hardening default_build' "$ROOT_DIR/scripts/verify_default_boundary.sh"
grep -q 'default_build_rejects_production_skeleton_commands' "$ROOT_DIR/apps/cli/tests/cli_hardening.rs"
grep -q 'default_build_prints_read_only_production_preflight_without_secrets' "$ROOT_DIR/apps/cli/tests/cli_hardening.rs"
grep -q 'default_build_rejects_production_unlock_with_redacted_error' "$ROOT_DIR/apps/cli/tests/cli_hardening.rs"
grep -q 'not ready for real communication' "$ROOT_DIR/SECURITY.md"
grep -q 'does not .*secure messenger release' "$ROOT_DIR/README.md"
grep -q 'high-risk transport policy/fail-closed behavior' "$ROOT_DIR/README.md"
grep -q 'entry to a bounded fail-closed skeleton, not usable network execution' "$ROOT_DIR/README.md"
grep -Fq 'network_execution_allowed()` means the pre-network blocker list is empty enough to enter the next bounded fail-closed skeleton' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'It does not mean sockets, Tor bootstrap, onion hosting, or envelope transfer are allowed' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'TransportRuntimePreflight::first_runtime_blocker()` may report the first fail-closed blocker without minting a `TransportRuntimeReady` token' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'TransportRuntimeState::fail_closed_blocker()` reports disabled state as `RuntimeNetworkDisabled` for status/reporting without starting a runtime' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'OnionEnvelopeTransport::integration_boundary_summary()` exposes the high-risk policy mode, runtime state, first fail-closed blocker, and a false envelope-I/O availability flag' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'TransportAdapterIntegrationBoundarySummary::envelope_io_available()` remains false until a separate implementation phase adds a real adapter' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'NetworkExperimentGateProposal::summary()` exposes bootstrap-only, manual feature gate, explicit operator consent, heavy isolated verification, isolated target cache, and no hosting/stream/envelope/messaging availability' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'The summary keeps onion hosting, stream I/O, envelope I/O, and usable messaging disabled even when `can_attempt_network_bootstrap()` is true' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'TRANSPORT_EXPERIMENT_RUNBOOK.md' "$ROOT_DIR/README.md"
grep -Fq 'TRANSPORT_EXPERIMENT_RUNBOOK.md` is the required operator runbook before using `--execute-network`' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq '`CARGO_TARGET_DIR` points to an isolated temporary target directory for this experiment' "$ROOT_DIR/TRANSPORT_EXPERIMENT_RUNBOOK.md"
grep -Fq 'CI, release builds, default verification, and unattended automation must not execute network bootstrap' "$ROOT_DIR/TRANSPORT_EXPERIMENT_RUNBOOK.md"
grep -Fq 'Delete the temporary `CARGO_TARGET_DIR`' "$ROOT_DIR/TRANSPORT_EXPERIMENT_RUNBOOK.md"
grep -Fq 'The rollback rule is deletion of local experiment artifacts plus preservation of fail-closed defaults' "$ROOT_DIR/TRANSPORT_EXPERIMENT_RUNBOOK.md"
grep -Fq 'Onion hosting, descriptor publication, stream I/O, envelope I/O, send/receive, offline mailbox behavior, and usable messaging remain out of scope' "$ROOT_DIR/TRANSPORT_EXPERIMENT_RUNBOOK.md"
grep -Fq 'Disabled manual bootstrap and lifecycle CLI summaries print `bootstrap_status=network-disabled` without exposing paths, profile names, endpoints, bridge lines, descriptors, or key material' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'Current public classes are `network-disabled`, `censorship-or-bridge-required`, `timeout-or-transient-network-failure`, `cancelled`, and `failed`; they are status reporting, not transport readiness' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -q 'pub fn first_runtime_blocker(self) -> Option<TransportRuntimeError>' "$ROOT_DIR/crates/transport/src/runtime_preflight.rs"
grep -q 'pub fn fail_closed_blocker(self) -> Option<TransportRuntimeError>' "$ROOT_DIR/crates/transport/src/runtime_preflight.rs"
grep -q 'pub struct NetworkExperimentGateSummary' "$ROOT_DIR/crates/transport/src/hosting_phase.rs"
grep -q 'pub fn can_attempt_network_bootstrap(self) -> bool' "$ROOT_DIR/crates/transport/src/hosting_phase.rs"
grep -q 'pub fn usable_messaging_enabled(self) -> bool' "$ROOT_DIR/crates/transport/src/hosting_phase.rs"
grep -q 'fn manual_bootstrap_status' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'bootstrap_status={}' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'bootstrap_status=network-disabled' "$ROOT_DIR/apps/cli/tests/cli_hardening.rs"
grep -q 'bootstrap_status_classification' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'network-disabled; censorship-or-bridge-required; timeout-or-transient-network-failure' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'does not expose raw Arti errors, paths, endpoints, bridge lines, descriptors, profile names, contact ids, or key material' "$ROOT_DIR/apps/desktop-tauri/README.md"
grep -q 'pub struct TransportAdapterIntegrationBoundarySummary' "$ROOT_DIR/crates/transport/src/transport_policy.rs"
grep -q 'pub fn integration_boundary_summary(&self) -> TransportAdapterIntegrationBoundarySummary' "$ROOT_DIR/crates/transport/src/transport_policy.rs"
grep -q 'pub fn envelope_io_available(self) -> bool' "$ROOT_DIR/crates/transport/src/transport_policy.rs"
grep -q 'pub struct TransportMessagePathBoundarySummary' "$ROOT_DIR/crates/transport/src/transport_policy.rs"
grep -q 'pub fn message_path_boundary_summary' "$ROOT_DIR/crates/transport/src/transport_policy.rs"
grep -q 'pub fn send_receive_available(self) -> bool' "$ROOT_DIR/crates/transport/src/transport_policy.rs"
grep -q 'pub fn offline_mailbox_available(self) -> bool' "$ROOT_DIR/crates/transport/src/transport_policy.rs"
grep -q 'pub fn usable_messaging_enabled(self) -> bool' "$ROOT_DIR/crates/transport/src/transport_policy.rs"
grep -Fq 'OnionEnvelopeTransport::message_path_boundary_summary()` exposes the route kind, policy decision, runtime state, fail-closed blocker, and false envelope-I/O, send/receive, offline-mailbox, and usable-messaging flags' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -Fq 'Production message path preparation must consult `TransportMessagePathBoundarySummary`' "$ROOT_DIR/TRANSPORT_DECISION.md"
grep -q 'It does not send messages, persist keys, bootstrap transport' "$ROOT_DIR/README.md"
grep -q 'RELEASE_VERIFICATION_UX_REQUIREMENTS.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_SIGNING_CANDIDATE_EVIDENCE_INDEX.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_SIGNING_CANDIDATE_EVIDENCE_RUNBOOK.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_verification_ux_requirements.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_signing_candidate_evidence_index.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_signing_candidate_evidence_runbook.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'Release verification UX evidence requirements' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'candidate evidence index' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'candidate evidence collection runbook' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'RELEASE_VERIFICATION_UX_REQUIREMENTS.md' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'RELEASE_SIGNING_CANDIDATE_EVIDENCE_INDEX.md' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'RELEASE_SIGNING_CANDIDATE_EVIDENCE_RUNBOOK.md' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'Requirement status: evidence requirements only, not signed artifact verification evidence' "$ROOT_DIR/RELEASE_VERIFICATION_UX_REQUIREMENTS.md"
grep -q 'does not verify real release artifacts' "$ROOT_DIR/RELEASE_VERIFICATION_UX_REQUIREMENTS.md"
grep -q 'Requirement status: candidate evidence index only, not release signing evidence' "$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_EVIDENCE_INDEX.md"
grep -q 'does not record candidate-specific release evidence' "$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_EVIDENCE_INDEX.md"
grep -q 'Requirement status: evidence collection runbook only, not candidate evidence' "$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_EVIDENCE_RUNBOOK.md"
grep -q 'does not collect candidate-specific release evidence' "$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_EVIDENCE_RUNBOOK.md"
test -x "$ROOT_DIR/scripts/verify_release_verification_ux_requirements.sh"
test -x "$ROOT_DIR/scripts/verify_release_signing_candidate_evidence_index.sh"
test -x "$ROOT_DIR/scripts/verify_release_signing_candidate_evidence_runbook.sh"
grep -q 'SQLCipher-backed storage spikes for `ADREC1` record containers' "$ROOT_DIR/README.md"
grep -q 'not a complete production encrypted local storage lifecycle' "$ROOT_DIR/README.md"
grep -q 'Complete production encrypted local storage lifecycle' "$ROOT_DIR/README.md"
grep -q 'Complete production encrypted local storage lifecycle' "$ROOT_DIR/SECURITY.md"
grep -q 'Replay rollback protection against encrypted database snapshot restore' "$ROOT_DIR/SECURITY.md"
grep -q 'Protocol/Library Shortlist' "$ROOT_DIR/CRYPTO_DECISION.md"
grep -q 'Current shortlist outcome' "$ROOT_DIR/CRYPTO_DECISION.md"
grep -q 'snow` Noise XX boundary' "$ROOT_DIR/CRYPTO_DECISION.md"
grep -q 'Direct `x25519-dalek` plus custom session logic' "$ROOT_DIR/CRYPTO_DECISION.md"
grep -q 'Do not claim production E2EE readiness' "$ROOT_DIR/CRYPTO_DECISION.md"
grep -q 'No Tauri production messaging command is exposed while the crypto/session boundary is incomplete' "$ROOT_DIR/CRYPTO_DECISION.md"
grep -Fq 'production_session_evaluation_summary()` exposes the bounded first evaluation result' "$ROOT_DIR/CRYPTO_DECISION.md"
grep -q 'ProductionSessionEvaluationSummary' "$ROOT_DIR/CRYPTO_DECISION.md"
grep -q 'pub struct ProductionSessionEvaluationSummary' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct ProductionSkeletonPreflightSummary' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub enum ProductionSkeletonConnector' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct ProductionSkeletonNextConnectorSelection' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct SessionDurableStateConnectorGate' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct SessionDurableStateConnectorHarness' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub enum SessionDurableStateAdapterRecordKind' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct SessionDurableStateAdapterRecordPolicy' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct SessionDurableStatePersistenceAdapterSkeleton' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct SessionDurableStateEncryptedRecordAdapter' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct SessionDurableStateAdapterNonReadinessGuard' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct SessionDurableStateStoreWriteStatusMirror' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub struct SessionDurableStateProductUnlockBlockerSummary' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn production_skeleton_preflight_summary' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn production_skeleton_next_connector_selection' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_durable_state_connector_gate' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_durable_state_connector_test_harness' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_durable_state_persistence_adapter_skeleton' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_durable_state_encrypted_record_adapter_spike' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_durable_state_adapter_non_readiness_guard' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_durable_state_store_write_status_mirror' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_durable_state_product_unlock_blocker_summary' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_durable_state_unlock_policy_handoff_summary' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_unlock_lock_command_design_gate' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_unlock_command_fail_closed' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_lock_lifecycle_status_mirror' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn session_unlock_redacted_error_taxonomy' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'ProductionSkeletonConnector::SessionProtocolAndStatePersistence' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_durable_state_connector_gate_keeps_runtime_closed' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_durable_state_connector_harness_applies_storage_policy' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_durable_state_persistence_adapter_skeleton_maps_record_policies' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_durable_state_encrypted_record_adapter_prepares_allowed_records_only' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_durable_state_adapter_non_readiness_guard_blocks_claims' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_durable_state_store_write_test_only_round_trips_prepared_record' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_durable_state_store_write_status_mirror_keeps_production_closed' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_durable_state_product_unlock_blocker_summary_keeps_unlock_closed' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_durable_state_unlock_policy_handoff_keeps_product_unlock_closed' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_unlock_lock_command_design_gate_keeps_commands_closed' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_unlock_command_fail_closed_skeleton_rejects_all_requests' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_lock_lifecycle_status_mirror_keeps_lock_runtime_closed' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'session_unlock_redacted_error_taxonomy_hides_sensitive_details' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'test_only_put_prepared_record' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn production_messaging_ready(self) -> bool' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn production_session_evaluation_summary' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn production_e2ee_ready(self) -> bool' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'pub fn tauri_production_messaging_command_ready(self) -> bool' "$ROOT_DIR/crates/core/src/lib.rs"
grep -q 'Shortlist Alignment' "$ROOT_DIR/SESSION_DECISION.md"
grep -q 'existing `snow`-backed Noise XX smoke boundary' "$ROOT_DIR/SESSION_DECISION.md"
grep -q 'This alignment does not claim production E2EE readiness' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'production_session_evaluation_summary()` is the current public-safe harness for this evaluation path' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_durable_state_connector_gate()` is the first read-only connector-gate draft for durable session state' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_durable_state_connector_test_harness()` applies that gate to the storage policy without implementing the connector' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_durable_state_persistence_adapter_skeleton()` is the current adapter boundary before implementation' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_durable_state_encrypted_record_adapter_spike()` is the first narrow adapter spike' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_durable_state_adapter_non_readiness_guard()` keeps the adapter spike from being interpreted as readiness' "$ROOT_DIR/SESSION_DECISION.md"
grep -q 'The first store-write check for this adapter is test-only' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_durable_state_store_write_status_mirror()` reports that the store-write coverage is test-only' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_durable_state_product_unlock_blocker_summary()` records the current product unlock blockers' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_durable_state_unlock_policy_handoff_summary()` links the session durable-state blocker summary to the storage unlock policy' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_unlock_lock_command_design_gate()` records the minimum command semantics before any product unlock/lock implementation' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_unlock_command_fail_closed()` is the first command-shape skeleton for future product unlock' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_lock_lifecycle_status_mirror()` records the lock lifecycle requirements that future unlock work must satisfy' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'session_unlock_redacted_error_taxonomy()` defines safe unlock failure categories for future CLI/Tauri copy' "$ROOT_DIR/SESSION_DECISION.md"
grep -Fq 'Default CLI `production unlock` currently uses that taxonomy only as a fail-closed boundary rejection' "$ROOT_DIR/SESSION_DECISION.md"
grep -q 'does not have a complete production encrypted local storage lifecycle today' "$ROOT_DIR/STORAGE_DECISION.md"
grep -q 'ADREC1` spike' "$ROOT_DIR/STORAGE_DECISION.md"
grep -q 'ADREC1` is a container format, not an encryption algorithm' "$ROOT_DIR/STORAGE_DECISION.md"
grep -q 'Public docs should use "storage guardrails", "storage boundary", or "SQLCipher-backed storage spike"' "$ROOT_DIR/STORAGE_DECISION.md"
grep -q 'Public product language must therefore avoid claims like "persistent replay protection" or "rollback-proof local state."' "$ROOT_DIR/STORAGE_DECISION.md"
grep -q 'storage_backend_integration_boundary_summary()` exposes these guardrails as integration status' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'production_message_storage_boundary_summary()` exposes the current production message-path storage status' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_durable_state_connector_gate()` records the current cross-core session persistence contract' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_durable_state_connector_test_harness()` verifies that contract against storage policy' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_durable_state_persistence_adapter_skeleton()` maps the allowed durable-state record policies' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_durable_state_encrypted_record_adapter_spike()` prepares allowed sealed records' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_durable_state_adapter_non_readiness_guard()` records that sealed-record preparation does not provide rollback protection' "$ROOT_DIR/STORAGE_DECISION.md"
grep -q 'session_durable_state_store_write_test_only_round_trips_prepared_record' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_durable_state_store_write_status_mirror()` exposes that store-write coverage as test-only' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_durable_state_product_unlock_blocker_summary()` exposes product unlock blockers' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_durable_state_unlock_policy_handoff_summary()` confirms that the session durable-state blocker path is aligned with the storage unlock policy' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_unlock_lock_command_design_gate()` captures pre-implementation command requirements' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_unlock_command_fail_closed()` gives future unlock callers a stable disabled result shape' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_lock_lifecycle_status_mirror()` mirrors explicit lock and idle auto-lock requirements' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'session_unlock_redacted_error_taxonomy()` provides safe categories for future unlock failures' "$ROOT_DIR/STORAGE_DECISION.md"
grep -Fq 'CLI `production unlock` currently exercises only the redacted disabled taxonomy' "$ROOT_DIR/STORAGE_DECISION.md"
grep -q 'pub struct StorageBackendIntegrationBoundarySummary' "$ROOT_DIR/crates/storage/src/lib.rs"
grep -q 'pub fn storage_backend_integration_boundary_summary' "$ROOT_DIR/crates/storage/src/lib.rs"
grep -q 'pub struct ProductionMessageStorageBoundarySummary' "$ROOT_DIR/crates/storage/src/lib.rs"
grep -q 'pub fn production_message_storage_boundary_summary' "$ROOT_DIR/crates/storage/src/lib.rs"
grep -q 'pub fn durable_session_transport_persistence_allowed(self) -> bool' "$ROOT_DIR/crates/storage/src/lib.rs"
grep -q 'pub fn production_key_management_ready(self) -> bool' "$ROOT_DIR/crates/storage/src/lib.rs"
grep -q 'pub fn secure_deletion_from_media(self) -> bool' "$ROOT_DIR/crates/storage/src/lib.rs"
grep -Fq 'Here, "production" means the default non-`dev-insecure` build boundary, not deployable security' "$ROOT_DIR/README.md"
grep -q 'perform network I/O, unlock local storage' "$ROOT_DIR/README.md"
grep -q 'COMPONENT_BOUNDARIES.md' "$ROOT_DIR/README.md"
grep -q 'production preflight, transport, network-execution, storage, and verification boundary state through `prototype_status`' "$ROOT_DIR/README.md"
grep -q 'Security-Ready Component Boundaries' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'not a secure messenger release today' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'boundary map, not an approval to ship production communication' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'Default builds do not expose usable profile, pairing, messaging, storage unlock, Tor bootstrap, onion hosting, stream I/O, or production message commands' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'Default CLI hardening rejects production skeleton commands for profile, pairing, messaging, storage unlock, transport bootstrap, and transport send/receive' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'ProductionSkeletonPreflightSummary' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'Default CLI `production preflight` prints that aggregate preflight status as read-only redacted copy' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'Tauri `prototype_status` mirrors the production preflight blockers as static read-only copy' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'ProductionSkeletonNextConnectorSelection' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'session protocol and durable-state gate as the next connector candidate without opening runtime execution' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionDurableStateConnectorGate' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'Noise transport state remains in-memory only and runtime execution stays closed' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionDurableStateConnectorHarness' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'private-key and replay records are accepted only as encrypted records, and session transport persistence is rejected' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionDurableStatePersistenceAdapterSkeleton' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'maps those durable-state kinds to storage policy without implementing storage unlock, transport I/O, runtime messaging, or durable Noise transport persistence' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionDurableStateEncryptedRecordAdapter' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'prepares allowed sealed durable-state records but does not write them to a store' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionDurableStateAdapterNonReadinessGuard' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'keeps rollback protection, store writes, durable session persistence, production E2EE readiness, durable Noise transport persistence, and runtime messaging false' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'The session durable-state store-write spike is test-only' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'round-trips a prepared sealed record through `SqlCipherRecordStore` while preserving the production non-readiness guard' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionDurableStateStoreWriteStatusMirror' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'reports that store-write coverage is test-only and keeps production store write, unlock command, durable session persistence, rollback protection, and runtime messaging disabled' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionDurableStateProductUnlockBlockerSummary' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'product unlock remains blocked by key wrapping, backup exclusion, rollback protection, and durable session lifecycle decisions' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionDurableStateUnlockPolicyHandoffSummary' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'high-risk mode requires passphrase input, OS-keystore-only unlock is rejected, and product unlock remains disabled' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionUnlockLockCommandDesignGate' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'explicit lock, idle auto-lock, redacted unlock errors, passphrase-first high-risk policy, and disabled product commands' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'session_unlock_command_fail_closed()' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'always returns a redacted disabled result without opening storage, writing session records, exposing key material, or enabling runtime messaging' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionLockLifecycleStatusMirror' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'explicit lock and idle auto-lock requirements while keeping storage unlocked state, product lock command, key erasure claim, and runtime messaging disabled' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'SessionUnlockRedactedErrorTaxonomy' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'without exposing raw storage errors, OS keychain errors, paths, identifiers, key material, or passphrase detail' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'Default CLI `production unlock` is a boundary rejection only' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'returns the redacted disabled taxonomy and does not open storage, write session records, expose key material, or enable runtime messaging' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'Tauri `prototype_status` mirrors the CLI production unlock rejection as static copy only' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'does not add a Tauri unlock command or execute the CLI' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'mirrors session durable-state and unlock-policy blockers as static read-only copy without executing unlock, writing session records, or opening runtime messaging' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_HARDENING.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_COMPLETION_AUDIT.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_SIGNING_PLAN.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_SIGNING_TOOLING_DECISION.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_SIGNING_CEREMONY_DRY_RUN.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_KEY_CEREMONY_REQUIREMENTS.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_ARTIFACT_SIGNING_REQUIREMENTS.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_BINARY_VERIFICATION_PLAN.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_BINARY_INPUT_TEMPLATE.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_DEPENDENCY_REVIEW_TEMPLATE.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_EXTERNAL_REVIEW_TEMPLATE.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_SIGNOFF_TEMPLATE.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_UPDATE_INTEGRITY_TEMPLATE.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'RELEASE_GATE_EVIDENCE_AUDIT.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_artifact_gates.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_dependency_review_gate.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_dependency_review_template.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_external_review_gate.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_external_review_template.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_completion_audit.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_gate_evidence_audit.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'scripts/verify_update_integrity_gate.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_update_integrity_template.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_signoff_gate.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_signoff_template.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_signing_plan.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_signing_dry_run.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_detached_signature_fixture.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_signing_tooling_gate.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_signing_ceremony_dry_run.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_signing_ceremony_harness.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_key_ceremony_requirements.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_release_artifact_signing_requirements.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_binary_verification_plan.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_binary_manifest_fixture.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'scripts/verify_binary_input_template.sh' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'no release signing workflow, signed artifact verification, reproducible/equivalent verification evidence, dependency review evidence, release-candidate signoff evidence, external review readiness evidence, or update/installer integrity evidence exists' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'ProductionSessionEvaluationSummary' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'TransportMessagePathBoundarySummary' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'ProductionMessageStorageBoundarySummary' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'replace Tauri CLI-wrapper demo commands with Rust-owned runtime commands only after the above boundaries have guardrails' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'Any claim that this project is generally safer than Signal' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'keep the first evaluation path narrowed to the existing `snow` Noise XX synchronous boundary' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'COMPONENT_BOUNDARIES.md' "$ROOT_DIR/SECURITY.md"
grep -q 'warning: production self-test is not a secure messenger release' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'production self-test performs no network I/O and opens no local storage' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'production boundary self-test passed' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'production session candidate:' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'production session non-readiness:' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'production preflight is read-only and performs no messaging, storage unlock, or transport I/O' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'production unlock is disabled: unlock_error=' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'production skeleton preflight summary:' "$ROOT_DIR/apps/cli/src/main.rs"
grep -q 'The self-test prints a redacted production-session summary' "$ROOT_DIR/README.md"
grep -q 'durable session persistence, Tauri production messaging commands, and usable async messaging false' "$ROOT_DIR/README.md"
grep -q 'production_session_status: "snow Noise XX synchronous evaluation boundary only"' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'production_self_test_status: "CLI production boundary self-test only"' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'production_session_non_readiness:' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'production_preflight_status: "read-only production skeleton blockers copy"' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'production_preflight_blockers:' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'session_durable_state_status: "read-only durable-state candidate blockers copy"' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'session_unlock_policy_status: "high-risk passphrase required OS-keystore-only rejected"' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'session_unlock_non_readiness:' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'session_unlock_cli_rejection_status: "redacted product-unlock-disabled boundary copy"' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'session_unlock_cli_rejection_flags:' "$ROOT_DIR/apps/desktop-tauri/src-tauri/src/status.rs"
grep -q 'Production session limits' "$ROOT_DIR/apps/desktop-tauri/index.html"
grep -q 'Production preflight' "$ROOT_DIR/apps/desktop-tauri/index.html"
grep -q 'Preflight blockers' "$ROOT_DIR/apps/desktop-tauri/index.html"
grep -q 'Session durable state' "$ROOT_DIR/apps/desktop-tauri/index.html"
grep -q 'Session unlock policy' "$ROOT_DIR/apps/desktop-tauri/index.html"
grep -q 'Session unlock limits' "$ROOT_DIR/apps/desktop-tauri/index.html"
grep -q 'Session unlock rejection' "$ROOT_DIR/apps/desktop-tauri/index.html"
grep -q 'Unlock rejection flags' "$ROOT_DIR/apps/desktop-tauri/index.html"
grep -q 'production-session limits copy' "$ROOT_DIR/apps/desktop-tauri/README.md"
grep -q 'session durable-state status is static blocker copy' "$ROOT_DIR/apps/desktop-tauri/README.md"
grep -q 'session unlock-policy status mirrors the high-risk passphrase-required and OS-keystore-only-rejected policy as static copy' "$ROOT_DIR/apps/desktop-tauri/README.md"
grep -q 'session unlock-rejection status mirrors the CLI `production unlock` redacted disabled taxonomy as static copy' "$ROOT_DIR/apps/desktop-tauri/README.md"
grep -q 'production-preflight' "$ROOT_DIR/apps/desktop-tauri/README.md"
grep -q 'mirrors the CLI `production preflight` blockers as static read-only copy' "$ROOT_DIR/apps/desktop-tauri/README.md"
grep -q 'Release signing or reproducible builds' "$ROOT_DIR/README.md"
grep -q 'Release Hardening Gap Inventory' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'Release signing | No release signing workflow or signed artifact verification exists; a pre-implementation signing plan, tooling decision, ceremony dry-run record, real key ceremony requirements, artifact signing requirements, Release verification UX evidence requirements, candidate evidence index, candidate evidence collection runbook, ceremony command harness, dry-run verifier, and disposable detached-signature fixture exist' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'Reproducible or equivalent verification | No reproducible build evidence or equivalent binary verification evidence exists; a pre-implementation verification plan, input template, and manifest fixture verifier exist' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'Dependency and supply-chain review' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'External security review' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'does not satisfy the release gates' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_artifact_gates.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'fails if public copy starts claiming those gates are ready before implementation' "$ROOT_DIR/RELEASE_HARDENING.md"
test -x "$ROOT_DIR/scripts/verify_release_artifact_gates.sh"
grep -q 'Dependency Review Policy Skeleton' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'No dependency review evidence is recorded yet' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'reviewed lockfiles, direct dependency changes, native/system dependencies, and denied or accepted risk decisions' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_dependency_review_gate.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
test -x "$ROOT_DIR/scripts/verify_dependency_review_gate.sh"
grep -q 'External Review Readiness Checklist Skeleton' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'No external or independent review readiness evidence is recorded yet' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'reviewed scope, reviewer independence expectations, review materials, finding triage, and release-blocking unresolved risks' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_external_review_gate.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
test -x "$ROOT_DIR/scripts/verify_external_review_gate.sh"
grep -q 'RELEASE_EXTERNAL_REVIEW_TEMPLATE.md' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'not-review-readiness-evidence' "$ROOT_DIR/RELEASE_EXTERNAL_REVIEW_TEMPLATE.md"
grep -q 'scripts/verify_external_review_template.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_external_review_template.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_external_review_template.sh"
grep -q 'Release completion audit' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'RELEASE_COMPLETION_AUDIT.md' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'Audit verdict: not complete' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
grep -q 'Current evidence does not prove v0.1-security-ready 100%' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
grep -q 'Update and installer integrity' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
grep -q 'scripts/verify_release_completion_audit.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
test -x "$ROOT_DIR/scripts/verify_release_completion_audit.sh"
grep -q 'Audit verdict: release gate evidence incomplete' "$ROOT_DIR/RELEASE_GATE_EVIDENCE_AUDIT.md"
grep -q '99% planning/readiness-scaffold interpretation' "$ROOT_DIR/RELEASE_GATE_EVIDENCE_AUDIT.md"
grep -q 'cannot move the project to a 100% security-ready claim' "$ROOT_DIR/RELEASE_GATE_EVIDENCE_AUDIT.md"
grep -q 'scripts/verify_release_gate_evidence_audit.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_release_gate_evidence_audit.sh"
grep -q 'Update and Installer Integrity Checklist Skeleton' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'No update or installer integrity evidence is recorded yet' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'artifact formats, signature/hash verification, downgrade or rollback handling, platform package integrity, and recovery behavior for failed updates' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_update_integrity_gate.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_update_integrity_gate.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_update_integrity_gate.sh"
grep -q 'RELEASE_UPDATE_INTEGRITY_TEMPLATE.md' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'not-update-integrity-evidence' "$ROOT_DIR/RELEASE_UPDATE_INTEGRITY_TEMPLATE.md"
grep -q 'scripts/verify_update_integrity_template.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_update_integrity_template.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_update_integrity_template.sh"
grep -q 'Release-Candidate Threat Model and Copy Signoff Skeleton' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'No release-candidate threat-model or release-copy signoff evidence is recorded yet' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'exact candidate commit, threat model revision, non-goals, known risks, user-facing safety copy, and unresolved release blockers' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_signoff_gate.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_signoff_gate.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_release_signoff_gate.sh"
grep -q 'RELEASE_SIGNOFF_TEMPLATE.md' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'not-signoff-evidence' "$ROOT_DIR/RELEASE_SIGNOFF_TEMPLATE.md"
grep -q 'scripts/verify_release_signoff_template.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_signoff_template.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_release_signoff_template.sh"
grep -q 'RELEASE_SIGNING_PLAN.md' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'Another Dimension Chat does not have release signing today' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'pre-implementation signing design, not signed artifact evidence and not release approval' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'SHA256SUMS' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'RELEASE_SIGNING_TOOLING_DECISION.md' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'scripts/verify_release_signing_dry_run.sh' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'The dry-run marker is not a real release signature' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'scripts/verify_release_signing_plan.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_signing_plan.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_release_signing_plan.sh"
grep -q 'scripts/verify_release_signing_dry_run.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_signing_dry_run.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
grep -q 'missing signatures, stale checksums, stale detached signature markers, and unsigned artifacts' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
test -x "$ROOT_DIR/scripts/verify_release_signing_dry_run.sh"
grep -q 'scripts/verify_release_detached_signature_fixture.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_detached_signature_fixture.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
grep -q 'scripts/verify_release_detached_signature_fixture.sh' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'disposable OpenSSL RSA fixture keys' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
test -x "$ROOT_DIR/scripts/verify_release_detached_signature_fixture.sh"
grep -q 'Release Signing Tooling Decision Gate' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'Decision status: tooling path selected, signing implementation incomplete' "$ROOT_DIR/RELEASE_SIGNING_TOOLING_DECISION.md"
grep -q 'OpenSSL-compatible detached signatures over `SHA256SUMS`' "$ROOT_DIR/RELEASE_SIGNING_TOOLING_DECISION.md"
grep -q 'does not create a release signing key, sign release artifacts, or approve release signing readiness' "$ROOT_DIR/RELEASE_SIGNING_TOOLING_DECISION.md"
grep -q 'RELEASE_SIGNING_CEREMONY_DRY_RUN.md' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'dry-run procedure only, not release signing evidence' "$ROOT_DIR/RELEASE_SIGNING_CEREMONY_DRY_RUN.md"
grep -q 'scripts/verify_release_signing_ceremony_dry_run.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_signing_ceremony_dry_run.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_release_signing_ceremony_dry_run.sh"
grep -q 'scripts/verify_release_signing_ceremony_harness.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_signing_ceremony_harness.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_release_signing_ceremony_harness.sh"
grep -q 'RELEASE_KEY_CEREMONY_REQUIREMENTS.md' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'evidence requirements only, not a real key ceremony' "$ROOT_DIR/RELEASE_KEY_CEREMONY_REQUIREMENTS.md"
grep -q 'scripts/verify_release_key_ceremony_requirements.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_key_ceremony_requirements.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_release_key_ceremony_requirements.sh"
grep -q 'RELEASE_ARTIFACT_SIGNING_REQUIREMENTS.md' "$ROOT_DIR/RELEASE_SIGNING_PLAN.md"
grep -q 'evidence requirements only, not artifact signing evidence' "$ROOT_DIR/RELEASE_ARTIFACT_SIGNING_REQUIREMENTS.md"
grep -q 'scripts/verify_release_artifact_signing_requirements.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_artifact_signing_requirements.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_release_artifact_signing_requirements.sh"
grep -q 'scripts/verify_release_signing_tooling_gate.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_release_signing_tooling_gate.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_release_signing_tooling_gate.sh"
grep -q 'RELEASE_BINARY_VERIFICATION_PLAN.md' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'Another Dimension Chat does not have reproducible builds or equivalent binary verification today' "$ROOT_DIR/RELEASE_BINARY_VERIFICATION_PLAN.md"
grep -q 'pre-implementation verification design, not reproducible build evidence and not release approval' "$ROOT_DIR/RELEASE_BINARY_VERIFICATION_PLAN.md"
grep -q 'scripts/verify_binary_verification_plan.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_binary_verification_plan.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_binary_verification_plan.sh"
grep -q 'scripts/verify_binary_manifest_fixture.sh' "$ROOT_DIR/RELEASE_BINARY_VERIFICATION_PLAN.md"
grep -q 'scripts/verify_binary_manifest_fixture.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_binary_manifest_fixture.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
grep -q 'missing artifacts, extra artifacts, checksum mismatches, and unrecorded build-input changes' "$ROOT_DIR/RELEASE_BINARY_VERIFICATION_PLAN.md"
test -x "$ROOT_DIR/scripts/verify_binary_manifest_fixture.sh"
grep -q 'RELEASE_BINARY_INPUT_TEMPLATE.md' "$ROOT_DIR/RELEASE_BINARY_VERIFICATION_PLAN.md"
grep -q 'RELEASE_BINARY_INPUT_TEMPLATE.md' "$ROOT_DIR/COMPONENT_BOUNDARIES.md"
grep -q 'not-verification-evidence' "$ROOT_DIR/RELEASE_BINARY_INPUT_TEMPLATE.md"
grep -q 'scripts/verify_binary_input_template.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_binary_input_template.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_binary_input_template.sh"
grep -q 'RELEASE_DEPENDENCY_REVIEW_TEMPLATE.md' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'not-review-evidence' "$ROOT_DIR/RELEASE_DEPENDENCY_REVIEW_TEMPLATE.md"
grep -q 'scripts/verify_dependency_review_template.sh' "$ROOT_DIR/RELEASE_HARDENING.md"
grep -q 'scripts/verify_dependency_review_template.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"
test -x "$ROOT_DIR/scripts/verify_dependency_review_template.sh"

if git -C "$ROOT_DIR" ls-files | grep -E '^docs/' >/dev/null; then
  echo "private docs must not be tracked" >&2
  exit 1
fi

if grep -R -n -E 'ready for real communication|secure messenger release|production-grade confidentiality|production transport adapter implementation' \
  "$ROOT_DIR/README.md" \
  "$ROOT_DIR/apps/desktop-tauri/README.md" \
  "$ROOT_DIR/apps/desktop-tauri/package.json" \
  "$ROOT_DIR/apps/desktop-tauri/src-tauri/tauri.conf.json" \
  | grep -v 'not ready for real communication' \
  | grep -v 'not a secure messenger release' \
  | grep -v 'does not .*secure messenger release' \
  | grep -v 'does not provide production-grade confidentiality' \
  | grep -v 'Production transport adapter implementation' >/dev/null; then
  echo "public release surface contains an unsupported security/readiness claim" >&2
  exit 1
fi

printf 'release hygiene static verification passed\n'
