#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_GUARD_AUDIT_COVERAGE_CHECKS.md"
AUDIT="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_GUARD_AUDIT.md"
GUARD="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_NON_CLAIM_GUARD.md"
AUDIT_VERIFIER="$ROOT_DIR/scripts/verify_release_signing_candidate_signed_artifact_verification_guard_audit.sh"

test -f "$DOC"

grep -q 'Coverage-check status: signed-artifact verification guard audit coverage checks only, not signed artifact verification evidence' "$DOC"
grep -q 'RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_GUARD_AUDIT.md' "$DOC"
grep -q 'RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_NON_CLAIM_GUARD.md' "$DOC"
grep -q 'not release-candidate evidence, signed artifact verification, detached signature verification evidence, artifact authenticity proof, release signing approval, or release approval' "$DOC"
grep -q 'Audit status: signed-artifact verification guard coverage audit only, not signed artifact verification evidence' "$DOC"
grep -q 'Guard status: signed-artifact verification non-claim guard only, not signed artifact verification evidence' "$DOC"
grep -q 'Signed-artifact verification coverage remains fixture-only' "$DOC"
grep -q 'fixture signed-artifact verification coverage is not signed artifact verification evidence' "$DOC"
grep -q 'no detached signature verification evidence exists' "$DOC"
grep -q 'no artifact authenticity proof exists' "$DOC"
grep -q 'not release-ready or v0.1-security-ready' "$DOC"
grep -q 'real release artifact hashes have been compared against `SHA256SUMS`' "$DOC"
grep -q 'detached signatures have been verified for a release candidate' "$DOC"
grep -q 'signed artifact verification has passed' "$DOC"
grep -q 'artifact authenticity has been proven' "$DOC"
grep -q 'candidate evidence has been collected' "$DOC"
grep -q 'release signing has been approved' "$DOC"
grep -q 'a release candidate has been approved' "$DOC"
grep -q 'release hardening gates have passed' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not signed artifact verification evidence' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not detached signature verification evidence' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not artifact authenticity proof' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not release signing approval' "$DOC"
grep -q 'Signed-artifact verification guard coverage is not release approval' "$DOC"
grep -q 'Guard audit coverage checks are not signed artifact verification evidence' "$DOC"
grep -q 'Guard audit coverage checks are not detached signature verification evidence' "$DOC"
grep -q 'Guard audit coverage checks are not artifact authenticity proof' "$DOC"
grep -q 'Guard audit coverage checks are not release signing approval' "$DOC"
grep -q 'Guard audit coverage checks are not release approval' "$DOC"
grep -q 'do not verify detached signatures' "$DOC"
grep -q 'do not prove artifact authenticity' "$DOC"
grep -q 'do not make Another Dimension Chat release-ready or v0.1-security-ready' "$DOC"

grep -q 'Audit status: signed-artifact verification guard coverage audit only, not signed artifact verification evidence' "$AUDIT"
grep -q 'fixture signed-artifact verification coverage is not signed artifact verification evidence' "$AUDIT"
grep -q 'Signed-artifact verification guard coverage is not release approval' "$AUDIT"
grep -q 'Guard status: signed-artifact verification non-claim guard only, not signed artifact verification evidence' "$GUARD"
grep -q 'Signed-artifact verification coverage remains fixture-only' "$GUARD"
grep -q 'fixture signed-artifact verification coverage is not signed artifact verification evidence' "$GUARD"
grep -q 'no detached signature verification evidence exists' "$GUARD"
grep -q 'no artifact authenticity proof exists' "$GUARD"

grep -q 'RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_GUARD_AUDIT.md' "$ROOT_DIR/README.md"
grep -q 'RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_GUARD_AUDIT_COVERAGE_CHECKS.md' "$ROOT_DIR/README.md"
grep -q 'run_step "release signing candidate signed-artifact verification guard audit" scripts/verify_release_signing_candidate_signed_artifact_verification_guard_audit.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'run_step "release signing candidate signed-artifact verification guard audit coverage checks" scripts/verify_release_signing_candidate_signed_artifact_verification_guard_audit_coverage_checks.sh' "$ROOT_DIR/scripts/verify_all.sh"
grep -q 'scripts/verify_release_signing_candidate_signed_artifact_verification_guard_audit_coverage_checks.sh' "$ROOT_DIR/RELEASE_COMPLETION_AUDIT.md"

printf 'release signing candidate signed-artifact verification guard audit coverage checks remain coverage-only\n'
