#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_SIGNED_ARTIFACT_VERIFICATION_FIXTURE_AUDIT.md"
FIXTURE="$ROOT_DIR/scripts/verify_release_signing_candidate_signed_artifact_verification_fixture.sh"

grep -q 'Audit status: signed-artifact verification fixture coverage audit only, not signed artifact verification evidence' "$DOC"
grep -q 'CANDIDATE_EVIDENCE_INDEX' "$DOC"
grep -q 'ARTIFACT_MANIFEST' "$DOC"
grep -q 'SHA256SUMS' "$DOC"
grep -q 'SHA256SUMS.sig' "$DOC"
grep -q 'public_key_fingerprint' "$DOC"
grep -q 'candidate_commit' "$DOC"
grep -q 'release_tag' "$DOC"
grep -q 'artifact_manifest' "$DOC"
grep -q 'artifact_manifest_sha256' "$DOC"
grep -q 'sha256sums_path' "$DOC"
grep -q 'sha256sums_sha256' "$DOC"
grep -q 'sha256sums_sig_path' "$DOC"
grep -q 'sha256sums_sig_sha256' "$DOC"
grep -q 'key_ceremony_record' "$DOC"
grep -q 'signature_verification_command' "$DOC"
grep -q 'signature_verification_transcript' "$DOC"
grep -q 'artifact_hash_verification_command' "$DOC"
grep -q 'artifact_hash_verification_transcript' "$DOC"
grep -q 'failure_transcript' "$DOC"
grep -q 'reviewer' "$DOC"
grep -q 'review_timestamp' "$DOC"
grep -q 'classification' "$DOC"
grep -q 'blocker_status' "$DOC"
grep -q 'fixture-filled-not-release-evidence' "$DOC"
grep -q 'missing signed-artifact verification record' "$DOC"
grep -q 'missing `SHA256SUMS`' "$DOC"
grep -q 'missing `SHA256SUMS.sig`' "$DOC"
grep -q 'missing public key fingerprint' "$DOC"
grep -q 'mismatched record candidate commit' "$DOC"
grep -q 'mismatched record release tag' "$DOC"
grep -q 'mismatched record artifact manifest' "$DOC"
grep -q 'mismatched record artifact manifest digest' "$DOC"
grep -q 'stale `SHA256SUMS` digest' "$DOC"
grep -q 'stale `SHA256SUMS.sig` digest' "$DOC"
grep -q 'key ceremony fingerprint mismatch' "$DOC"
grep -q 'missing signature verification transcript' "$DOC"
grep -q 'missing artifact hash verification transcript' "$DOC"
grep -q 'missing failure transcript' "$DOC"
grep -q 'template-only evidence' "$DOC"
grep -q 'placeholder evidence' "$DOC"
grep -q 'empty blocker status' "$DOC"
grep -q 'does not sign release artifacts' "$DOC"
grep -q 'does not checksum real release artifacts' "$DOC"
grep -q 'does not compare real release artifact hashes against `SHA256SUMS`' "$DOC"
grep -q 'does not verify detached signatures' "$DOC"
grep -q 'does not prove artifact authenticity' "$DOC"
grep -q 'does not collect candidate-specific release evidence' "$DOC"
grep -q 'does not approve release signing' "$DOC"
grep -q 'does not approve a release candidate or release' "$DOC"
grep -q 'does not make Another Dimension Chat release-ready or v0.1-security-ready' "$DOC"
grep -q 'Signed-artifact verification fixture coverage is not signed artifact verification' "$DOC"
grep -q 'Signed-artifact verification fixture coverage is not artifact authenticity proof' "$DOC"
grep -q 'Signed-artifact verification fixture coverage is not release signing approval' "$DOC"
grep -q 'Signed-artifact verification fixture coverage is not release approval' "$DOC"

grep -q 'CANDIDATE_EVIDENCE_INDEX' "$FIXTURE"
grep -q 'ARTIFACT_MANIFEST' "$FIXTURE"
grep -q 'SHA256SUMS' "$FIXTURE"
grep -q 'SHA256SUMS.sig' "$FIXTURE"
grep -q 'public_key_fingerprint' "$FIXTURE"
grep -q 'candidate_commit' "$FIXTURE"
grep -q 'release_tag' "$FIXTURE"
grep -q 'artifact_manifest_sha256' "$FIXTURE"
grep -q 'sha256sums_sha256' "$FIXTURE"
grep -q 'sha256sums_sig_sha256' "$FIXTURE"
grep -q 'signature_verification_transcript' "$FIXTURE"
grep -q 'artifact_hash_verification_transcript' "$FIXTURE"
grep -q 'failure_transcript' "$FIXTURE"
grep -q 'blocker_status' "$FIXTURE"
grep -q 'fixture-filled-not-release-evidence' "$FIXTURE"
grep -q 'expect_rejects "missing signed-artifact verification record"' "$FIXTURE"
grep -q 'expect_rejects "missing SHA256SUMS"' "$FIXTURE"
grep -q 'expect_rejects "missing SHA256SUMS.sig"' "$FIXTURE"
grep -q 'expect_rejects "missing public key fingerprint"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record candidate commit"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record release tag"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record artifact manifest"' "$FIXTURE"
grep -q 'expect_rejects "mismatched record artifact manifest digest"' "$FIXTURE"
grep -q 'expect_rejects "stale SHA256SUMS digest"' "$FIXTURE"
grep -q 'expect_rejects "stale SHA256SUMS.sig digest"' "$FIXTURE"
grep -q 'expect_rejects "key ceremony fingerprint mismatch"' "$FIXTURE"
grep -q 'expect_rejects "missing signature verification transcript"' "$FIXTURE"
grep -q 'expect_rejects "missing artifact hash verification transcript"' "$FIXTURE"
grep -q 'expect_rejects "missing failure transcript"' "$FIXTURE"
grep -q 'expect_rejects "template-only evidence"' "$FIXTURE"
grep -q 'expect_rejects "placeholder evidence"' "$FIXTURE"
grep -q 'expect_rejects "empty blocker status"' "$FIXTURE"

printf 'release signing candidate signed-artifact verification fixture audit confirms fixture coverage and limits\n'
