#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC="$ROOT_DIR/RELEASE_SIGNING_CANDIDATE_EVIDENCE_PACKAGE_CHECKSUM_AUDIT.md"
PACKAGE_FIXTURE="$ROOT_DIR/scripts/verify_release_signing_candidate_evidence_fixture.sh"
MANIFEST_FIXTURE="$ROOT_DIR/scripts/verify_release_signing_candidate_manifest_consistency_fixture.sh"

grep -q 'Audit status: evidence package checksum coverage audit only, not candidate evidence' "$DOC"
grep -q 'artifact_manifest' "$DOC"
grep -q 'ARTIFACT_MANIFEST' "$DOC"
grep -q 'artifact_manifest_sha256' "$DOC"
grep -q 'SHA-256 digest' "$DOC"
grep -q 'mismatched artifact manifest' "$DOC"
grep -q 'missing artifact manifest' "$DOC"
grep -q 'empty artifact manifest' "$DOC"
grep -q 'stale index manifest digest' "$DOC"
grep -q 'mismatched record manifest digest' "$DOC"
grep -q 'template-only evidence' "$DOC"
grep -q 'placeholder evidence' "$DOC"
grep -q 'empty blocker status' "$DOC"
grep -q 'does not checksum real release artifacts' "$DOC"
grep -q 'does not compare real release artifact hashes against `SHA256SUMS`' "$DOC"
grep -q 'does not verify detached signatures' "$DOC"
grep -q 'does not prove artifact authenticity' "$DOC"
grep -q 'does not create or approve candidate evidence' "$DOC"
grep -q 'does not approve release signing' "$DOC"
grep -q 'Fixture checksum coverage is not candidate evidence' "$DOC"
grep -q 'Fixture checksum coverage is not signed artifact verification' "$DOC"
grep -q 'Fixture checksum coverage is not release approval' "$DOC"

grep -q 'artifact_manifest' "$PACKAGE_FIXTURE"
grep -q 'expect_rejects "mismatched artifact manifest"' "$PACKAGE_FIXTURE"
grep -q 'expect_rejects "template-only evidence"' "$PACKAGE_FIXTURE"
grep -q 'expect_rejects "placeholder evidence"' "$PACKAGE_FIXTURE"
grep -q 'expect_rejects "empty blocker status"' "$PACKAGE_FIXTURE"

grep -q 'ARTIFACT_MANIFEST' "$MANIFEST_FIXTURE"
grep -q 'artifact_manifest_sha256' "$MANIFEST_FIXTURE"
grep -q 'sha256_file "$package_dir/ARTIFACT_MANIFEST"' "$MANIFEST_FIXTURE"
grep -q 'expect_rejects "missing artifact manifest"' "$MANIFEST_FIXTURE"
grep -q 'expect_rejects "empty artifact manifest"' "$MANIFEST_FIXTURE"
grep -q 'expect_rejects "stale index manifest digest"' "$MANIFEST_FIXTURE"
grep -q 'expect_rejects "mismatched record manifest digest"' "$MANIFEST_FIXTURE"
grep -q 'expect_rejects "template-only evidence"' "$MANIFEST_FIXTURE"
grep -q 'expect_rejects "placeholder evidence"' "$MANIFEST_FIXTURE"

printf 'release signing candidate evidence package checksum audit confirms fixture coverage and limits\n'
