#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MOBILE_DIR="$ROOT_DIR/apps/mobile"

require_file() {
  local path="$1"
  if [[ ! -f "$ROOT_DIR/$path" ]]; then
    echo "missing required mobile skeleton file: $path" >&2
    exit 1
  fi
}

require_text() {
  local path="$1"
  local text="$2"
  if ! grep -F -q "$text" "$ROOT_DIR/$path"; then
    echo "missing required mobile skeleton text in $path: $text" >&2
    exit 1
  fi
}

reject_find() {
  local description="$1"
  shift
  if find "$MOBILE_DIR" "$@" -print -quit | grep -q .; then
    echo "mobile skeleton must not contain $description" >&2
    exit 1
  fi
}

require_file "apps/mobile/README.md"
require_file "apps/mobile/android/README.md"
require_file "apps/mobile/ios/README.md"
require_file "apps/mobile/ffi/README.md"

require_text "apps/mobile/README.md" "documentation-only boundary"
require_text "apps/mobile/README.md" "Mobile clients are not part of the current"
require_text "apps/mobile/README.md" "unsigned experimental public beta"
require_text "apps/mobile/README.md" "sensitive"
require_text "apps/mobile/README.md" "not audited"
require_text "apps/mobile/README.md" "not production-ready"
require_text "apps/mobile/README.md" "external onion delivery not"
require_text "apps/mobile/README.md" "Status Screen Copy Boundary"
require_text "apps/mobile/README.md" "documentation-only candidates"
require_text "apps/mobile/README.md" "Status screens may show status only"
require_text "apps/mobile/README.md" "redacted status only"
require_text "apps/mobile/README.md" "not connected"
require_text "apps/mobile/README.md" "manual action required"
require_text "apps/mobile/README.md" "Status screen labels may project only"
require_text "apps/mobile/README.md" "profile lock state"
require_text "apps/mobile/README.md" "runtime command surface"
require_text "apps/mobile/README.md" "mobile command surface"
require_text "apps/mobile/README.md" "public non-claims"
require_text "apps/mobile/README.md" "must not show send now"
require_text "apps/mobile/README.md" "receive in background"
require_text "apps/mobile/README.md" "push delivery enabled"
require_text "apps/mobile/README.md" "connected to peer"
require_text "apps/mobile/README.md" "onion delivery verified"
require_text "apps/mobile/README.md" "security-ready claims"
require_text "apps/mobile/README.md" "Install/Update Screen Copy Boundary"
require_text "apps/mobile/README.md" "manual update verification required"
require_text "apps/mobile/README.md" "same GitHub Release artifact"
require_text "apps/mobile/README.md" "same release checksum"
require_text "apps/mobile/README.md" "public provenance"
require_text "apps/mobile/README.md" "release manifest"
require_text "apps/mobile/README.md" "release notes"
require_text "apps/mobile/README.md" "dependency evidence"
require_text "apps/mobile/README.md" "store trust not claimed"
require_text "apps/mobile/README.md" "auto-update available"
require_text "apps/mobile/README.md" "automatic update"
require_text "apps/mobile/README.md" "update installed automatically"
require_text "apps/mobile/README.md" "Play Store verified"
require_text "apps/mobile/README.md" "App Store verified"
require_text "apps/mobile/README.md" "TestFlight verified"
require_text "apps/mobile/README.md" "store approved security"
require_text "apps/mobile/README.md" "mobile review security"
require_text "apps/mobile/README.md" "platform signing security"
require_text "apps/mobile/README.md" "notarization security"
require_text "apps/mobile/README.md" "branch checksum accepted"
require_text "apps/mobile/README.md" "source archive checksum accepted"
require_text "apps/mobile/README.md" "copied checksum accepted"
require_text "apps/mobile/README.md" "Backup-Exclusion Screen Copy Boundary"
require_text "apps/mobile/README.md" "backup exclusion status only"
require_text "apps/mobile/README.md" "app-private storage required"
require_text "apps/mobile/README.md" "app-container storage required"
require_text "apps/mobile/README.md" "backup exclusion marker written by wrapper"
require_text "apps/mobile/README.md" "backup exclusion marker verified by wrapper"
require_text "apps/mobile/README.md" "platform verification token present"
require_text "apps/mobile/README.md" "cloud backup not claimed"
require_text "apps/mobile/README.md" "backup recovery not claimed"
require_text "apps/mobile/README.md" "rollback prevention not claimed"
require_text "apps/mobile/README.md" "secure deletion not claimed"
require_text "apps/mobile/README.md" "cloud backup enabled"
require_text "apps/mobile/README.md" "cloud sync enabled"
require_text "apps/mobile/README.md" "backup recovery available"
require_text "apps/mobile/README.md" "rollback prevention guaranteed"
require_text "apps/mobile/README.md" "secure deletion guaranteed"
require_text "apps/mobile/README.md" "shared external storage allowed"
require_text "apps/mobile/README.md" "shared app group storage allowed"
require_text "apps/mobile/README.md" "iCloud backup available"
require_text "apps/mobile/README.md" "Google backup available"
require_text "apps/mobile/README.md" "backup complete"
require_text "apps/mobile/README.md" "data safe after device restore"
require_text "apps/mobile/README.md" "Local Data Lifecycle Screen Copy Boundary"
require_text "apps/mobile/README.md" "local data lifecycle status only"
require_text "apps/mobile/README.md" "conversation delete available"
require_text "apps/mobile/README.md" "conversation delete preserves session"
require_text "apps/mobile/README.md" "session delete available"
require_text "apps/mobile/README.md" "session delete preserves messages"
require_text "apps/mobile/README.md" "profile delete available"
require_text "apps/mobile/README.md" "full local wipe available"
require_text "apps/mobile/README.md" "passphrase-first unlock required"
require_text "apps/mobile/README.md" "encrypted store required"
require_text "apps/mobile/README.md" "backup exclusion best-effort only"
require_text "apps/mobile/README.md" "rollback detection marker only"
require_text "apps/mobile/README.md" "secure deletion not claimed"
require_text "apps/mobile/README.md" "store path shown"
require_text "apps/mobile/README.md" "passphrase retained"
require_text "apps/mobile/README.md" "plaintext exposed"
require_text "apps/mobile/README.md" "key material exposed"
require_text "apps/mobile/README.md" "remote wipe available"

require_text "apps/mobile/android/README.md" "documentation-only skeleton"
require_text "apps/mobile/android/README.md" "not a Gradle project"
require_text "apps/mobile/android/README.md" "not an APK or AAB artifact"
require_text "apps/mobile/android/README.md" "not Android app readiness"
require_text "apps/mobile/android/README.md" "thin Kotlin shell over UniFFI or another"
require_text "apps/mobile/android/README.md" "must not define independent protocol, storage, transport"

require_text "apps/mobile/ios/README.md" "documentation-only skeleton"
require_text "apps/mobile/ios/README.md" "not an Xcode project"
require_text "apps/mobile/ios/README.md" "not an IPA artifact"
require_text "apps/mobile/ios/README.md" "not TestFlight distribution"
require_text "apps/mobile/ios/README.md" "not iOS app readiness"
require_text "apps/mobile/ios/README.md" "thin Swift shell over UniFFI or another"
require_text "apps/mobile/ios/README.md" "must not define independent protocol, storage, transport"

require_text "apps/mobile/ffi/README.md" "documentation-only naming and API inventory"
require_text "apps/mobile/ffi/README.md" "not a UniFFI definition"
require_text "apps/mobile/ffi/README.md" "not generated bindings"
require_text "apps/mobile/ffi/README.md" "not Kotlin or Swift"
require_text "apps/mobile/ffi/README.md" "runtime source"
require_text "apps/mobile/ffi/README.md" "Allowed API groups mirror the shared core wrapper boundary"
require_text "apps/mobile/ffi/README.md" "shared_core_status_surface"
require_text "apps/mobile/ffi/README.md" "redacted_support_diagnostics"
require_text "apps/mobile/ffi/README.md" "must not export raw storage open calls"
require_text "apps/mobile/ffi/README.md" "security-ready claims"
require_text "apps/mobile/ffi/README.md" "Signature Placeholder Boundary"
require_text "apps/mobile/ffi/README.md" "documentation-only until a"
require_text "apps/mobile/ffi/README.md" "narrow handle-and-bytes shape"
require_text "apps/mobile/ffi/README.md" "opaque"
require_text "apps/mobile/ffi/README.md" "ProfileHandle"
require_text "apps/mobile/ffi/README.md" "canonical byte buffers"
require_text "apps/mobile/ffi/README.md" "redacted structured result objects"
require_text "apps/mobile/ffi/README.md" "explicit error codes"
require_text "apps/mobile/ffi/README.md" "caller-owned input buffers"
require_text "apps/mobile/ffi/README.md" "core-owned returned buffers"
require_text "apps/mobile/ffi/README.md" "explicit release"
require_text "apps/mobile/ffi/README.md" "explicit user action tokens"
require_text "apps/mobile/ffi/README.md" "does not define a"
require_text "apps/mobile/ffi/README.md" "callable mobile FFI"
require_text "apps/mobile/ffi/README.md" "stable ABI"
require_text "apps/mobile/ffi/README.md" "memory ownership contract"
require_text "apps/mobile/ffi/README.md" "serialization"
require_text "apps/mobile/ffi/README.md" "binding generation"
require_text "apps/mobile/ffi/README.md" "mobile app readiness"
require_text "apps/mobile/ffi/README.md" "Status Command DTO Boundary"
require_text "apps/mobile/ffi/README.md" "documentation-only redacted"
require_text "apps/mobile/ffi/README.md" "not a callable command surface"
require_text "apps/mobile/ffi/README.md" "schema version"
require_text "apps/mobile/ffi/README.md" "profile lock"
require_text "apps/mobile/ffi/README.md" "runtime command surface"
require_text "apps/mobile/ffi/README.md" "mobile command surface"
require_text "apps/mobile/ffi/README.md" "public non-claims"
require_text "apps/mobile/ffi/README.md" "profile paths"
require_text "apps/mobile/ffi/README.md" "database paths"
require_text "apps/mobile/ffi/README.md" "network endpoints"
require_text "apps/mobile/ffi/README.md" "delivery runtime handles"
require_text "apps/mobile/ffi/README.md" "push tokens"
require_text "apps/mobile/ffi/README.md" "central account identifiers"
require_text "apps/mobile/ffi/README.md" "security-ready toggles"
require_text "apps/mobile/ffi/README.md" "DTO Serialization Placeholder Boundary"
require_text "apps/mobile/ffi/README.md" "documentation-only until a"
require_text "apps/mobile/ffi/README.md" "deterministic UTF-8 JSON object"
require_text "apps/mobile/ffi/README.md" "explicit schema version"
require_text "apps/mobile/ffi/README.md" "sorted keys"
require_text "apps/mobile/ffi/README.md" "string enums"
require_text "apps/mobile/ffi/README.md" "bounded arrays of status labels"
require_text "apps/mobile/ffi/README.md" "reject-unknown-fields"
require_text "apps/mobile/ffi/README.md" "does not define a serializer"
require_text "apps/mobile/ffi/README.md" "stable wire format"
require_text "apps/mobile/ffi/README.md" "cross-version migration"
require_text "apps/mobile/ffi/README.md" "raw logs"
require_text "apps/mobile/ffi/README.md" "support bundles"
require_text "apps/mobile/ffi/README.md" "crash dumps"
require_text "apps/mobile/ffi/README.md" "Redacted Diagnostics Payload Placeholder Boundary"
require_text "apps/mobile/ffi/README.md" "local-copy-only"
require_text "apps/mobile/ffi/README.md" "Allowed diagnostics payload fields"
require_text "apps/mobile/ffi/README.md" "failure class"
require_text "apps/mobile/ffi/README.md" "manual network permission"
require_text "apps/mobile/ffi/README.md" "app launch network boundary"
require_text "apps/mobile/ffi/README.md" "redacted runtime flags"
require_text "apps/mobile/ffi/README.md" "diagnostics redaction state"
require_text "apps/mobile/ffi/README.md" "Allowed diagnostics channels"
require_text "apps/mobile/ffi/README.md" "in-app redacted text view"
require_text "apps/mobile/ffi/README.md" "explicit user-initiated copy"
require_text "apps/mobile/ffi/README.md" "minimal private security contact request"
require_text "apps/mobile/ffi/README.md" "bridge lines"
require_text "apps/mobile/ffi/README.md" "pairing payloads"
require_text "apps/mobile/ffi/README.md" "envelope payloads"
require_text "apps/mobile/ffi/README.md" "Android logcat"
require_text "apps/mobile/ffi/README.md" "iOS"
require_text "apps/mobile/ffi/README.md" "sysdiagnose"
require_text "apps/mobile/ffi/README.md" "share-sheet private data prefill"

reject_find "Android build project files" \
  \( -name build.gradle -o -name settings.gradle -o -name AndroidManifest.xml \)
reject_find "iOS build project files" \
  \( -name Package.swift -o -name Info.plist -o -name '*.xcodeproj' -o -name '*.xcworkspace' \)
reject_find "mobile runtime or generated binding source" \
  \( -name '*.kt' -o -name '*.swift' -o -name '*.udl' \)
reject_find "mobile app artifacts" \
  \( -name '*.apk' -o -name '*.aab' -o -name '*.ipa' \)
reject_find "mobile build output directories" \
  \( -type d -name build -o -type d -name DerivedData \)

printf 'status=mobile-skeleton-boundary-verified\n'
