#!/usr/bin/env bash
set -euo pipefail

fail() {
  echo "error=$*" >&2
  exit 1
}

must_contain() {
  local file="$1"
  local needle="$2"
  grep -Fq "$needle" "$file" || fail "$file missing required text: $needle"
}

must_output_contain() {
  local text="$1"
  local needle="$2"
  printf '%s\n' "$text" | grep -Fq "$needle" || fail "missing required output: $needle"
}

must_not_match() {
  local file="$1"
  local pattern="$2"
  if grep -Eq "$pattern" "$file"; then
    fail "$file contains forbidden Windows public artifact candidate pattern: $pattern"
  fi
}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CORE="crates/core/src/lib.rs"
STATE="apps/desktop-tauri/src/action-state.js"
STATE_TEST="apps/desktop-tauri/src/action-state.test.js"
SMOKE_TEST="apps/desktop-tauri/src/ui-smoke.test.js"
TAURI_LIB="apps/desktop-tauri/src-tauri/src/lib.rs"
TAURI_STATUS="apps/desktop-tauri/src-tauri/src/status.rs"
REFERENCE="reference/WINDOWS_PUBLIC_ARTIFACT_CANDIDATE_GATE.md"
MANIFEST_SCHEMA="reference/WINDOWS_ARTIFACT_MANIFEST_CHECKSUM_SCHEMA.md"
RUNTIME_SCHEMA="reference/WINDOWS_REAL_RUNTIME_RESULT_SCHEMA.md"
RUNTIME_CONTRACT="scripts/windows_artifact_runtime_evidence_contract_once.sh"
SIGNING_REPUTATION="scripts/windows_code_signing_reputation_boundary_once.sh"

for file in "$CORE" "$STATE" "$STATE_TEST" "$SMOKE_TEST" "$TAURI_LIB" "$TAURI_STATUS" \
  "$REFERENCE" "$MANIFEST_SCHEMA" "$RUNTIME_SCHEMA" "$RUNTIME_CONTRACT" "$SIGNING_REPUTATION"; do
  [ -f "$file" ] || fail "missing Windows public artifact candidate gate input: $file"
done

for file in "$CORE" "$STATE" "$REFERENCE"; do
  must_contain "$file" "windows-shell-nsis-exe-installer-candidate"
  must_contain "$file" "runtime_mode"
  must_contain "$file" "onion_runtime_compiled"
  must_contain "$file" "webview2_runtime_required"
  must_contain "$file" "app_data_resolver_shared_storage_semantics"
  must_contain "$file" "manifest_checksum_provenance_required"
  must_contain "$file" "runtime_result_external_peer_evidence_separated"
  must_contain "$file" "engine_sidecar_required"
  must_contain "$file" "engine_sidecar_manual_self_test_command"
  must_contain "$file" "smartscreen_security_boundary_claimed"
  must_contain "$file" "windows_public_artifact_ready"
  must_contain "$file" "windows_production_claim_allowed"
done

must_contain "$CORE" "production_windows_public_artifact_candidate_summary"
must_contain "$CORE" "PRODUCTION_WINDOWS_PUBLIC_ARTIFACT_REQUIRED_FIELDS"
must_contain "$CORE" "PRODUCTION_WINDOWS_PUBLIC_ARTIFACT_FORBIDDEN_CLAIMS"
must_contain "$CORE" "windows_public_artifact_candidate_keeps_claims_false_and_shared_core_bound"

must_contain "$STATE" "productionWindowsPublicArtifactCandidateView"
must_contain "apps/desktop-tauri/package.json" "engine:prepare-sidecar:release:manual && node scripts/with-cargo-target.mjs tauri build --config src-tauri/tauri.sidecar.conf.json --features public-shell"
must_contain "$STATE_TEST" "windows public artifact candidate keeps installer and security claims false"
must_contain "$SMOKE_TEST" "productionWindowsPublicArtifactCandidateView"
must_contain "$TAURI_LIB" "windows_public_artifact_adapter_boundary_summary"
must_contain "$TAURI_LIB" "WINDOWS_PUBLIC_ARTIFACT_ADAPTER_POLICIES"
must_contain "$TAURI_LIB" "windows-shell-nsis-exe-installer-candidate"
must_contain "$TAURI_LIB" "runtime_mode"
must_contain "$TAURI_LIB" "onion_runtime_compiled"
must_contain "$TAURI_LIB" "tauri-app-data"
must_contain "$TAURI_LIB" "app_data_resolver_public_support_safe"
must_contain "$TAURI_LIB" "app_data_resolver_shared_storage_semantics"
must_contain "$TAURI_LIB" "raw_local_path_returned"
must_contain "$TAURI_LIB" "support_report_raw_path_allowed"
must_contain "$TAURI_LIB" "encrypted_store_required"
must_contain "$TAURI_LIB" "local_delete_wipe_semantics_shared_core"
must_contain "$TAURI_LIB" "runtime_result_external_peer_evidence_separated"
must_contain "$TAURI_LIB" "windows_app_data_path_review_required"
must_contain "$TAURI_LIB" "windows_redacted_diagnostics_behavior_review_required"
must_contain "$TAURI_LIB" "windows_public_artifact_adapter_keeps_app_data_shared_core_and_redacted"
must_contain "$TAURI_STATUS" "windows_public_artifact_adapter_boundary_summary"
must_contain "$TAURI_STATUS" "windows_app_data_path_review_required={}"
must_contain "$TAURI_STATUS" "remaining_blocker=real-windows-artifact-runtime-manifest-evidence"

must_contain "$REFERENCE" "windows_public_artifact_candidate=true"
must_contain "$REFERENCE" "runtime_mode=shell-sidecar-pending"
must_contain "$REFERENCE" "onion_runtime_compiled=false"
must_contain "$REFERENCE" "bundle_target=nsis"
must_contain "$REFERENCE" "default_extension=.exe"
must_contain "$REFERENCE" "portable_default_allowed=false"
must_contain "$REFERENCE" "msi_alternative_allowed=true"
must_contain "$REFERENCE" "webview2_failure_class_redacted=true"
must_contain "$REFERENCE" "app_data_resolver_public_support_safe=true"
must_contain "$REFERENCE" "encrypted_store_required=true"
must_contain "$REFERENCE" "raw_local_path_returned=false"
must_contain "$REFERENCE" "shared_core_bypass_allowed=false"
must_contain "$REFERENCE" "local_delete_wipe_semantics_shared_core=true"
must_contain "$REFERENCE" "manifest_checksum_provenance_required=true"
must_contain "$REFERENCE" "windows_runtime_result_packet_required_for_public_artifact=true"
must_contain "$REFERENCE" "windows_manifest_checksum_provenance_separate_from_runtime_result=true"
must_contain "$REFERENCE" "runtime_result_external_peer_evidence_separated=true"
must_contain "$REFERENCE" "engine_sidecar_required=true"
must_contain "$REFERENCE" "engine_sidecar_packaged_required=true"
must_contain "$REFERENCE" "engine_sidecar_runtime_mode=manual-e2ee-engine-sidecar"
must_contain "$REFERENCE" "engine_sidecar_manual_self_test_required=true"
must_contain "$REFERENCE" "engine_sidecar_raw_path_returned=false"
must_contain "$REFERENCE" "engine_sidecar_stdout_returned=false"
must_contain "$REFERENCE" "engine_sidecar_stderr_returned=false"
must_contain "$REFERENCE" "real_windows_runtime_result_present=false"
must_contain "$REFERENCE" "windows_runtime_result_fixture_promoted_to_public_artifact=false"
must_contain "$REFERENCE" "windows_non_windows_runtime_result_promoted=false"
must_contain "$REFERENCE" "windows_local_or_fabricated_runtime_result_promoted=false"
must_contain "$REFERENCE" "local_runtime_promoted_to_delivery_proof=false"
must_contain "$REFERENCE" "smartscreen_security_boundary_claimed=false"
must_contain "$REFERENCE" "code_signing_security_boundary_claimed=false"
must_contain "$REFERENCE" "store_reputation_security_boundary_claimed=false"
must_contain "$REFERENCE" "auto_update_claimed=false"
must_contain "$REFERENCE" "windows_public_artifact_upload_allowed=false"
must_contain "$REFERENCE" "windows_public_artifact_claim_allowed=false"
must_contain "$REFERENCE" "windows_installer_claim_allowed=false"
must_contain "$REFERENCE" "windows_upload_claim_allowed=false"
must_contain "$REFERENCE" "windows_production_claim_allowed=false"

must_contain "$RUNTIME_CONTRACT" "status=windows-artifact-runtime-evidence-contract-ready"
must_contain "$RUNTIME_CONTRACT" "windows_artifact_manifest_fixture_accepted=true"
must_contain "$RUNTIME_CONTRACT" "windows_runtime_result_fixture_accepted=true"
must_contain "$RUNTIME_CONTRACT" "real_windows_runtime_result_present=false"
must_contain "$RUNTIME_CONTRACT" "windows_runtime_result_packet_required_for_public_artifact=true"
must_contain "$RUNTIME_CONTRACT" "windows_manifest_checksum_provenance_separate_from_runtime_result=true"
must_contain "$RUNTIME_CONTRACT" "windows_runtime_result_fixture_promoted_to_public_artifact=false"
must_contain "$RUNTIME_CONTRACT" "windows_result_requires_real_windows_machine=true"
must_contain "$RUNTIME_CONTRACT" "windows_non_windows_runtime_result_promoted=false"
must_contain "$RUNTIME_CONTRACT" "windows_local_or_fabricated_runtime_result_promoted=false"
must_contain "$RUNTIME_CONTRACT" "windows_result_rejects_private_local_app_data=true"
must_contain "$RUNTIME_CONTRACT" "windows_result_engine_sidecar_diagnostics_verified=true"
must_contain "$RUNTIME_CONTRACT" "windows_result_engine_sidecar_manual_self_test_verified=true"
must_contain "$RUNTIME_CONTRACT" "windows_strict_current_head_rejects_stale_evidence=true"

runtime_contract_output="$("$RUNTIME_CONTRACT")"
must_output_contain "$runtime_contract_output" "status=windows-artifact-runtime-evidence-contract-ready"
must_output_contain "$runtime_contract_output" "real_windows_runtime_result_present=false"
must_output_contain "$runtime_contract_output" "windows_runtime_result_packet_required_for_public_artifact=true"
must_output_contain "$runtime_contract_output" "windows_manifest_checksum_provenance_separate_from_runtime_result=true"
must_output_contain "$runtime_contract_output" "windows_non_windows_runtime_result_promoted=false"
must_output_contain "$runtime_contract_output" "windows_local_or_fabricated_runtime_result_promoted=false"
must_output_contain "$runtime_contract_output" "windows_public_artifact_ready=false"
must_output_contain "$runtime_contract_output" "windows_result_engine_sidecar_diagnostics_verified=true"
must_output_contain "$runtime_contract_output" "windows_result_engine_sidecar_manual_self_test_verified=true"

signing_reputation_output="$("$SIGNING_REPUTATION")"
must_output_contain "$signing_reputation_output" "windows_code_signing_reputation_boundary=source-ready"
must_output_contain "$signing_reputation_output" "windows_signing_ready=false"
must_output_contain "$signing_reputation_output" "code_signing_security_boundary_claimed=false"

for file in "$STATE" "$TAURI_LIB" "$TAURI_STATUS" "$REFERENCE"; do
  must_not_match "$file" "windows_public_artifact_ready[=:] ?true"
  must_not_match "$file" "windows_installer_ready[=:] ?true"
  must_not_match "$file" "windows_signing_ready[=:] ?true"
  must_not_match "$file" "windows_public_artifact_upload_allowed[=:] ?true"
  must_not_match "$file" "windows_production_claim_allowed[=:] ?true"
  must_not_match "$file" "smartscreen_security_boundary_claimed[=:] ?true"
  must_not_match "$file" "local_runtime_promoted_to_delivery_proof[=:] ?true"
  must_not_match "$file" "shared_core_bypass_allowed[=:] ?true"
done

echo "status=windows-public-artifact-candidate-gate-ready"
echo "windows_public_artifact_candidate=true"
echo "artifact_type=windows-shell-nsis-exe-installer-candidate"
echo "bundle_target=nsis"
echo "runtime_mode=shell-sidecar-pending"
echo "onion_runtime_compiled=false"
echo "webview2_runtime_required=true"
echo "app_data_resolver_shared_storage_semantics=true"
echo "app_data_resolver_public_support_safe=true"
echo "windows_app_data_path_review_required=false"
echo "windows_redacted_diagnostics_behavior_review_required=false"
echo "manifest_checksum_provenance_required=true"
echo "windows_runtime_result_packet_required_for_public_artifact=true"
echo "windows_manifest_checksum_provenance_separate_from_runtime_result=true"
echo "runtime_evidence_contract_verified=true"
echo "windows_code_signing_reputation_boundary=source-ready"
echo "runtime_result_external_peer_evidence_separated=true"
echo "engine_sidecar_required=true"
echo "engine_sidecar_packaged_required=true"
echo "engine_sidecar_runtime_mode=manual-e2ee-engine-sidecar"
echo "engine_sidecar_manual_self_test_required=true"
echo "real_windows_runtime_result_present=false"
echo "windows_runtime_result_fixture_promoted_to_public_artifact=false"
echo "windows_non_windows_runtime_result_promoted=false"
echo "windows_local_or_fabricated_runtime_result_promoted=false"
echo "windows_public_artifact_ready=false"
echo "windows_public_artifact_claim_allowed=false"
echo "windows_installer_claim_allowed=false"
echo "windows_upload_claim_allowed=false"
echo "windows_production_claim_allowed=false"
