[package]
name = "another-dimension-tools"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
base64ct = { version = "1.8.3", features = ["alloc"] }
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["zeroize"] }
sha2 = "0.10.9"
serde_json = { version = "1.0.149", features = ["preserve_order"] }
